### ISSUE TITLE
booking with addons SSR [UMNR] error

### ISSUE THREAD

**Issue by yatinmistry** [Travelport/travelport-uapi-tutorial-php#10]
Hello,

While booking addons, i am getting error, **Free text is required for this type of SSR [UMNR]**
In travelport demo i have checked with same code (in my test credentials and preproduction environment)with it has no error.
1. How can we pass freetext in AirCreateReservation request while booking with addons?
2. In which addons (SSR codes) , we have to pass Free Text. Please provide SSR code list ?

Please refer attached request and response.

[AirCreateReservation_with_addons_response.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/222187/AirCreateReservation_with_addons_response.txt)
[AirCreateReservation_with_addons_request.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/222188/AirCreateReservation_with_addons_request.txt)

Thanks,

Yatin mistry

**Comment by yatinmistry** [comment]
Hello Tech Team,

Waiting for reply.

Thanks,

Yatin Mistry

**Comment by vivekjyotipramanik** [comment]
Hi Yatin,

Apologies for the delay. SSR is required as part of AirBooking for most of the carriers . Please find below the details about the SSR. Please let me know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Air_Booking/Create_Air_Booking/Air_Booking_with_SSRs.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAir%2520Booking%7CCreating%2520Air%2520Bookings%7CAir%2520Booking%2520Modifiers%7C_____8

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Shared_Air_Topics/SSRs_(Special_Service_Requests).htm%3FTocPath%3DUniversal%2520Records%2520and%2520Bookings%7CAssociated%2520Topics%7C_____10

Thanks & Regards
Vivekjyoti Pramanik

**Comment by yatinmistry** [comment]
Hello Vivekjyoti,

Thanks for reply. But how to pass freetext ? 
I am trying to book optional services addons which is coming in AirPriceResp.
 
Please give a example.

Thanks,
Yatin Mistry

**Comment by yatinmistry** [comment]
Hello Vivekjyoti,

Thanks for the help. Issue resolved.

Needed Format for free text is as below,

**LANGUAGE DETAILS/FIRST NAME/AGE AND SEX/PASSENGER CONTACT NAMES AND ADDRESSES AND TELEPHONE NUMBERS|SI.UMNR**

I have passed in api as 
**SSRFreeText="en/Santosh/male/9090909090|SI.UMNR"**


In which addons (SSR codes) , we have to pass Free Text. Please provide SSR code list ?

Thanks,
Yatin Mistry

**Comment by vivekjyotipramanik** [comment]
Hi Yatin,

Apologies for the delay, as I was in a conference for the last 4 days, I could not answer the questions. 
The document SSR codes are of three kinds, DOCO, DOCA and DOCS.

1. For the DOCS SSR, the Travel document type, Travel Document Issuing Country/State, and Travel Document Number fields must all be entered or none of them should be entered. 

SSR Type="DOCS" FreeText="P/GB/S12345678/GB/12JUN63/M/23OCT14/SMITH/JOHN" Carrier="U2"/>

2. For the DOCA SSR, if the Address type is specified (R-Residential or D-Destination address), then the country of the address should also be specified and vice versa.

SSR Type="DOCA" FreeText="HK1/R/US/1600 SMITH ST/HOUSTON/TX/77001" Carrier="BA" 

3. For the DOCO SSR, the requirements for visa information vary by provider. For all providers, the Supplementary Travel Information document type (e.g., Visa) and Supplementary Travel Information Number (e.g., Visa Number) fields must both be entered, or neither should be entered. 

Document types of 'R': Redress Number and 'K': Known Traveler Number can be input in the DOCO SSR with their respective number. Both a Redress Number or Known Traveler Number type always needs a supplementary Travel Information Number. 

In a DOCO SSR, a Redress Number must be accompanied by a DOCS SSR for the traveler. 

In all cases, validation is performed by the provider.

SSR Type="DOCO" HK1//V/9891404/LONDON/14MAR07/USA-1SMITH/JOHNMR Carrier="BA"

Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik
