### ISSUE TITLE
Authentication Result Error Message Response (77): User account is locked.

### ISSUE THREAD

**Issue by sgatrip** [Travelport/travelport-uapi-tutorial-php#100]
I am having an issue with my travelport universal api test account
my Branch Code for Galileo (1G): P7004943
when I try it with example codes locally i get error in response like this:
Authentication Result Error Message Response (77): User account is locked.
can you please help me asap.

**Comment by vivekjyotipramanik** [comment]
Hi sgatrip,

Could you please provide the username you are using. We will need both TargetBranch & Username both to unlock the account. Thanks.

**Comment by sgatrip** [comment]
Universal API/uAPI4610084718-a7e18c20

thank you

**Comment by sgatrip** [comment]
waiting update
thanks

**Comment by vivekjyotipramanik** [comment]
Hi sgatrip,

We are working on this and will provide an update as soon as the account is unlocked. Thanks.

**Comment by ericjoyal** [comment]
Hi vivekjyotipramanik,

using the credential provided I also get the following error:
 Authentication Result Error Message Response (77): User account is locked.

Could you please unlock my account as well? My userdata are:
 Universal API User ID: Universal API/uAPI4666307696-d0547470
 Branch Code for Worldspan (1P): P107351

Thanks!

**Comment by vivekjyotipramanik** [comment]
Hi ericjoyal,

We have unlocked the account. Could you please try again. Please let us know how it goes. Thanks.

**Comment by ericjoyal** [comment]
Hi vivekjyotipramanik,

It seems to work. Thanks.

**Comment by MRZMUH001** [comment]
Hi vivekjyotipramanik,

Can you please also unlock my credentials. 

Universal API User ID: Universal API/uAPI2656018225
Branch Code for Galileo (1G): P105221

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi MRZMUH001,

We have unlocked the credential. Could you please try again. Please let us know how it goes. Thanks.

**Comment by ShreyaS10** [comment]
Hi!,

I am getting the following error:
Authentication Result Error Message Response (77): User account is locked.

Could you please unlock my account as well? My credentials are:
Universal API User ID: Universal API/uAPI4823947828-11b28eb3
Branch Code for Galileo (1G): P7038872

Thanks!

**Comment by NirandaG** [comment]
This has been unlocked. Please use correct username and password to avoid getting this locked again.
Rgds,
Niranda

**Comment by NirandaG** [comment]
Hi,
This has been unlocked.
Please use correct username and password to avoid this getting locked again.
Rgds,
Niranda

**Comment by NirandaG** [comment]
Hi,
This has been unlocked and please make sure you use correct username and password to avoid this getting locked again.
Rgds,
Niranda

**Comment by lovegame007** [comment]
if you can unlock 
TARGETBRANCH: P105145
CREDENTIALS: Universal API/uAPI-555184191
Provider: 1G

Thank you.
