### ISSUE TITLE
How to get number of Seats available in LowFareSearchRes Air

### ISSUE THREAD

**Issue by itsmohdabrar** [Travelport/travelport-uapi-tutorial-php#102]
Hi

I need to know how i can get the **Numbers** of **AVAILABLE SEATS** available for particular journey/segment in _LowFareSearchRes_ of AIR.

Please Let me know ASAP.

Thanks in Advance

**Comment by vivekjyotipramanik** [comment]
Hi itsmohdabrar,

We ca use the SeatMapReq/Rsp to get the number of available seats in a given flight. Please find below the link with all the details. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Seat%20Maps/Seat_Maps.htm%3FTocPath%3DAir%7CSeat%2520Maps%7C_____0

**Comment by itsmohdabrar** [comment]
@vivekjyotipramanik  , Thank you so much it helped me.
