### ISSUE TITLE
To get commission payback from airline while booking (AirCreateReservationReq)

### ISSUE THREAD

**Issue by sawood** [Travelport/travelport-uapi-tutorial-php#104]
Hi

We are getting commission payback for some of the airlines,to get the commission payback we are using the entry '_TMVZ0_' in Galileo SmartPoint.

I need the same process through **XML** (webservices) 

I tried this

`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header />
  <s:Body>
    <univ:AirCreateReservationReq xmlns:common_v39_0="http://www.travelport.com/schema/common_v39_0" xmlns:univ="http://www.travelport.com/schema/universal_v39_0" AuthorizedBy="user" TraceId="cc1d8ff8d4ecf0822665000b486b233c" TargetBranch="********" xmlns="http://www.travelport.com/schema/air_v39_0" RetainReservation="None">
      <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v39_0" OriginApplication="UAPI"></BillingPointOfSaleInfo>
      <BookingTraveler Key="0" TravelerType="ADT" DOB="1946-10-10" Gender="M" xmlns="http://www.travelport.com/schema/common_v39_0">
        <BookingTravelerName Prefix="Mr" First="tesfdfsd" Last="tesfdfsdsdfsfsd"></BookingTravelerName>
        <PhoneNumber Number="98765421025" Type="Mobile"></PhoneNumber>
        <Email EmailID="test@test.com" Type="P"></Email>
        <SSR Carrier="KE" FreeText="P/IN/4565443534/IN/10Oct46/M/24Oct23/sdfsfsd/tesfdfsd" Status="HK" Type="DOCS" />
        <Address>
          <AddressName> , US</AddressName>
          <Street></Street>
          <City></City>
          <PostalCode></PostalCode>
          <Country>US</Country>
        </Address>
      </BookingTraveler>
      <FormOfPayment xmlns="http://www.travelport.com/schema/common_v39_0" Type="Cash"></FormOfPayment>
      <AirPricingSolution Key="11L018cB0BKApB5tkHAAAA==" TotalPrice="AED2890" BasePrice="INR30000" ApproximateTotalPrice="AED2890" ApproximateBasePrice="AED1700" EquivalentBasePrice="AED1700" Taxes="AED1190" Fees="AED0" ApproximateTaxes="AED1190" QuoteDate="2017-10-24">
        <AirPricingInfo Key="11L018cB0BKAsB5tkHAAAA==" TotalPrice="AED2890" BasePrice="INR30000" ApproximateTotalPrice="AED2890" ApproximateBasePrice="AED1700" EquivalentBasePrice="AED1700" ApproximateTaxes="AED1190" Taxes="AED1190" LatestTicketingTime="2018-02-16T23:59:00.000+04:00" PricingMethod="Guaranteed" Refundable="true" IncludesVAT="false" ETicketability="Yes" PlatingCarrier="KE" ProviderCode="1G">
          <FareInfo Key="11L018cB0BKA0B5tkHAAAA==" FareBasis="QEEIC" PassengerTypeCode="ADT" Origin="DEL" Destination="PEK" EffectiveDate="2017-10-24T15:12:00.000+04:00" DepartureDate="2018-02-16" Amount="AED850" NotValidAfter="2018-05-16" TaxAmount="AED590.00">
            <FareRuleKey FareInfoRef="11L018cB0BKA0B5tkHAAAA==" ProviderCode="1G">6UUVoSldxwgP2ZjIlnPlJsbKj3F8T9EyxsqPcXxP0TIjSPOlaHfQe5cuasWd6i8Dly5qxZ3qLwOXLmrFneovA5cuasWd6i8Dly5qxZ3qLwOXLmrFneovA2lYQhPu//wQM3ExqSoG053Ma3FfzOfuOUY3Fxmg5+olQu0ZscBMSQ7/yqZm8ZlXA+V5Ab9/KZMe0JtU/wbuhWCF/oTXxxF6MeJYtF79PC3YfoLT9JoAKrPVW5TpURjX8fi8hntICB5n7uWkLLHGDfjg2BMJ0qOmdTyy/Q52QOiI0tyLIzIB/QMovxbXQMnk1vwBShF29N4Sv4Xvb2u1Qx+/he9va7VDH7+F729rtUMfv4Xvb2u1Qx8Qxibp/OJehpo2LrM59tO1jp8ZENljzx72lVAJ3nO/P0rwFjNalI3BTHkcjklkZw0+IFOFCl3IxSTnU814VWHi</FareRuleKey>
            <Brand Key="11L018cB0BKA0B5tkHAAAA==" BrandID="91074" UpSellBrandID="91075" Name="Economy Class" Carrier="KE">
              <Title Type="External" LanguageCode="EN">Economy Class</Title>
              <Title Type="Short" LanguageCode="EN">Economy</Title>
              <Text Type="MarketingConsumer" LanguageCode="EN">Affordable luxury features highest-quality service from departure to arrival. Great design, more personal space, this 18-inch wide seat with 121-degree reclining back support has 34 inches of space between you and the next row of seats, and provides personal comfort unlike any other economy-class seat.

An 8.4-inch high-resolution LCD wide screen with state-of-the-art audio and video on demand (AVOD) makes channel selection easy and your flight more enjoyable.

- Include inflight meals
- Include carry on bag
- Include checked baggage
- Include seat selection

Note: Type and size of seat and its available features may vary depending on the flight route, time and aircraft.

Note: Type and size of seat and its available features may vary depending on the flight route, time and aircraft.</Text>
              <Text Type="MarketingAgent" LanguageCode="EN">Affordable luxury features highest-quality service from departure to arrival. Great design, more personal space, this 18-inch wide seat with 121-degree reclining back support has 34 inches of space between you and the next row of seats, and provides personal comfort unlike any other economy-class seat.

An 8.4-inch high-resolution LCD wide screen with state-of-the-art audio and video on demand (AVOD) makes channel selection easy and your flight more enjoyable.

- Include inflight meals
- Include carry on bag
- Include checked baggage
- Include seat selection

Note: Type and size of seat and its available features may vary depending on the flight route, time and aircraft.</Text>
              <Text Type="Strapline" LanguageCode="EN">Best-in-class comfort in the air</Text>
              <ImageLocation Type="Agent" ImageWidth="150" ImageHeight="150">https://cdn.travelport.com/koreanair/KE_general_medium_1228.jpg</ImageLocation>
              <ImageLocation Type="Consumer" ImageWidth="1333" ImageHeight="800">https://cdn.travelport.com/koreanair/KE_general_large_45850.jpg</ImageLocation>
            </Brand>
          </FareInfo>
          <FareInfo Key="11L018cB0BKABC5tkHAAAA==" FareBasis="QEEIC" PassengerTypeCode="ADT" Origin="PEK" Destination="DEL" EffectiveDate="2017-10-24T15:12:00.000+04:00" DepartureDate="2018-02-24" Amount="AED850" NotValidAfter="2018-05-16" TaxAmount="AED600.00">
            <FareRuleKey FareInfoRef="11L018cB0BKABC5tkHAAAA==" ProviderCode="1G">6UUVoSldxwgP2ZjIlnPlJsbKj3F8T9EyxsqPcXxP0TIjSPOlaHfQe5cuasWd6i8Dly5qxZ3qLwOXLmrFneovA5cuasWd6i8Dly5qxZ3qLwOXLmrFneovA2lYQhPu//wQM3ExqSoG052UHcuWlOZd4XSryiL7uiM383f1UwCbb2X/yqZm8ZlXA+V5Ab9/KZMeoqpf07fzK+WF/oTXxxF6MeJYtF79PC3YfoLT9JoAKrPVW5TpURjX8fi8hntICB5n7uWkLLHGDfhJ6dYYb68oBzyy/Q52QOiIVDcu+XlVEREovxbXQMnk1vwBShF29N4Sv4Xvb2u1Qx+/he9va7VDH7+F729rtUMfv4Xvb2u1Qx8Qxibp/OJehpo2LrM59tO1jp8ZENljzx72lVAJ3nO/P0rwFjNalI3BTHkcjklkZw0+IFOFCl3IxSTnU814VWHi</FareRuleKey>
            <Brand Key="11L018cB0BKABC5tkHAAAA==" BrandID="91074" UpSellBrandID="91075" Name="Economy Class" Carrier="KE">
              <Title Type="External" LanguageCode="EN">Economy Class</Title>
              <Title Type="Short" LanguageCode="EN">Economy</Title>
              <Text Type="MarketingConsumer" LanguageCode="EN">Affordable luxury features highest-quality service from departure to arrival. Great design, more personal space, this 18-inch wide seat with 121-degree reclining back support has 34 inches of space between you and the next row of seats, and provides personal comfort unlike any other economy-class seat.

An 8.4-inch high-resolution LCD wide screen with state-of-the-art audio and video on demand (AVOD) makes channel selection easy and your flight more enjoyable.

- Include inflight meals
- Include carry on bag
- Include checked baggage
- Include seat selection

Note: Type and size of seat and its available features may vary depending on the flight route, time and aircraft.

Note: Type and size of seat and its available features may vary depending on the flight route, time and aircraft.</Text>
              <Text Type="MarketingAgent" LanguageCode="EN">Affordable luxury features highest-quality service from departure to arrival. Great design, more personal space, this 18-inch wide seat with 121-degree reclining back support has 34 inches of space between you and the next row of seats, and provides personal comfort unlike any other economy-class seat.

An 8.4-inch high-resolution LCD wide screen with state-of-the-art audio and video on demand (AVOD) makes channel selection easy and your flight more enjoyable.

- Include inflight meals
- Include carry on bag
- Include checked baggage
- Include seat selection

Note: Type and size of seat and its available features may vary depending on the flight route, time and aircraft.</Text>
              <Text Type="Strapline" LanguageCode="EN">Best-in-class comfort in the air</Text>
              <ImageLocation Type="Agent" ImageWidth="150" ImageHeight="150">https://cdn.travelport.com/koreanair/KE_general_medium_1228.jpg</ImageLocation>
              <ImageLocation Type="Consumer" ImageWidth="1333" ImageHeight="800">https://cdn.travelport.com/koreanair/KE_general_large_45850.jpg</ImageLocation>
            </Brand>
          </FareInfo>
          <BookingInfo BookingCode="Q" CabinClass="Economy" FareInfoRef="11L018cB0BKA0B5tkHAAAA==" SegmentRef="11L018cB0BKAhB5tkHAAAA==" HostTokenRef="11L018cB0BKAqB5tkHAAAA==" />
          <BookingInfo BookingCode="Q" CabinClass="Economy" FareInfoRef="11L018cB0BKA0B5tkHAAAA==" SegmentRef="11L018cB0BKAjB5tkHAAAA==" HostTokenRef="11L018cB0BKAqB5tkHAAAA==" />
          <BookingInfo BookingCode="Q" CabinClass="Economy" FareInfoRef="11L018cB0BKABC5tkHAAAA==" SegmentRef="11L018cB0BKAlB5tkHAAAA==" HostTokenRef="11L018cB0BKArB5tkHAAAA==" />
          <BookingInfo BookingCode="Q" CabinClass="Economy" FareInfoRef="11L018cB0BKABC5tkHAAAA==" SegmentRef="11L018cB0BKAnB5tkHAAAA==" HostTokenRef="11L018cB0BKArB5tkHAAAA==" />
          <TaxInfo Category="IN" Amount="AED10" Key="11L018cB0BKAtB5tkHAAAA==" />
          <TaxInfo Category="K3" Amount="AED130" Key="11L018cB0BKAuB5tkHAAAA==" />
          <TaxInfo Category="WO" Amount="AED20" Key="11L018cB0BKAvB5tkHAAAA==" />
          <TaxInfo Category="BP" Amount="AED80" Key="11L018cB0BKAwB5tkHAAAA==" />
          <TaxInfo Category="CN" Amount="AED50" Key="11L018cB0BKAxB5tkHAAAA==" />
          <TaxInfo Category="YQ" Amount="AED40" Key="11L018cB0BKAyB5tkHAAAA==" />
          <TaxInfo Category="YR" Amount="AED860" Key="11L018cB0BKAzB5tkHAAAA==" />
          <FareCalc>DEL KE X/SEL KE BJS 234.36QEEIC KE X/SEL KE DEL 234.36QEEIC NUC468.72END ROE64.004</FareCalc>
          <PassengerType Code="ADT" BookingTravelerRef="0" />
          <ChangePenalty>
            <Amount>AED260.00</Amount>
          </ChangePenalty>
          <CancelPenalty>
            <Amount>AED260.00</Amount>
          </CancelPenalty>
          <BaggageAllowances>
            <BaggageAllowanceInfo TravelerType="ADT" Origin="DEL" Destination="BJS" Carrier="KE">
              <URLInfo>
                <URL>MYTRIPANDMORE.COM/BAGGAGEDETAILSKE.BAGG</URL>
              </URLInfo>
              <TextInfo>
                <Text>1P</Text>
                <Text>BAGGAGE DISCOUNTS MAY APPLY BASED ON FREQUENT FLYER STATUS/ ONLINE CHECKIN/FORM OF PAYMENT/MILITARY/ETC.</Text>
              </TextInfo>
              <BagDetails ApplicableBags="1stChecked" BasePrice="INR0" ApproximateBasePrice="AED0" TotalPrice="INR0" ApproximateTotalPrice="AED0">
                <BaggageRestriction>
                  <TextInfo>
                    <Text>UPTO50LB/23KG AND UPTO62LI/158LCM</Text>
                  </TextInfo>
                </BaggageRestriction>
              </BagDetails>
              <BagDetails ApplicableBags="2ndChecked" BasePrice="INR6515" ApproximateBasePrice="AED368" TotalPrice="INR6515" ApproximateTotalPrice="AED368">
                <BaggageRestriction>
                  <TextInfo>
                    <Text>UPTO50LB/23KG AND UPTO62LI/158LCM</Text>
                  </TextInfo>
                </BaggageRestriction>
              </BagDetails>
            </BaggageAllowanceInfo>
            <BaggageAllowanceInfo TravelerType="ADT" Origin="BJS" Destination="DEL" Carrier="KE">
              <URLInfo>
                <URL>MYTRIPANDMORE.COM/BAGGAGEDETAILSKE.BAGG</URL>
              </URLInfo>
              <TextInfo>
                <Text>1P</Text>
                <Text>BAGGAGE DISCOUNTS MAY APPLY BASED ON FREQUENT FLYER STATUS/ ONLINE CHECKIN/FORM OF PAYMENT/MILITARY/ETC.</Text>
              </TextInfo>
              <BagDetails ApplicableBags="1stChecked" BasePrice="INR0" ApproximateBasePrice="AED0" TotalPrice="INR0" ApproximateTotalPrice="AED0">
                <BaggageRestriction>
                  <TextInfo>
                    <Text>UPTO50LB/23KG AND UPTO62LI/158LCM</Text>
                  </TextInfo>
                </BaggageRestriction>
              </BagDetails>
              <BagDetails ApplicableBags="2ndChecked" BasePrice="CNY670" ApproximateBasePrice="AED372" TotalPrice="CNY670" ApproximateTotalPrice="AED372">
                <BaggageRestriction>
                  <TextInfo>
                    <Text>UPTO50LB/23KG AND UPTO62LI/158LCM</Text>
                  </TextInfo>
                </BaggageRestriction>
              </BagDetails>
            </BaggageAllowanceInfo>
            <CarryOnAllowanceInfo Origin="DEL" Destination="SEL" Carrier="KE">
              <TextInfo>
                <Text>1P</Text>
              </TextInfo>
              <CarryOnDetails ApplicableCarryOnBags="1" BasePrice="INR0" ApproximateBasePrice="AED0" TotalPrice="INR0" ApproximateTotalPrice="AED0">
                <BaggageRestriction>
                  <TextInfo>
                    <Text>UPTO26LB/12KG AND UPTO45LI/115LCM</Text>
                  </TextInfo>
                </BaggageRestriction>
              </CarryOnDetails>
            </CarryOnAllowanceInfo>
            <CarryOnAllowanceInfo Origin="SEL" Destination="BJS" Carrier="KE">
              <TextInfo>
                <Text>1P</Text>
              </TextInfo>
              <CarryOnDetails ApplicableCarryOnBags="1" BasePrice="KRW0" TotalPrice="KRW0">
                <BaggageRestriction>
                  <TextInfo>
                    <Text>UPTO26LB/12KG AND UPTO45LI/115LCM</Text>
                  </TextInfo>
                </BaggageRestriction>
              </CarryOnDetails>
            </CarryOnAllowanceInfo>
            <CarryOnAllowanceInfo Origin="BJS" Destination="SEL" Carrier="KE">
              <TextInfo>
                <Text>1P</Text>
              </TextInfo>
              <CarryOnDetails ApplicableCarryOnBags="1" BasePrice="CNY0" ApproximateBasePrice="AED0" TotalPrice="CNY0" ApproximateTotalPrice="AED0">
                <BaggageRestriction>
                  <TextInfo>
                    <Text>UPTO26LB/12KG AND UPTO45LI/115LCM</Text>
                  </TextInfo>
                </BaggageRestriction>
              </CarryOnDetails>
            </CarryOnAllowanceInfo>
            <CarryOnAllowanceInfo Origin="SEL" Destination="DEL" Carrier="KE">
              <TextInfo>
                <Text>1P</Text>
              </TextInfo>
              <CarryOnDetails ApplicableCarryOnBags="1" BasePrice="KRW0" TotalPrice="KRW0">
                <BaggageRestriction>
                  <TextInfo>
                    <Text>UPTO26LB/12KG AND UPTO45LI/115LCM</Text>
                  </TextInfo>
                </BaggageRestriction>
              </CarryOnDetails>
            </CarryOnAllowanceInfo>
          </BaggageAllowances>
        </AirPricingInfo>
        <HostToken xmlns="http://www.travelport.com/schema/common_v39_0" Key="11L018cB0BKAqB5tkHAAAA==">GFB10101ADT00  01QEEIC                                 0200010002#GFB200010101NADTV3008IN3300200001994Z#</HostToken>
        <HostToken xmlns="http://www.travelport.com/schema/common_v39_0" Key="11L018cB0BKArB5tkHAAAA==">GFB10101ADT00  02QEEIC                                 0200030004#GFB200010102NADTV3008IN3300200001994Z#</HostToken>
      </AirPricingSolution>
      <ActionStatus ProviderCode="1G" TicketDate="T*" Type="ACTIVE" QueueCategory="01" xmlns="http://www.travelport.com/schema/common_v39_0"></ActionStatus>
      <AirPricingTicketingModifiers>
        <AirPricingInfoRef Key="11L018cB0BKAsB5tkHAAAA==" />
        <TicketingModifiers>
          <Commission Level="Fare" Type="PercentBase" Percentage="7" />
        </TicketingModifiers>
      </AirPricingTicketingModifiers>
    </univ:AirCreateReservationReq>
  </s:Body>
</s:Envelope>`

Which was recommended by [travel-port](https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Air_Ticketing/Ticketing_Modifie
rs.htm?Highlight=commission) support team 

But am getting the **response** as

`<SOAP:Fault xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <faultcode>Server.Data</faultcode>
  <faultstring>Error unmarshalling message body: Expected "{http://www.travelport.com/schema/air_v39_0}TicketingModifiers" end tag, found "{http://www.travelport.com/schema/air_v39_0}Commission" start tag (line 219, col 71, in UTF-8)</faultstring>
  <detail>
    <common_v39_0:ErrorInfo xmlns:common_v39_0="http://www.travelport.com/schema/common_v39_0">
      <common_v39_0:Code>1005</common_v39_0:Code>
      <common_v39_0:Service>WEBSVC</common_v39_0:Service>
      <common_v39_0:Type>Data</common_v39_0:Type>
      <common_v39_0:Description>Unable to parse XML stream</common_v39_0:Description>
      <common_v39_0:TransactionId>4EF378CD0A07425AF05B8639D5D59BDD</common_v39_0:TransactionId>
      <common_v39_0:TraceId>cc1d8ff8d4ecf0822665000b486b233c</common_v39_0:TraceId>
    </common_v39_0:ErrorInfo>
  </detail>
</SOAP:Fault>`

Please let me know where am making mistake.

Thanks in Advance

**Comment by vivekjyotipramanik** [comment]
Hi  sawood,

The commission is part of ticketingModifiers in AirTicketReq and you are adding this is in AirCreateReservationReq. Could you please try with AirTicketingReq with the commission details. Also, If you are using preProduction credentials, Please create an ORS ticket/MyTravelport ticket and an API Analyst will assist you regarding this. Thanks.

**Comment by sawood** [comment]
Hi Vivek

Thanks for your quick response.

I tried with AirTicketingReq with the commission details

`<soapenv:Envelope
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:com="http://www.travelport.com/schema/common_v39_0"
 xmlns:univ="http://www.travelport.com/schema/universal_v39_0">
 <soapenv:Header/>
 <soapenv:Body>
  <air:AirTicketingReq BulkTicket="false" ReturnInfoOnFail="true" TargetBranch="P3076226"
   xmlns:air="http://www.travelport.com/schema/air_v39_0">
   <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
   <air:AirReservationLocatorCode>Y6WQAK</air:AirReservationLocatorCode>
   <air:AirTicketingModifiers>
    <com:Commission Level="Fare" Type="PercentBase" Percentage="7" />
   </air:AirTicketingModifiers>
  </air:AirTicketingReq>
 </soapenv:Body>
</soapenv:Envelope>`

But I got the **response** as

`<air:AirTicketingRsp TransactionId="5298AFEB0A0742644F8D9D1F72039FEF" ResponseTime="1095" xmlns:air="http://www.travelport.com/schema/air_v39_0" xmlns:common_v39_0="http://www.travelport.com/schema/common_v39_0">
  <air:TicketFailureInfo Code="12008" Message="Host error during ticket issue. ELECTRONIC TICKET NOT ISSUED VENDOR LOCATOR REQUIRED FOR KE" BookingTravelerRef="dBE018gB0BKAKouGAJAAAA==">
    <air:AirPricingInfoRef Key="rVpr18BAAA/BnVaxCJAAAA==" />
    <common_v39_0:Name Prefix="Mr" First="Amaresh" Last="AmareshPanda" />
  </air:TicketFailureInfo>
</air:AirTicketingRsp>`

Can you please let me know what is the issue.

Thanks

**Comment by sawood** [comment]
I think the above ticketing has problem from supplier. when i tried with different airline it was working and in ticketing response, i can see the commission tag with commission details.Hope it is the proper method and the commission is paid back.

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi  sawood,

Regarding commission related question, it would be great if you can create an ORS Ticket/MyTravelport ticket and An API Analyst will assist you regarding it. Thanks.

**Comment by sawood** [comment]
Hi Vivek

I have already raise a incident with Travel-port,am waiting for there response.
anyways Thanks a lot vivek for your help.
