### ISSUE TITLE
AirTicketReq request separate for each passengers

### ISSUE THREAD

**Issue by stepan-ap** [Travelport/travelport-uapi-tutorial-php#105]
1G(galileo) please show XML samples AirTicketReq for separate for each passengers.

**Comment by vivekjyotipramanik** [comment]
As this is a duplicate of another issue can we close this issue. Regarding your question, Could you please raise a support ticket in MyTravelport and an API analyst will assist you. Thanks.

**Comment by stepan-ap** [comment]
ok, thanks
