### ISSUE TITLE
BOOKING CLASS/PREFERENCE NOT AVAIL CHECK AVAILABILITY 

### ISSUE THREAD

**Issue by sivaneshc** [Travelport/travelport-uapi-tutorial-php#109]
Hi,

Getting the below error in "AirPriceResponse"
"BOOKING CLASS/PREFERENCE NOT AVAIL CHECK AVAILABILITY "

How do filter it in "LowFareSearchReq". Please suggest if there is any option to clear this error.

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

Could you please try with a different Origin/Destination and dates at least 2 months from today's date. In PreProduction, as test data is limited, some of the routes might not have availability. please let us know how it goes. Thanks.

**Comment by sivaneshc** [comment]
Hi vivekjyotipramanik,

This happens in production

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

Could you please create a MyTravelport ticket as this is occurring in Production. Thanks.
