### ISSUE TITLE
Provider 1G and ACH

### ISSUE THREAD

**Issue by sivaneshc** [Travelport/travelport-uapi-tutorial-php#112]
Hi,
I need to know whether 1G and ACH has same AirPriceReq or different?
If ACH has different AirPriceReq, then i also need to know whether it differs each Airline.

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

The AirPriceReq structure is same for all Airlines and all providers. Please find below the link with all the details. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Air_Pricing/Air_Pricing.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAir%2520Pricing%7C_____0

**Comment by sivaneshc** [comment]
Hi vivekjyotipramanik,

Thanks for the input.
I am getting error message when using ACH Provider in AirPriceRes "Required attribute in the request is missing-/OTA_AirPriceRQ/TravelerInfoSummary/PriceRequestInformation@CurrencyCode"

Please find the attatched request and response

[AirPriceReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/1654964/AirPriceReq.txt)
[AirPriceRes.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/1654965/AirPriceRes.txt)

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

Could you please try with the below request. Please let us know how it goes. Thanks.

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header />
    <soapenv:Body>
        <AirPriceReq xmlns="http://www.travelport.com/schema/air_v33_0" AuthorizedBy="Travelport" TargetBranch="P7027641">
            <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v33_0" OriginApplication="uAPI" />
            <AirItinerary>
                <AirSegment Key="AGtIcD4R2BKAjT92IAAAAA==" AvailabilitySource="" AvailabilityDisplayType="" Group="0" Carrier="6E" FlightNumber="758" Origin="AMD" Destination="BLR" DepartureTime="2018-02-02T12:35:00.000+05:30" ArrivalTime="2018-02-02T14:45:00.000+05:30" FlightTime="130" Distance="0" ProviderCode="ACH" ClassOfService="X">
                    <air:Connection xmlns:air="http://www.travelport.com/schema/air_v33_0" />
                </AirSegment>
                <AirSegment Key="AGtIcD4R2BKAhT92IAAAAA==" AvailabilitySource="" AvailabilityDisplayType="" Group="0" Carrier="6E" FlightNumber="73" Origin="BLR" Destination="SIN" DepartureTime="2018-02-02T21:20:00.000+05:30" ArrivalTime="2018-02-03T04:30:00.000+08:00" FlightTime="280" Distance="0" ProviderCode="ACH" ClassOfService="X"></AirSegment>
            </AirItinerary>
            <AirPricingModifiers>
                <BrandModifiers ModifierType="FareFamilyDisplay" />
            </AirPricingModifiers>
            <SearchPassenger xmlns="http://www.travelport.com/schema/common_v33_0" Code="ADT" BookingTravelerRef="TzQ2MDhENGlLSGNURWVqOA==1" />
            <AirPricingCommand>
                <AirSegmentPricingModifiers FareBasisCode="L0IP" AirSegmentRef="AGtIcD4R2BKAjT92IAAAAA==">
                    <PermittedBookingCodes>
                        <BookingCode Code="X" />
                    </PermittedBookingCodes>
                </AirSegmentPricingModifiers>
                <AirSegmentPricingModifiers FareBasisCode="Q0INT" AirSegmentRef="AGtIcD4R2BKAhT92IAAAAA==">
                    <PermittedBookingCodes>
                        <BookingCode Code="X" />
                    </PermittedBookingCodes>
                </AirSegmentPricingModifiers>
            </AirPricingCommand>
            <FormOfPayment xmlns="http://www.travelport.com/schema/common_v33_0" Type="Credit" />
        </AirPriceReq>
    </soapenv:Body>
</soapenv:Envelope>
```

**Comment by sivaneshc** [comment]
Hi vivekjyotipramanik,

Still getting the same error " **Required attribute in the request is missing-/OTA_AirPriceRQ/TravelerInfoSummary/PriceRequestInformation@CurrencyCode**"

Please find the attached request and response.
[AirPriceRes.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/1658515/AirPriceRes.txt)
[AirPriceReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/1658516/AirPriceReq.txt)
[LowFareSearchRes.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/1658517/LowFareSearchRes.txt)
[LowFareSearchReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/1658518/LowFareSearchReq.txt)





Thank you

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

Could you please create a MyTravelport ticket for this issue so that an API Analyst can check the provisioning. Thanks.

**Comment by sivaneshc** [comment]
Ok. Thank you

**Comment by varunrana87** [comment]
Hi Guys, Did you get this issue sorted?

if yes, can you please also let me know, cause i'm getting this same error with Price request.

Here's my Price request - 

 <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ses="http://www.travelport.com/soa/common/security/SessionContext_v1" xmlns:air="http://www.travelport.com/schema/air_v44_0" xmlns:com="http://www.travelport.com/schema/common_v44_0">
   <soapenv:Header></soapenv:Header>
   <soapenv:Body>
     <air:AirPriceReq AuthorizedBy="user" TargetBranch="P7088812" CheckOBFees="All">
       <com:BillingPointOfSaleInfo OriginApplication="UAPI"></com:BillingPointOfSaleInfo>
       <air:AirItinerary>
         <air:AirSegment Key="H6H/ih3R2BKAvLHHEAAAAA==" Group="0" Carrier="6E" FlightNumber="42" Origin="SIN" Destination="CCU" DepartureTime="2019-02-10T02:45:00.000+08:00" ArrivalTime="2019-02-10T04:30:00.000+05:30" FlightTime="255" ProviderCode="ACH" SupplierCode="6E" ClassOfService="N" Equipment="320" ChangeOfPlane="false">
           <air:AirAvailInfo>
             <air:BookingCodeInfo CabinClass="Economy" BookingCounts="43"></air:BookingCodeInfo>
           </air:AirAvailInfo>
           <air:FlightDetails Key="H6H/ih3R2BKAwLHHEAAAAA==" Origin="SIN" Destination="CCU" DepartureTime="2019-02-10T02:45:00.000+08:00" ArrivalTime="2019-02-10T04:30:00.000+05:30" FlightTime="255" TravelTime="255" Equipment="320" OriginTerminal="2"></air:FlightDetails>
           <air:Connection SegmentIndex="2"></air:Connection>
         </air:AirSegment>
         <air:AirSegment Key="H6H/ih3R2BKAxLHHEAAAAA==" Group="0" Carrier="6E" FlightNumber="5324" Origin="CCU" Destination="DEL" DepartureTime="2019-02-10T07:00:00.000+05:30" ArrivalTime="2019-02-10T09:30:00.000+05:30" FlightTime="150" ProviderCode="ACH" SupplierCode="6E" ClassOfService="X" Equipment="320" ChangeOfPlane="false">
           <air:AirAvailInfo>
             <air:BookingCodeInfo CabinClass="Economy" BookingCounts="43"></air:BookingCodeInfo>
           </air:AirAvailInfo>
           <air:FlightDetails Key="H6H/ih3R2BKAyLHHEAAAAA==" Origin="CCU" Destination="DEL" DepartureTime="2019-02-10T07:00:00.000+05:30" ArrivalTime="2019-02-10T09:30:00.000+05:30" FlightTime="150" TravelTime="150" Equipment="320" OriginTerminal="1" DestinationTerminal="1"></air:FlightDetails>
           <air:Connection SegmentIndex="2"></air:Connection>
         </air:AirSegment>
         <air:AirSegment Key="H6H/ih3R2BKAzLHHEAAAAA==" Group="1" Carrier="6E" FlightNumber="2519" Origin="DEL" Destination="MAA" DepartureTime="2019-03-10T21:45:00.000+05:30" ArrivalTime="2019-03-11T00:40:00.000+05:30" FlightTime="175" ProviderCode="ACH" SupplierCode="6E" ClassOfService="N" Equipment="320" ChangeOfPlane="false">
           <air:AirAvailInfo>
             <air:BookingCodeInfo CabinClass="Economy" BookingCounts="4"></air:BookingCodeInfo>
           </air:AirAvailInfo>
           <air:FlightDetails Key="H6H/ih3R2BKA0LHHEAAAAA==" Origin="DEL" Destination="MAA" DepartureTime="2019-03-10T21:45:00.000+05:30" ArrivalTime="2019-03-11T00:40:00.000+05:30" FlightTime="175" TravelTime="175" Equipment="320" OriginTerminal="2" DestinationTerminal="1"></air:FlightDetails>
           <air:Connection SegmentIndex="2"></air:Connection>
         </air:AirSegment>
         <air:AirSegment Key="H6H/ih3R2BKA1LHHEAAAAA==" Group="1" Carrier="6E" FlightNumber="51" Origin="MAA" Destination="SIN" DepartureTime="2019-03-11T05:15:00.000+05:30" ArrivalTime="2019-03-11T12:10:00.000+08:00" FlightTime="265" ProviderCode="ACH" SupplierCode="6E" ClassOfService="N" Equipment="320" ChangeOfPlane="false">
           <air:AirAvailInfo>
             <air:BookingCodeInfo CabinClass="Economy" BookingCounts="4"></air:BookingCodeInfo>
           </air:AirAvailInfo>
           <air:FlightDetails Key="H6H/ih3R2BKA2LHHEAAAAA==" Origin="MAA" Destination="SIN" DepartureTime="2019-03-11T05:15:00.000+05:30" ArrivalTime="2019-03-11T12:10:00.000+08:00" FlightTime="265" TravelTime="265" Equipment="320" OriginTerminal="4" DestinationTerminal="2"></air:FlightDetails>
           <air:Connection SegmentIndex="2"></air:Connection>
         </air:AirSegment>
       </air:AirItinerary>
       <air:AirPricingModifiers CurrencyType="INR" FaresIndicator="AllFares" ETicketability="Yes"></air:AirPricingModifiers>
       <com:SearchPassenger Code="ADT" BookingTravelerRef="0"></com:SearchPassenger>
       <air:AirPricingCommand>
         <air:AirSegmentPricingModifiers AirSegmentRef="H6H/ih3R2BKAvLHHEAAAAA==" FareBasisCode="R0INTRT"></air:AirSegmentPricingModifiers>
         <air:AirSegmentPricingModifiers AirSegmentRef="H6H/ih3R2BKAxLHHEAAAAA==" FareBasisCode="P015AP"></air:AirSegmentPricingModifiers>
         <air:AirSegmentPricingModifiers AirSegmentRef="H6H/ih3R2BKAzLHHEAAAAA==" FareBasisCode="Q0IPRT"></air:AirSegmentPricingModifiers>
         <air:AirSegmentPricingModifiers AirSegmentRef="H6H/ih3R2BKA1LHHEAAAAA==" FareBasisCode="R0INTRT"></air:AirSegmentPricingModifiers>
       </air:AirPricingCommand>
       <air:PCC>
         <com:PointOfSale ProviderCode="1G" PseudoCityCode="63F1"></com:PointOfSale>
       </air:PCC>
     </air:AirPriceReq>
   </soapenv:Body>


Any Help Appreciated! Thanks

**Comment by NirandaG** [comment]
Hi,
Your credentials does not seem to be Sandbox.
Please open a ticket on MyTravelport https://my.travelport.com and some one would assist you.
Rgds,
Niranda
