### ISSUE TITLE
AvailabilitySearchReq roundtrip with connection ?

### ISSUE THREAD

**Issue by feyzprod** [Travelport/travelport-uapi-tutorial-php#113]
We are using GWS classic API to get/book flight and we would like to start booking ancillaries with uAPI.

We already know the flight that we are going to book

Let say 
Outbound CDG -> WAW
------ CDG -> MUC
------ MUC -> WAW
Inbound WAW -> CDG
----- WAW -> MUC
----- MUC -> CDG

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
				        <soapenv:Header/>
				        <soapenv:Body>
			                <air:AvailabilitySearchReq xmlns:air="http://www.travelport.com/schema/air_v42_0" AuthorizedBy="user" TargetBranch="my_branch" TraceId="trace">
			                <com:BillingPointOfSaleInfo xmlns:com="http://www.travelport.com/schema/common_v42_0" OriginApplication="UAPI"/><air:SearchAirLeg>
	                                <air:SearchOrigin>
	                                	<com:Airport xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="CDG"/>
	                                </air:SearchOrigin>
	                                <air:SearchDestination>
	                                	<com:Airport xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="WAW"/>
	                                </air:SearchDestination>
	                                <air:SearchDepTime PreferredTime="2018-03-12"/>
		                        </air:SearchAirLeg>
<air:SearchAirLeg>
	                                <air:SearchOrigin>
	                                	<com:Airport xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="WAW"/>
	                                </air:SearchOrigin>
	                                <air:SearchDestination>
	                                	<com:Airport xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="CDG"/>
	                                </air:SearchDestination>
	                                <air:SearchDepTime PreferredTime="2018-03-20"/>
		                        </air:SearchAirLeg>
<air:AirSearchModifiers>
	                                <air:PreferredProviders>
	                                	<com:Provider xmlns:com="http://www.travelport.com/schema/common_v42_0" Code="1V"/>
	                                </air:PreferredProviders>
		                        </air:AirSearchModifiers>
			                </air:AvailabilitySearchReq>
				        </soapenv:Body>
					</soapenv:Envelope>

I almost get no results and I don't see my connection MUC -> WAW

Is there a param to get more results with all connections ?

or should I call AvailabilitySearchReq for all my connections
CDG -> MUC
MUC -> WAW
WAW -> MUC
MUC -> CDG

**Comment by vivekjyotipramanik** [comment]
Hi feyzprod,

Using AirAvailability in UAPI, it will always try to provide results with minimum connections and actually using MaxStops and MaxConnections parameters we can modify the search. To specifically, get each of the connections, we have to add SearchAirLeg for each of the origin and destination cities. Please find below the link with all the details. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Air_Availability/Air_Availability_by_Connecting_Cities.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAir%2520Availability%7CAir%2520Availability%2520Modifiers%7C_____6

**Comment by feyzprod** [comment]
Do you have an xml example of how to add Connecting Cities ? 
I get this error message : Error unmarshalling message body: Expected "{http://www.travelport.com/schema/air_v34_0}PermittedConnectionPoints" end tag, found "{http://www.travelport.com/schema/air_v34_0}ConnectionPoint" start tag (line 16, col 32, in UTF-8)


<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
        <soapenv:Header/>
        <soapenv:Body>
                <air:AvailabilitySearchReq xmlns:air="http://www.travelport.com/schema/air_v34_0" AuthorizedBy="user" TargetBranch="*******" TraceId="trace">
                <com:BillingPointOfSaleInfo xmlns:com="http://www.travelport.com/schema/common_v34_0" OriginApplication="UAPI"/>
                        <air:SearchAirLeg>
                                <air:SearchOrigin>
                                        <com:Airport xmlns:com="http://www.travelport.com/schema/common_v34_0" Code="CDG"/>
                                </air:SearchOrigin>
                                <air:SearchDestination>
                                        <com:Airport xmlns:com="http://www.travelport.com/schema/common_v34_0" Code="WAW"/>
                                </air:SearchDestination>
                                <air:SearchDepTime PreferredTime="2018-03-13"/>
                                <air:AirLegModifiers>
									<air:PermittedConnectionPoints>
										<air:ConnectionPoint>
											<com:Airport xmlns:com="http://www.travelport.com/schema/common_v34_0" Code="MUC"/>
										</air:ConnectionPoint>
									</air:PermittedConnectionPoints>
								</air:AirLegModifiers>
                        </air:SearchAirLeg>
                        <air:SearchAirLeg>
                                <air:SearchOrigin>
                                        <com:Airport xmlns:com="http://www.travelport.com/schema/common_v34_0" Code="WAW"/>
                                </air:SearchOrigin>
                                <air:SearchDestination>
                                        <com:Airport xmlns:com="http://www.travelport.com/schema/common_v34_0" Code="CDG"/>
                                </air:SearchDestination>
                                <air:SearchDepTime PreferredTime="2018-03-20"/>
                                <air:AirLegModifiers>
									<air:PermittedConnectionPoints>
										<air:ConnectionPoint>
											<com:Airport xmlns:com="http://www.travelport.com/schema/common_v34_0" Code="MUC"/>
										</air:ConnectionPoint>
									</air:PermittedConnectionPoints>
								</air:AirLegModifiers>
                        </air:SearchAirLeg>
                        <air:AirSearchModifiers>
                                <air:PreferredProviders>
                                        <com:Provider xmlns:com="http://www.travelport.com/schema/common_v34_0" Code="1V"/>
                                </air:PreferredProviders>
                        </air:AirSearchModifiers>
                </air:AvailabilitySearchReq>
        </soapenv:Body>
</soapenv:Envelope>

**Comment by vivekjyotipramanik** [comment]
Hi feyzprod,

Please find below the updated request. Just to add, even if we use PermittedConnectionPoints, still it does not guarantee that it will return flights with MUC as connecting point. To confirm that you always get MUC, Please use MUC as a AirSearchLeg. Please find below both the examples. Thanks.

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq AuthorizedBy="user" TargetBranch="*******" TraceId="trace" xmlns:com="http://www.travelport.com/schema/common_v42_0" xmlns:air="http://www.travelport.com/schema/air_v42_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="CDG"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="WAW"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2018-03-13"/>
            <air:AirLegModifiers>
               <air:PermittedConnectionPoints>
                  <com:ConnectionPoint>
                     <com:Airport Code="MUC"/>
                  </com:ConnectionPoint>
               </air:PermittedConnectionPoints>
            </air:AirLegModifiers>
         </air:SearchAirLeg>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="WAW"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="CDG"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2018-03-20"/>
            <air:AirLegModifiers>
               <air:PermittedConnectionPoints>
                  <com:ConnectionPoint>
                     <com:Airport Code="MUC"/>
                  </com:ConnectionPoint>
               </air:PermittedConnectionPoints>
            </air:AirLegModifiers>
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="1V"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
```


```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq AuthorizedBy="user" TargetBranch="*******" TraceId="trace" xmlns:com="http://www.travelport.com/schema/common_v42_0" xmlns:air="http://www.travelport.com/schema/air_v42_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="CDG"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="MUC"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2018-03-13"/>
         </air:SearchAirLeg>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="MUC"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="WAW"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2018-03-13"/>
         </air:SearchAirLeg>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="WAW"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="MUC"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2018-03-20"/>
         </air:SearchAirLeg>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="MUC"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="CDG"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2018-03-20"/>
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="1V"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by feyzprod** [comment]
Thanks vivekjyotipramanik

About the first example, how do I know if I need to use :air or :com on a tag ?

The problem with your second example is, it's not considered as a normal Round Trip

I will get multiple Group 0,1,2...

That can cause problem for pricing ?

**Comment by vivekjyotipramanik** [comment]
Hi feyzprod,

The tag can be checked using SOAP UI tool or from the schema document itself. Please find below the link with the details.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Getting_Started/Getting_Started.htm%3FTocPath%3DGetting%2520Started%7C_____0

Yes, the 2nd example, will not use groups as you are looking for, but there is no way to guarantee that a Flight will use Connecting city. Please raise a MyTravelport ticket and an API Analyst can research more on this. Thanks.

**Comment by feyzprod** [comment]
Can we put multiple connections point ?

My journey CDG -> YUL
CDG -> LHR
LHR -> JFK
JFK -> YUL

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
				   <soapenv:Header/>
				   <soapenv:Body>
				      <air:AvailabilitySearchReq AuthorizedBy="user" TargetBranch="******" TraceId="trace" xmlns:com="http://www.travelport.com/schema/common_v42_0" xmlns:air="http://www.travelport.com/schema/air_v42_0">
				         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/><air:SearchAirLeg>
					            <air:SearchOrigin>
					               <com:Airport Code="YUL"/>
					            </air:SearchOrigin>
					            <air:SearchDestination>
					               <com:Airport Code="CDG"/>
					            </air:SearchDestination>
					            <air:SearchDepTime PreferredTime="2018-04-17"/><air:AirLegModifiers><air:PermittedConnectionPoints><com:ConnectionPoint>
										<com:Airport Code="AMS"/>
									</com:ConnectionPoint></air:PermittedConnectionPoints><air:PermittedCarriers><com:Carrier Code="DL" /></air:PermittedCarriers></air:AirLegModifiers></air:SearchAirLeg><air:SearchAirLeg>
					            <air:SearchOrigin>
					               <com:Airport Code="CDG"/>
					            </air:SearchOrigin>
					            <air:SearchDestination>
					               <com:Airport Code="YUL"/>
					            </air:SearchDestination>
					            <air:SearchDepTime PreferredTime="2018-04-24"/><air:AirLegModifiers><air:PermittedConnectionPoints><com:ConnectionPoint>
										<com:Airport Code="LHR"/>
									</com:ConnectionPoint><com:ConnectionPoint>
										<com:Airport Code="JFK"/>
									</com:ConnectionPoint></air:PermittedConnectionPoints><air:PermittedCarriers><com:Carrier Code="AF" /></air:PermittedCarriers></air:AirLegModifiers></air:SearchAirLeg><air:AirSearchModifiers>
				            <air:PreferredProviders>
				               <com:Provider Code="1V"/>
				            </air:PreferredProviders>
				         </air:AirSearchModifiers>
				      </air:AvailabilitySearchReq>
				   </soapenv:Body>
				</soapenv:Envelope>`

I don't see any LHR connections, but in my request if I remove the connection point JFK, I will now get LHR result.

**Comment by vivekjyotipramanik** [comment]
Hi feyzprod,

Upto 3 connectionPoints per request are allowed in Galileo/Apollo. Please find below the link with all the details about connectionPoints. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Low_Fare_Shopping/Low_Fare_Shopping_by_Connecting_Cities.htm#Preferred
