### ISSUE TITLE
AirPriceReq Multiple FareBasisCode

### ISSUE THREAD

**Issue by feyzprod** [Travelport/travelport-uapi-tutorial-php#116]
Can we send multiple FareBasisCode by segment ?

Sometime, when I have multiple passengers (ADT,CHD,INF) in the same request, they each have their own FareBasisCode.

Psg 1 ADT FareBasisCode = WSPEU6
Psg 2 CHD FareBasisCode = WSPEU6CH
Psg 3 INF FareBasisCode = WSPEU6IN

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
						<soapenv:Header/>
						        <soapenv:Body>
						                <air:AirPriceReq xmlns:air="http://www.travelport.com/schema/air_v42_0" AuthorizedBy="user" TargetBranch="******" TraceId="trace">
						                        <com:BillingPointOfSaleInfo xmlns:com="http://www.travelport.com/schema/common_v42_0" OriginApplication="UAPI"/><air:AirItinerary><air:AirSegment ArrivalTime="2018-05-15T15:25:00.000+02:00" AvailabilitySource="S"  Carrier="AZ" ChangeOfPlane="false" DepartureTime="2018-05-15T13:20:00.000+02:00" Destination="FCO" ETicketability="Yes" Equipment="320" FlightNumber="333" FlightTime="125" Group="0" Key="d07cAGBAAA/B3MERIGAAAA==" OptionalServicesIndicator="false" Origin="CDG" ParticipantLevel="Secure Sell" ProviderCode="1V" ClassOfService="W"><air:AirAvailInfo ProviderCode="1V"/><air:Connection/></air:AirSegment><air:AirSegment ArrivalTime="2018-05-16T11:05:00.000+02:00" AvailabilitySource="S"  Carrier="AZ" ChangeOfPlane="false" DepartureTime="2018-05-16T08:45:00.000+02:00" Destination="WAW" ETicketability="Yes" Equipment="32S" FlightNumber="490" FlightTime="140" Group="0" Key="d07cAGBAAA/BPNERIGAAAA==" OptionalServicesIndicator="false" Origin="FCO" ParticipantLevel="Secure Sell" ProviderCode="1V" ClassOfService="W"><air:AirAvailInfo ProviderCode="1V"/></air:AirSegment><air:AirSegment ArrivalTime="2018-05-22T14:15:00.000+02:00" AvailabilitySource="S"  Carrier="AZ" ChangeOfPlane="false" DepartureTime="2018-05-22T11:55:00.000+02:00" Destination="FCO" ETicketability="Yes" Equipment="32S" FlightNumber="491" FlightTime="140" Group="1" Key="d07cAGBAAA/BrNERIGAAAA==" OptionalServicesIndicator="false" Origin="WAW" ParticipantLevel="Secure Sell" ProviderCode="1V" ClassOfService="O"><air:AirAvailInfo ProviderCode="1V"/><air:Connection/></air:AirSegment><air:AirSegment ArrivalTime="2018-05-22T17:35:00.000+02:00" AvailabilitySource="S"  Carrier="AZ" ChangeOfPlane="false" DepartureTime="2018-05-22T15:25:00.000+02:00" Destination="CDG" ETicketability="Yes" Equipment="321" FlightNumber="324" FlightTime="130" Group="1" Key="d07cAGBAAA/BTNERIGAAAA==" OptionalServicesIndicator="false" Origin="FCO" ParticipantLevel="Secure Sell" ProviderCode="1V" ClassOfService="O"><air:AirAvailInfo ProviderCode="1V"/></air:AirSegment></air:AirItinerary><air:AirPricingModifiers InventoryRequestType="DirectAccess">
						 	<air:BrandModifiers ModifierType="FareFamilyDisplay" />
						 </air:AirPricingModifiers><com:SearchPassenger xmlns:com="http://www.travelport.com/schema/common_v42_0" BookingTravelerRef="0" Code="ADT"/><com:SearchPassenger xmlns:com="http://www.travelport.com/schema/common_v42_0" BookingTravelerRef="1" Code="ADT"/><com:SearchPassenger xmlns:com="http://www.travelport.com/schema/common_v42_0" BookingTravelerRef="2" Code="CHD"/><com:SearchPassenger xmlns:com="http://www.travelport.com/schema/common_v42_0" BookingTravelerRef="3" Code="INF"/><air:AirPricingCommand><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/B3MERIGAAAA==" FareBasisCode="WSPEU6"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="W" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/B3MERIGAAAA==" FareBasisCode="WSPEU6CH"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="W" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/B3MERIGAAAA==" FareBasisCode="WSPEU6IN"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="W" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BPNERIGAAAA==" FareBasisCode="WSPEU6"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="W" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BPNERIGAAAA==" FareBasisCode="WSPEU6CH"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="W" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BPNERIGAAAA==" FareBasisCode="WSPEU6IN"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="W" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BrNERIGAAAA==" FareBasisCode="OSPEU6"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="O" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BrNERIGAAAA==" FareBasisCode="OSPEU6CH"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="O" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BrNERIGAAAA==" FareBasisCode="OSPEU6IN"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="O" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BTNERIGAAAA==" FareBasisCode="OSPEU6"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="O" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BTNERIGAAAA==" FareBasisCode="OSPEU6CH"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="O" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers><air:AirSegmentPricingModifiers AirSegmentRef="d07cAGBAAA/BTNERIGAAAA==" FareBasisCode="OSPEU6IN"><air:PermittedBookingCodes>
						      	        <air:BookingCode Code="O" />
							      </air:PermittedBookingCodes></air:AirSegmentPricingModifiers></air:AirPricingCommand>    </air:AirPriceReq>
						   </soapenv:Body>
						</soapenv:Envelope>`

In AirPriceReq response I will only get fare for WSPEU6 not for WSPEU6CH,WSPEU6IN

**Comment by vivekjyotipramanik** [comment]
Hi feyzprod,

Ideally an INF passenger should followed by an ADT passenger. I believe as INF has been added at the end, the pricing is not working. Please find below the link with Passenger Type best practices. Could you please check if there is any error showing up in the airpricingrsp. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Shared_Air_Topics/Passenger_Type_Codes.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAssociated%2520Topics%7C_____21
