### ISSUE TITLE
visa information in the response

### ISSUE THREAD

**Issue by nisassa** [Travelport/travelport-uapi-tutorial-php#119]
Hi Guys,

I'd want to know if is there a way to get visa information using the uAPI.
I want in our system when we set up the user's nationality to make an request to the API, to figure out if there are any visa requirements for the nationality of the customer.

Thanks!

**Comment by NirandaG** [comment]
Hi nisassa,
There is no service in uAPI to support this functionality.
You might need to use external sources to accommodate this.
Rgds,
Niranda

**Comment by nisassa** [comment]
Thanks a lot.
Could you recommend any APIs that could be used to achieve this goal?

Best Regards,
Dumitru
