### ISSUE TITLE
Get Airplane/Carrier Full Name

### ISSUE THREAD

**Issue by marcadde23** [Travelport/travelport-uapi-tutorial-php#122]
Hello everyone!
After sending my request for retrieving flights available, I still missing some useful info, such as carrier name, equipment details. see the picture below:

![flight-details](https://user-images.githubusercontent.com/35252916/37564129-7dae4ab6-2aa0-11e8-857c-1679d912031e.jpg)

As you see the result, it writes BA, 320. Which is not what I want.
I want to display **British Airways** instead of BA
Also **Airbus Industrie A320-100/200** instead of 320 as shown in the demo page

![flight-details-correct](https://user-images.githubusercontent.com/35252916/37564161-55ca44fe-2aa1-11e8-9e0c-808a584781da.jpg)

How I can do that?

**Comment by vivekjyotipramanik** [comment]
Hi marcadde23,

Please find below the static file data which can be stored in your application and you can get the data about full Airline name. Also, you can use ReferenceDataRretrieveReq to get full name about the Airline. Please find below the link with the details.

https://developer.travelport.com/euf/assets/developer-network/downloads/ReferenceData.zip

Open the RAIR file and it has the data.


https://support.travelport.com/webhelp/uapi/uAPI.htm#Getting_Started/Design_Considerations/Reference_Data.htm%3FTocPath%3DGetting%2520Started%7CUniversal%2520API%2520Overview%7CDesign%2520Considerations%7C_____5

**Comment by marcadde23** [comment]
It worked, thank you.
