### ISSUE TITLE
Booking Error

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#124]
Hello All
  Greetings of the day!!

when we make booking, we get following error

Uncaught Service Exception cause:com.cendant.tds.soa.framework.ServiceException: Exception ReturnedERR: AGENT ID - GALILEOWith the Dynamic GTID list of:AA1C80 

kindly resolve it please

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

Please share the username and targetbranch you are using. Thanks.

**Comment by Alex0084** [comment]
Hello Vivek,
   Greetings of the Day!!

here is username and target branch :

Username : API/uAPI8767522130-2516f529
Target Branch : P3167909

Please check and resolve it please

Thanks

**Comment by NirandaG** [comment]
Hi,
This appears to be a Production credentials. You need to open a MyTravelport ticket to resolve this.
Rgds,
Niranda
