### ISSUE TITLE
Which one is correct workflow for worldspan (1P)

### ISSUE THREAD

**Issue by m-swami** [Travelport/travelport-uapi-tutorial-php#128]
Hi,

I am using worldspan workflow and according to this url https://support.travelport.com/webhelp/uapi/uAPI.htm i am using booking sessions. All i need to know is that is it necessary to use booking sessions for certification process??

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi m-swami,

I don't think BookingSessions is necessary for certification. Please create a MyTravelport ticket regarding this and an API Analyst will help you with this. Thanks.

**Comment by m-swami** [comment]
Thanks for the information, i have created a MyTravelport ticket. Now please help us in BookingPriceReq issue, even if it is not necessary i think it is good to use booking sessions.
This issue -> https://github.com/Travelport/travelport-uapi-tutorial-php/issues/127
