### ISSUE TITLE
Authentication Result Error Message Response (77): User account is locked. #22

### ISSUE THREAD

**Issue by Adnan113** [Travelport/travelport-uapi-tutorial-php#132]
Hi, i'm still have same problem with test credential that travelport send to me.
This are my test credential

Universal API User ID:  Universal API/uAPI3964999191-ecd1c0f4
--
Universal API Password:  MrzyDdchTYxYNabq8FSsfZcnb
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7037607
URLs:  https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

i don't know how to send these credential through postman in xml form can you please tell me that format or you can send me that xml formatted file so i can send ,credential at  https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

and i'm not able to try again
Please help me @vivekjyotipramanik  
Adnan

**Comment by NirandaG** [comment]
Hi,
This should work by now.
Rgds,
Niranda

**Comment by marcadde23** [comment]
I have same issue here, this is my account credentials.


Universal API User ID:  Universal API/uAPI8907208289-36afdb0d
Universal API Password:  JgGfgXHJF34TTWpfbYtDZcEhB
Branch Code for Galileo (1G): P7004208

**Comment by NirandaG** [comment]
Hi,
This was locked due to invalid credentials and I have unlocked it.
Please use the correct username and password to avoid this getting locked again.
Also I have created the Robotic SignOn for this as well and now this should work fine.
Rgds,
Niranda

**Comment by stbeli** [comment]
Dear Niranda, 

I have have same issue:
Universal API User ID:  Universal API/uAPI6361813539-85eb9a22
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7002789
URLs:  https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

**Comment by NirandaG** [comment]
Hi,
This has been created. Please try now.
Rgds,
Niranda

**Comment by adilnaik** [comment]
Hi @NirandaG 
I have the same issue it says "(77)User account is locked".
Universal API User ID: Universal API/uAPI2726420276-3b2e1c43
Branch Code (TargetBranch): P7037567
please unblock my creds.

**Comment by smart25me** [comment]
Hi @NirandaG I have same issue, my account credentials.
Universal API User ID:  Universal API/uAPI1128768630
Universal API Password:  xYygw2MMbtRZdwb2z3jZxehM4
Branch Code for Galileo: P105207
thank you

**Comment by NirandaG** [comment]
Hi,
This has been unlocked.
Please use valid credentials to avoid this getting blocked again.
Rgds,
Niranda

**Comment by smart25me** [comment]
Thanks @NirandaG, it works.
But what do you mean valid credentials, how I got it.

**Comment by emcengineering** [comment]
$TARGETBRANCH = 'P107740';
$CREDENTIALS = 'Universal API/uAPI1120578595-1a27e0da:JaYyjS5cYqwS8frXE2q2sDHzm';
$Provider = '1P'; // Any provider you want to use like 1G/1P/1V/ACH

This account is also locked. Can you please unlock it?

**Comment by mugh33s** [comment]
Hi @NirandaG 
My account is locked. Can you please unlock?
Universal API User ID: Universal API/uAPI6035036525-8ff7f8fc
Universal API Password: Cbjk96WSgkXPaprCJrMrt8M9P
Branch Code for Galileo: P7004961
Thanks.
