### ISSUE TITLE
Hotel Search using postman : HOTEL DB TEMP UNAVAILABLE - RETRY REQUEST

### ISSUE THREAD

**Issue by talalhaider** [Travelport/travelport-uapi-tutorial-php#134]
![image](https://user-images.githubusercontent.com/2072121/39738691-f83bd820-52a5-11e8-8467-e7c915e986fb.png)

Error": [
                        {
                            "@type": "Error",
                            "Message": "HOTEL DB TEMP UNAVAILABLE - RETRY REQUEST"
                        }
                    ]

**Comment by vivekjyotipramanik** [comment]
Hi  talalhaider,

Please try with different city in HotelSearch request. Please try after sometime, maybe 1-2 hours. Thanks.

**Comment by talalhaider** [comment]
Still not working.

**Comment by talalhaider** [comment]
It is working now.
