### ISSUE TITLE
Error while processing

### ISSUE THREAD

**Issue by rahulsharma841990** [Travelport/travelport-uapi-tutorial-php#135]
Hello, 

 I am just trying to call the API using your Sample code, but its showing error

    `Processing! Please wait!
     Fatal error: Error occurred request/response processing! in C:\xampp\htdocs\tute\galilio\index.php on line 101`

**API Using**

`$soap_do = curl_init ("https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");`

can anyone please tell me what is the problem?

**Comment by vivekjyotipramanik** [comment]
Hi rahulsharma841990,

Could you please try your credentials in demosite and let us know if it is working fine there. Thanks.

http://demo.travelportuniversalapi.com/

**Comment by rahulsharma841990** [comment]
@vivekjyotipramanik 
Yes, its working in demo site

![image](https://user-images.githubusercontent.com/6939188/39786895-440ccfa8-5340-11e8-8943-35fab45b14d4.png)

**Comment by vivekjyotipramanik** [comment]
Hi rahulsharma841990,

If it is working fine with your credentials in demosite, Please share the complete code which you are using and getting error in php. Thanks.

**Comment by rahulsharma841990** [comment]
@vivekjyotipramanik 

**Here is my code:** 

`$TARGETBRANCH = '*******';
$CREDENTIALS = 'Universal API/user*****:ABC****';
$Provider = 'ACH'; // Any provider you want to use like 1G/1P/1V/ACH
$message = <<<EOM
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq TraceId="trace" AuthorizedBy="user" TargetBranch="$TARGETBRANCH" xmlns:air="http://www.travelport.com/schema/air_v29_0" xmlns:com="http://www.travelport.com/schema/common_v29_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="LGW"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="EDI"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2014-12-31">
            </air:SearchDepTime>            
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="$Provider"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
EOM;
$file = "001-".$Provider."_AirAvailabilityReq.xml"; // file name to save the request xml for test only(if you want to save the request/response)
prettyPrint($message,$file);//call function to pretty print xml
$auth = base64_encode("$CREDENTIALS"); 
$soap_do = curl_init ("https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");
$header = array(
"Content-Type: text/xml;charset=UTF-8", 
"Accept: gzip,deflate", 
"Cache-Control: no-cache", 
"Pragma: no-cache", 
"SOAPAction: \"\"",
"Authorization: Basic $auth", 
"Content-length: ".strlen($message),
); 
//curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 30); 
//curl_setopt($soap_do, CURLOPT_TIMEOUT, 30); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($soap_do, CURLOPT_POST, true ); 
curl_setopt($soap_do, CURLOPT_POSTFIELDS, $message); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true); // this will prevent the curl_exec to return result and will let us to capture output
$return = curl_exec($soap_do);
$file = "001-".$Provider."_AirAvailabilityRsp.xml"; // file name to save the response xml for test only(if you want to save the request/response)
$content = prettyPrint($return,$file);
parseOutput($content);
//print '<br>';
//echo $return;
//print '<br>';
//print_r(curl_getinfo($soap_do));
//Pretty print XML
function prettyPrint($result,$file){
    $dom = new DOMDocument;
    $dom->preserveWhiteSpace = false;
    $dom->loadXML($result);
    $dom->formatOutput = true;      
    //call function to write request/response in file   
    outputWriter($file,$dom->saveXML());
    return $dom->saveXML();
}
//function to write output in a file
function outputWriter($file,$content){  
    file_put_contents($file, $content); // Write request/response and save them in the File
}
function parseOutput($content){ //parse the Search response to get values to use in detail request
    $AirAvailabilitySearchRsp = $content; //use this if response is not saved anywhere else use above variable
    //echo $AirAvailabilitySearchRsp;
    $xml = simplexml_load_String("$AirAvailabilitySearchRsp", null, null, 'SOAP', true);    
    
    if($xml)
        echo "Processing! Please wait!";
    else{
        trigger_error("Encoding Error!", E_USER_ERROR);
    }
    $Results = $xml->children('SOAP',true);
    foreach($Results->children('SOAP',true) as $fault){
        if(strcmp($fault->getName(),'Fault') == 0){
            trigger_error("Error occurred request/response processing!", E_USER_ERROR);
        }
    }
    
    $count = 0;
    $fileName = "flights.txt";
    if(file_exists($fileName)){
        file_put_contents($fileName, "");
    }
    foreach($Results->children('air',true) as $nodes){
        foreach($nodes->children('air',true) as $hsr){
            if(strcmp($hsr->getName(),'AirSegmentList') == 0){
                foreach($hsr->children('air',true) as $hp){
                    if(strcmp($hp->getName(),'AirSegment') == 0){
                        $count = $count + 1;
                        file_put_contents($fileName,"\r\n"."Air Segment ".$count."\r\n"."\r\n", FILE_APPEND);
                        foreach($hp->attributes() as $a => $b   ){
                                $GLOBALS[$a] = "$b";
                                //echo "$a"." : "."$b";
                                file_put_contents($fileName,$a." : ".$b."\r\n", FILE_APPEND);
                        }                                               
                    }                   
                }
            }
            //break;
        }
    }
    $Token = 'Token';
    $TokenKey = 'TokenKey';
    $fileName = "tokens.txt";
    if(file_exists($fileName)){
        file_put_contents($fileName, "");
    }
    foreach($Results->children('air',true) as $nodes){
        foreach($nodes->children('air',true) as $hsr){
            if(strcmp($hsr->getName(),'HostTokenList') == 0){           
                foreach($hsr->children('common_v29_0', true) as $ht){
                    if(strcmp($ht->getName(), 'HostToken') == 0){
                        $GLOBALS[$Token] = $ht[0];
                        foreach($ht->attributes() as $a => $b){
                            if(strcmp($a, 'Key') == 0){
                                file_put_contents($fileName,$TokenKey.":".$b."\r\n", FILE_APPEND);
                            }
                        }                       
                        file_put_contents($fileName,$Token.":".$ht[0]."\r\n", FILE_APPEND);
                    }
                }
            }
        }
    }
    
    echo "\r\n"."Processing Done. Please check results in files.";
}`

**Comment by vivekjyotipramanik** [comment]
Hi  rahulsharma841990,

You are using 'ACH' as $provider. I believe your credentials is either 1G, 1V or 1P. Please check the credentials mail and it will be written there. Please use the correct $Provider. Thanks.

**Comment by rahulsharma841990** [comment]
@vivekjyotipramanik 

**In credentials i have:**

   `Below are the Pre-Production credentials for Acme Media Creations

    Universal API User ID: Universal API/xYz*******

     Universal API Password: ABC*****
     Branch Code: P******

     PCC : 7**`

**Comment by rahulsharma841990** [comment]
@vivekjyotipramanik 

Even i tried with all **like 1G/1P/1V/ACH**

**Comment by vivekjyotipramanik** [comment]
Hi rahulsharma841990,

Please check with Acme Media Creations about the Provider for the credentials. Please use the proper Provider. Thanks.

**Comment by rahulsharma841990** [comment]
@vivekjyotipramanik 

  On the demo site i was seletced galilio..!

**Comment by vivekjyotipramanik** [comment]
Hi rahulsharma841990,

Also, Please change the schema version to at least to v41. You are using very old schema which is v29. Also, the  PreferredTime="2014-12-31" you are using is 4 years older. Please use future dats , atleast 30-60 days from today's date. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi,

I have updated the code. Please give it a try. Thanks.

```xml
$TARGETBRANCH = '*******';
$CREDENTIALS = 'Universal API/user*****:ABC****';
$Provider = '1G'; // Any provider you want to use like 1G/1P/1V/ACH
$message = <<<EOM
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq TraceId="trace" AuthorizedBy="user" TargetBranch="$TARGETBRANCH" xmlns:air="http://www.travelport.com/schema/air_v41_0" xmlns:com="http://www.travelport.com/schema/common_v41_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="LGW"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="EDI"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2018-08-15">
            </air:SearchDepTime>            
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="$Provider"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
EOM;
$file = "001-".$Provider."_AirAvailabilityReq.xml"; // file name to save the request xml for test only(if you want to save the request/response)
prettyPrint($message,$file);//call function to pretty print xml
$auth = base64_encode("$CREDENTIALS"); 
$soap_do = curl_init ("https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");
$header = array(
"Content-Type: text/xml;charset=UTF-8", 
"Accept: gzip,deflate", 
"Cache-Control: no-cache", 
"Pragma: no-cache", 
"SOAPAction: \"\"",
"Authorization: Basic $auth", 
"Content-length: ".strlen($message),
); 
//curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 30); 
//curl_setopt($soap_do, CURLOPT_TIMEOUT, 30); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($soap_do, CURLOPT_POST, true ); 
curl_setopt($soap_do, CURLOPT_POSTFIELDS, $message); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true); // this will prevent the curl_exec to return result and will let us to capture output
$return = curl_exec($soap_do);
$file = "001-".$Provider."_AirAvailabilityRsp.xml"; // file name to save the response xml for test only(if you want to save the request/response)
$content = prettyPrint($return,$file);
parseOutput($content);
//print '<br>';
//echo $return;
//print '<br>';
//print_r(curl_getinfo($soap_do));
//Pretty print XML
function prettyPrint($result,$file){
    $dom = new DOMDocument;
    $dom->preserveWhiteSpace = false;
    $dom->loadXML($result);
    $dom->formatOutput = true;      
    //call function to write request/response in file   
    outputWriter($file,$dom->saveXML());
    return $dom->saveXML();
}
//function to write output in a file
function outputWriter($file,$content){  
    file_put_contents($file, $content); // Write request/response and save them in the File
}
function parseOutput($content){ //parse the Search response to get values to use in detail request
    $AirAvailabilitySearchRsp = $content; //use this if response is not saved anywhere else use above variable
    //echo $AirAvailabilitySearchRsp;
    $xml = simplexml_load_String("$AirAvailabilitySearchRsp", null, null, 'SOAP', true);    
    
    if($xml)
        echo "Processing! Please wait!";
    else{
        trigger_error("Encoding Error!", E_USER_ERROR);
    }
    $Results = $xml->children('SOAP',true);
    foreach($Results->children('SOAP',true) as $fault){
        if(strcmp($fault->getName(),'Fault') == 0){
            trigger_error("Error occurred request/response processing!", E_USER_ERROR);
        }
    }
    
    $count = 0;
    $fileName = "flights.txt";
    if(file_exists($fileName)){
        file_put_contents($fileName, "");
    }
    foreach($Results->children('air',true) as $nodes){
        foreach($nodes->children('air',true) as $hsr){
            if(strcmp($hsr->getName(),'AirSegmentList') == 0){
                foreach($hsr->children('air',true) as $hp){
                    if(strcmp($hp->getName(),'AirSegment') == 0){
                        $count = $count + 1;
                        file_put_contents($fileName,"\r\n"."Air Segment ".$count."\r\n"."\r\n", FILE_APPEND);
                        foreach($hp->attributes() as $a => $b   ){
                                $GLOBALS[$a] = "$b";
                                //echo "$a"." : "."$b";
                                file_put_contents($fileName,$a." : ".$b."\r\n", FILE_APPEND);
                        }                                               
                    }                   
                }
            }
            //break;
        }
    }
    $Token = 'Token';
    $TokenKey = 'TokenKey';
    $fileName = "tokens.txt";
    if(file_exists($fileName)){
        file_put_contents($fileName, "");
    }
    foreach($Results->children('air',true) as $nodes){
        foreach($nodes->children('air',true) as $hsr){
            if(strcmp($hsr->getName(),'HostTokenList') == 0){           
                foreach($hsr->children('common_v29_0', true) as $ht){
                    if(strcmp($ht->getName(), 'HostToken') == 0){
                        $GLOBALS[$Token] = $ht[0];
                        foreach($ht->attributes() as $a => $b){
                            if(strcmp($a, 'Key') == 0){
                                file_put_contents($fileName,$TokenKey.":".$b."\r\n", FILE_APPEND);
                            }
                        }                       
                        file_put_contents($fileName,$Token.":".$ht[0]."\r\n", FILE_APPEND);
                    }
                }
            }
        }
    }
    
    echo "\r\n"."Processing Done. Please check results in files.";
}
```

**Comment by rahulsharma841990** [comment]
@vivekjyotipramanik 

Great! Working now.

Thanks 👍
