### ISSUE TITLE
How to fetch results from LowFareSearchRsp

### ISSUE THREAD

**Issue by ghost** [Travelport/travelport-uapi-tutorial-php#137]
Is there any method to display lowfaresearchrsp results or i just have to create it by myself. I'm having problem in multiple SearchAirLeg where Outbound and Inbound data is mixed.

**Comment by vivekjyotipramanik** [comment]
Hi m-swami,

Do you mean display by displaying on screen like an UI, if yes, then yes, you have to develop your own UI to show the results. 

Regarding multiple AirLegs, Please find below the link with all the details regarding grouping. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Shared_Air_Topics/AirSegmentConnectionLogic.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAssociated%2520Topics%7C_____7

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Low_Fare_Shopping/Low_Fare_Shopping_(Synchronous).htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CLow%2520Fare%2520Shopping%7C_____2

**Comment by ghost** [comment]
Hi vivekjyotipramanik,

Issue is resolved now, while i was grouping flights between Outbound and Inbound flights they were displayed merged sometimes, then i saw in AirSegment tag there is a Group attribute which tells which flight is from Inbound or Outbound.
