### ISSUE TITLE
Activate test credentials

### ISSUE THREAD

**Issue by yatinmistry** [Travelport/travelport-uapi-tutorial-php#14]
Hello,

Please activate below test credentials.

Universal API User ID:  Universal API/uAPI3568924042-3768c943
TargetBranch :  Branch Code for Galileo (1G): P7009927

Thanks,
Yatin Mistry

**Comment by vivekjyotipramanik** [comment]
Hi Yatin,

We have unlocked the account. Could you please try again. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by yatinmistry** [comment]
Hello Vivekjyoti,

Thank you very much. Now it is working.


Thanks,

Yatin Mistry

**Comment by yatinmistry** [comment]
Hello VivekJyoti,

Please activate below test credentials.

Universal API User ID:  Universal API/uAPI4748044502-e449a512
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7004112


Thanks,

Yatin Mistry

**Comment by yatinmistry** [comment]
Hello VivekJyoti,

Activate credentials on urgent basis. As our flight module has stopped without api.

Thanks,
Yatin Mistry

**Comment by vivekjyotipramanik** [comment]
Hi Yatin,

We are working on to unlock the credentials. As soon as it is unlocked I will update here.
It should be unlocked by Monday. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by yatinmistry** [comment]
Hello Vivekjyoti Pramanik,

Thanks now credentials are working.

Thanks,
Yatin Mistry

**Comment by tinasherobert** [comment]
Hello,

Please activate below test credentials.

Universal API User ID:  Universal API/uAPI7341562091-18e3a6e9
TargetBranch : Branch Code for Galileo (1G): P7002716

Thanks,
Yatin Mistry

**Comment by saikat1989** [comment]
Hi Vivek,

Please activate below test credentials-
Universal API User ID:  Universal API/uAPI8968938106-bec96be5
TargetBranch : Branch Code for (1P): P107484

Thanks
Saikat
