### ISSUE TITLE
Error in UniversalRecordRetrieveReq

### ISSUE THREAD

**Issue by nitincdac** [Travelport/travelport-uapi-tutorial-php#140]
Hi 

I am facing a strange error in the response. I have tried this xml with Travelport API test Tool, which is working properly and giveing me the right response. But when I am trying this code with PHP CURL, I am getting "Error 404: SRVE0295E: Error reported: 404" in the response. Please see the below code 

$message = <<<EOM
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:air="http://www.travelport.com/schema/air_v42_0" xmlns:com="http://www.travelport.com/schema/common_v42_0" xmlns:common_v42_0="http://www.travelport.com/schema/common_v42_0" xmlns:univ="http://www.travelport.com/schema/universal_v42_0">
   <soapenv:Header/>
   <soapenv:Body>
      <univ:UniversalRecordRetrieveReq TraceId="trace" AuthorizedBy="user" TargetBranch="P7083471">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <univ:ProviderReservationInfo ProviderCode="1P" ProviderLocatorCode="23D8YX" />
      </univ:UniversalRecordRetrieveReq>
   </soapenv:Body>
</soapenv:Envelope>
EOM;

$auth = base64_encode("$CREDENTIALS"); 
$soap_do = curl_init("https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");                   
$header = array(
"Content-Type: text/xml;charset=UTF-8", 
"Accept: gzip,deflate", 
"Cache-Control: no-cache", 
"Pragma: no-cache", 
"SOAPAction: \"\"",
"Authorization: Basic $auth", 
"Content-length: ".strlen($message),
); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($soap_do, CURLOPT_POST, true ); 
curl_setopt($soap_do, CURLOPT_POSTFIELDS, $message); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header); 
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true);
$return = curl_exec($soap_do);
curl_close($soap_do);
echo $return;

Please help !!!
Regards

**Comment by NirandaG** [comment]
Hi,
Could yo u please send us the credentials you are passing?
Rgds,
Niranda

**Comment by nitincdac** [comment]
Hi Niranda

I am using the same credentials with Travelport API test Tool. 

$CREDENTIALS = "Universal API/uAPI6341447800-9dd17791:8e!Xs=F73w";

Regds

**Comment by NirandaG** [comment]
Hi,
Could you please change the $soap_do for the following and let us know?
https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/UniversalRecordService

Rgds,
Niranda

**Comment by nitincdac** [comment]
Hi Niranda

Working fine...  Thanks

regards
Nitin
