### ISSUE TITLE
Production environment: Unsuccessful primary host transaction causing reservation failure

### ISSUE THREAD

**Issue by sivaneshc** [Travelport/travelport-uapi-tutorial-php#144]
Hi,

In Production environment i made a booking in 6E. but ended up with below message. XMLs attached. "<common_v33_0Description>**Unsuccessful primary host transaction causing reservation failure.**</common_v33_0Description>".
[AirCreateReservationReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2079222/AirCreateReservationReq.txt)
[AirCreateReservationRes.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2079223/AirCreateReservationRes.txt)

Thank you

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

We do not support Production issues through github. Could you please create a MyTravelport ticket regarding this issue. Thanks.
