### ISSUE TITLE
AirCreateReservation - PNR has been created - Please retrieve PNR and check the booking and report issue immediately.

### ISSUE THREAD

**Issue by ghost** [Travelport/travelport-uapi-tutorial-php#146]
Hi Vivek,

I'm trying to perform booking but getting this error PNR has been created - Please retrieve PNR and check the booking and report issue immediately.

I have received success response before but when now i'm trying i got this error.
Is there anything i'm missing in xml request?

[xmls.zip](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2089862/xmls.zip)

**Comment by vivekjyotipramanik** [comment]
Hi m-swami,

Looks like UAPI could not retrieve the PNR, it created the booking in host system, but the retrieve failed. This might happen due to system downtime. Could you please try UniversalRecordRetrieve to retrieve the PNR. Also, Please try after sometime to book, as PreProduction might have some system downtime over the weekend. Thanks.

**Comment by ghost** [comment]
Three doubts/questions
1) There is a website http://demo.travelportuniversalapi.com, i'm checking my generated PNR on this website (Retrieve Universal Record) section. Is it okay to check on this website instead of doing UniversalRecordRetrieveReq.
2) Can we do AirCreateReservationReq using production credentials for test purpose and cancel after getting response, does it involve payment?
3) When we get AirCreateReservationRsp without any errors it contain LocatorCode in three sections
    <universal:UniversalRecord LocatorCode="02GZ49"
    <universal:ProviderReservationInfo LocatorCode="LW24S9"
    <air:AirReservation LocatorCode="02GZ4A"
    
    So which one is PNR?

**Comment by NirandaG** [comment]
Hi m-swami,
Please see my below comments:
1. You could use the Universal Retrieve service on the Demo site. For that one you need to pass the Universal Record Locator where you get from the AirCreate.
2. If you using Production, it would be better to check with your Travelport Account Manager before issuing the tickets.
3. In AirCreate Response the PNR would be: ProviderReservationInfo LocatorCode="LW24S9"
Hope this helps.
Rgds,
Niranda
