### ISSUE TITLE
LowFareResponse Parser : Cabin Class

### ISSUE THREAD

**Issue by devnox** [Travelport/travelport-uapi-tutorial-php#15]
Hello,
How to extract CabinClass in PHP ?

Thank you!

**Comment by vivekjyotipramanik** [comment]
Hi devnox,

We have added the code to extract CabinClass from LowFareSearchRsp in phpSample_Air_LFS.php. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by devnox** [comment]
Thank you. I will let you know ASAP

Thanks.

**Comment by devnox** [comment]
Its working! :)

Thank you!
