### ISSUE TITLE
U

### ISSUE THREAD

**Issue by ghost** [Travelport/travelport-uapi-tutorial-php#153]

**Comment by NirandaG** [comment]
Hi,
Could you please send us your username?
Rgds,
Niranda

**Comment by sajitkk** [comment]
username -  Universal API/uAPI1473616790-33a72d4b

**Comment by NirandaG** [comment]
Hi sajitkk,
You are using Pre-Production credentials. Please open a ticket at MyTravelport and a technician would assist with this.
https://my.travelport.com
Rgds,
Niranda
