### ISSUE TITLE
Error unmarshalling message body: Expected

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#157]
Hello,

Please we are facing this error Error unmarshalling message body: Expected "{http://www.travelport.com/schema.... 

I have also attached the request
[001-1G_AirBookingReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2242311/001-1G_AirBookingReq.txt)
[001-1G_AirBookingRsp.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2242312/001-1G_AirBookingRsp.txt)

 and response please help us it's kind of urgent matter.

best regards,

**Comment by vivekjyotipramanik** [comment]
Hi @Alex0084,

You are not using the namespaces properly. The AirPricingSolution is missing the namespace. You have to declare it like air:AirPricingSolution as you have declared the "air:" namespace in the header. Thanks.

**Comment by jayapen** [comment]
I am facing error while doing a passive create reservation request


Error unmarshalling message body: Expected "{http://www.travelport.com/schema/universal_v48_0}PassiveCreateReservationReq" end tag,
 found "{http://www.travelport.com/schema/common_v48_0}EmailNotification" start tag (line 2, col 1575, in UTF-8) Source=GDSMultiConnect StackTrace: at GDSServices.TravelPortConnect.CreatePNRRecord()





[PassiveCreateReservationReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/4156242/PassiveCreateReservationReq.txt)
