### ISSUE TITLE
(77): User account is locked

### ISSUE THREAD

**Issue by emcengineering** [Travelport/travelport-uapi-tutorial-php#158]
$TARGETBRANCH = 'P107740';
$CREDENTIALS = 'Universal API/uAPI1120578595-1a27e0da:JaYyjS5cYqwS8frXE2q2sDHzm';
$Provider = '1P'; // Any provider you want to use like 1G/1P/1V/ACH

This account is also locked. Can you please unlock it or inform me what we are doing incorrectly?

**Comment by NirandaG** [comment]
Hi,
This has been unlocked. Please use valid username and password to avoid this getting blocked again.
Rgds,
Niranda

**Comment by alamen-pgooja** [comment]
I have the same issue how can I validate my user credentials (i use trial) ??

**Comment by alamen-pgooja** [comment]
when I use https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/ to check the credentials that send to me in the welcome letter it says user invalid

**Comment by alamen-pgooja** [comment]
the script response is  77 Authentication Result Error Message Response (77): User account is locked. Authentication Result Error Message Response (77): User account is locked.

**Comment by NirandaG** [comment]
Could you please share the username?
Rgds,
Niranda
