### ISSUE TITLE
Error while  storing new price 

### ISSUE THREAD

**Issue by rxmax200** [Travelport/travelport-uapi-tutorial-php#159]
Getting "INVALID NUMBER OF SEGMENTS SELECTED | Unexpected system error." while i am trying to add the new  airPricing info using UniversalRecordModifyReq API . I have attached the  universonRetrieve response ,Airpricing response and UniversalRecordModify request .
Please let me know i am getting this error and how to resolve it 

[AirpricingResponse.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2252909/AirpricingResponse.txt)

[UniversonRetrieveResponse.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2252907/UniversonRetrieveResponse.txt)
[UniversalRecordModifierRequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2252908/UniversalRecordModifierRequest.txt)

**Comment by vivekjyotipramanik** [comment]
Hi  rxmax200,

You are adding air in universalmodify without any AirSegmentm when the SegmentRef in AirPricingInfo is trying to resolve the SegmentRef's it is failing. Please add the AirSegment in the request as well inside the AirAdd element. Thanks.

**Comment by rxmax200** [comment]
Now i am getting this error

<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
SOAP:Body
SOAP:Fault
Server.InvalidRequestException
[Error] :1:2792: cvc-complex-type.2.4.a: Invalid content was found starting with element 'ns4:AirPricingInfo'. One of '{"http://www.travelport.com/schema/air_v42_0":AirSegment}' is expected.


1000
WEBSVC
Data
Validation failed on request message.
FBAFA5F40A076478AC70B67A26CB88C9



LastElement
FlightDetails Key=aJlXxT3R2BKAMtdsBAAAAA== IncludesVAT=false LatestTicketingTime=2018-08-03T23:59:00.000-04:00 PricingMethod=GuaranteedUsingAirlinePrivateFare ETicketability=Yes PlatingCarrier=WN TotalPrice=USD260.80 BasePrice=USD221.40 ApproximateTotalPrice=USD260.80 ApproximateBasePrice=USD221.40 Taxes=USD39.40 ApproximateTaxes=USD39.40 ProviderCode=1V



</SOAP:Fault>
</SOAP:Body>
</SOAP:Envelope>

I have attached the UniversalRecordModifyReq for reference
[universalmodifierRequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2256630/universalmodifierRequest.txt)

**Comment by rxmax200** [comment]
I am tryin to add the AirPricingInfo not the air segment .
