### ISSUE TITLE
SeatMapReq change currency ?

### ISSUE THREAD

**Issue by yatinmistry** [Travelport/travelport-uapi-tutorial-php#16]
Hello, 

How to change currency in [SeatMapReq](https://support.travelport.com/webhelp/uapi/Subsystems/Schemas/Content/Schemas/SeatMapReq.html) ?

[seatmap_response.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/257067/seatmap_response.txt)
[seatmap_request.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/257068/seatmap_request.txt)

**Comment by vivekjyotipramanik** [comment]
Hi Yatin,

There is no way to specify currency in SeatMapReq as PreferredCurrency. Generally the currency depends on the PCC location of the Agency. We can specify AgencysellInfo inside SeatMapreq and specify the currency there as the currency using which the reservation will be created/is created.
Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by yatinmistry** [comment]
Hello Vivekjyoti,

Thanks for your quick reply.
I have used the AgencysellInfo with CurrencyCode but it always return seatPrice in AUD currency.
Please provide working example.

Thanks,

Yatin Mistry

**Comment by vivekjyotipramanik** [comment]
Hi yatin,

If the Agency PCC is based on any Australia city, then the currency will come in AUD.
Looks like the PCC you are using is based on Australia.

I believe infants cant select seats. I will check and confirm. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by yatinmistry** [comment]
Hello Vivekjyoti,

What is PCC? and How can know which PCC i am using ?

**Comment by vivekjyotipramanik** [comment]
Hi Yatin,

PCC is the Pseudo City Code, it is kind of an Agency Identifier and generally each TargetBranch is associated with a PCC. After you book/create an AirReservation, try search with OwningPCC in the response and it will show the PCC. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by yatinmistry** [comment]
Hi Vivekjyoti,

Thanks for the info. I will check and revert you soon.

Thanks,
Yatin Mistry

**Comment by yatinmistry** [comment]
Hello Vivekjyoti,

In my booking response i get below owningpcc.
 OwningPCC=6IS2

Thanks,
Yatin Mistry
