### ISSUE TITLE
NO VALID FARE FOR INPUT CRITERIA

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#162]
Hello 

Please some of result give this
      NO VALID FARE FOR INPUT CRITERIA

[NO VALID FARE FOR INPUT CRITERIA.zip](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2266069/NO.VALID.FARE.FOR.INPUT.CRITERIA.zip)

Can someone please help asap. 

Attach request and response

**Comment by Alex0084** [comment]
Any help please?

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

This is a valid error and if for a particular market there is no fare available, this error will show up. In Test environment, the data is very much limited and this kind of error might show up frequently. Please try with different origin/destination/airlines and dates. Thanks.
