### ISSUE TITLE
Account Locked

### ISSUE THREAD

**Issue by engrashid** [Travelport/travelport-uapi-tutorial-php#168]
MY user id is below
Universal API User ID:  Universal API/uAPI7662861526-8cd988d4
Branch Code for Galileo (1G): P7002731

Can you please unlock it?

**Comment by NirandaG** [comment]
This has been unlocked, Please use valid credentials to avoid this getting blocked again.
Rgds,
Niranda

**Comment by engrashid** [comment]
DEAR Niranda, 
Thanks a lot .Its working now .
