### ISSUE TITLE
Please unlock my account

### ISSUE THREAD

**Issue by naiyerazm** [Travelport/travelport-uapi-tutorial-php#180]
Please unlock my account
Universal API User ID: Universal API/uAPI1104070642-6913daae
Branch Code (TargetBranch) for ProviderName (ProviderCode): Branch Code for Worldspan (1P): P107782
[xml.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2717449/xml.txt)

**Comment by NirandaG** [comment]
This has been unlocked.
Rgds,
Niranda

**Comment by naiyerazm** [comment]
<SOAP-ENV:faultstring>Authentication Result Error Message Response  (77): User account is locked.</SOAP-ENV:faultstring>

**Comment by akv0204** [comment]
Hello Niranda,
Kindly enable robotic sign-on. Credentials are -
ID:  Universal API/uAPI6768275016-96b0fd84
Target branch: P7009887

--
Reagrds,
Ajay

**Comment by NirandaG** [comment]
Hi Ajay,
This has been unlocked and created the Robotic SignOn.
Rgds,
Niranda
