### ISSUE TITLE
Air Service - Change Currency

### ISSUE THREAD

**Issue by raymond180** [Travelport/travelport-uapi-tutorial-php#181]
Hi,

I just tried the Air/phpSample_Air_LFS.php example. I only changed what was needed to be changed and left everything untouched. However, the program returns the ticket pricing currency as AUD but I need it in TWD instead. Could anyone guide me how to change currency setting?

**Comment by vivekjyotipramanik** [comment]
Hi  raymond180,

The currency depends on your user settings. The TargetBranch and userid you are using might be tagged to AUD and that is the reason you are getting back response in AUD. You can the currency using AirPricingModifiers. Please find below the link with the details. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Low_Fare_Shopping/Low_Fare_Shopping_Air_Price_Modifiers.htm?Highlight=CurrencyType


https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Low_Fare_Shopping/Low_Fare_Shopping_Air_Price_Modifiers.htm?Highlight=CurrencyType

**Comment by raymond180** [comment]
Hi vivekjyotipramanik,

Thank you for providing the info. I have resolved the issue.
