### ISSUE TITLE
POWER P RODUCTS ACTIVATION REQUIRED-CONTACT YOUR WORLDSPAN A.E.

### ISSUE THREAD

**Issue by naiyerazm** [Travelport/travelport-uapi-tutorial-php#184]
POWER P RODUCTS ACTIVATION REQUIRED-CONTACT YOUR WORLDSPAN A.E.
Universal API/uAPI2986246588-a0671bcc
P107384 (Worldspan - 1P)

**Comment by hasintha** [comment]
Having the same issue

**Comment by vivekjyotipramanik** [comment]
Hi hasintha,

Please share the full request and response. Thanks.

**Comment by hasintha** [comment]
Hi Vivek, sorry for the late response. Here are the req and response

Request 

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:LowFareSearchReq TraceId="trace" AuthorizedBy="user" SolutionResult="true" TargetBranch="$TARGETBRANCH" xmlns:air="http://www.travelport.com/schema/air_v48_0" xmlns:com="http://www.travelport.com/schema/common_v48_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
				<com:CityOrAirport PreferCity="true" Code="LON"/>
            </air:SearchOrigin>
            <air:SearchDestination>
				<com:CityOrAirport PreferCity="true" Code="CMB"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="$PreferredDate">
            </air:SearchDepTime>            
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="$Provider"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
		 <com:SearchPassenger BookingTravelerRef="1" Code="ADT" xmlns:com="http://www.travelport.com/schema/common_v48_0"/>
      </air:LowFareSearchReq>
   </soapenv:Body>
</soapenv:Envelope>
EOM;`

The Response

`<?xml version="1.0"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Business</faultcode>
      <faultstring>POWER P RODUCTS ACTIVATION REQUIRED-CONTACT YOUR WORLDSPAN A.E. </faultstring>
      <detail>
        <common_v48_0:ErrorInfo xmlns:common_v48_0="http://www.travelport.com/schema/common_v48_0">
          <common_v48_0:Code>3000</common_v48_0:Code>
          <common_v48_0:Service>AIRSVC</common_v48_0:Service>
          <common_v48_0:Type>Business</common_v48_0:Type>
          <common_v48_0:Description>General air service Error.</common_v48_0:Description>
          <common_v48_0:TransactionId>14677EB80A0764775D3E3CFC09FD733B</common_v48_0:TransactionId>
          <common_v48_0:TraceId>trace</common_v48_0:TraceId>
        </common_v48_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>
`

**Comment by vivekjyotipramanik** [comment]
Hi hasintha,

I believe you are using PreProduction credentials and it is not activated properly. Could you please create a ticket in My.Travelport.com. Thanks.

**Comment by hasintha** [comment]
Will do vivek
