### ISSUE TITLE
Action Status date is past dated

### ISSUE THREAD

**Issue by imon91** [Travelport/travelport-uapi-tutorial-php#185]
When I have applied theses file for booking it showed that "NAME/ Modify Booking". I have shared it as a text format  booking file and response file. please check it 
![error_response](https://user-images.githubusercontent.com/34941713/50783013-cbe9b000-12d3-11e9-8b05-901fe119a814.PNG)
[bookimg_file.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2733648/bookimg_file.txt)

**Comment by vivekjyotipramanik** [comment]
Hi  imon91,

Please remove the + from country code and the DOT from name prefix and give it a try again. Thanks.

**Comment by imon91** [comment]
Hello vivekjyotipramanik
Thanks for your reply. Now its give a response file but I am not sure that that is desire response file or not. I have shared the response file. would you check please. I have applied for ticketing it shows an error message


Thank You



<?xml version="1.0"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <universal:AirCreateReservationRsp xmlns:universal="http://www.travelport.com/schema/universal_v29_0" xmlns:common_v29_0="http://www.travelport.com/schema/common_v29_0" xmlns:air="http://www.travelport.com/schema/air_v29_0" TraceId="trace" TransactionId="2B5853940A075716FAF2CAB8C3CDAADA" ResponseTime="2517">
      <universal:UniversalRecord LocatorCode="M7DD3F" Version="0" Status="Active">
        <common_v29_0:BookingTraveler Key="LPJxggBAAA/BtcL8KFAAAA==" TravelerType="ADT" DOB="1985-01-05" Gender="M" ElStat="A">
          <common_v29_0:BookingTravelerName Prefix="mr" First="Tasnim" Last="Imon"/>
          <common_v29_0:DeliveryInfo>
            <common_v29_0:ShippingAddress Key="4CfGbgWc1BKAlapc6KAAAA==" ElStat="A">
              <common_v29_0:AddressName>Bangladesh</common_v29_0:AddressName>
              <common_v29_0:Street>new palasia</common_v29_0:Street>
              <common_v29_0:City>indore</common_v29_0:City>
              <common_v29_0:State>MP</common_v29_0:State>
              <common_v29_0:PostalCode>452001</common_v29_0:PostalCode>
              <common_v29_0:Country>BD</common_v29_0:Country>
              <common_v29_0:ProviderReservationInfoRef Key="4CfGbgWc1BKAYH+c6KAAAA=="/>
            </common_v29_0:ShippingAddress>
          </common_v29_0:DeliveryInfo>
          <common_v29_0:PhoneNumber Key="4CfGbgWc1BKAiapc6KAAAA==" Type="None" Location="DAC" CountryCode="880" Number="1676-224087" ElStat="A">
            <common_v29_0:ProviderReservationInfoRef Key="4CfGbgWc1BKAYH+c6KAAAA=="/>
          </common_v29_0:PhoneNumber>
          <common_v29_0:Email Key="4CfGbgWc1BKAkapc6KAAAA==" Type="Home" EmailID="tasnim.hosen@gmail.com" ElStat="A">
            <common_v29_0:ProviderReservationInfoRef Key="4CfGbgWc1BKAYH+c6KAAAA=="/>
          </common_v29_0:Email>
          <common_v29_0:SSR Key="4CfGbgWc1BKAjapc6KAAAA==" Status="HK" Type="DOCS" FreeText="P/BD/00004567/BD/0000000/M/13DEC14/IMON/TASNIM -1IMON/TASNIMMR" Carrier="BG" ProviderReservationInfoRef="4CfGbgWc1BKAYH+c6KAAAA==" ElStat="A"/>
          <common_v29_0:Address Key="4CfGbgWc1BKAmapc6KAAAA==" ElStat="A">
            <common_v29_0:AddressName>indore</common_v29_0:AddressName>
            <common_v29_0:Street>new palasia</common_v29_0:Street>
            <common_v29_0:City>indore</common_v29_0:City>
            <common_v29_0:State>DHAKA</common_v29_0:State>
            <common_v29_0:PostalCode>121</common_v29_0:PostalCode>
            <common_v29_0:Country>BD</common_v29_0:Country>
            <common_v29_0:ProviderReservationInfoRef Key="4CfGbgWc1BKAYH+c6KAAAA=="/>
          </common_v29_0:Address>
        </common_v29_0:BookingTraveler>
        <common_v29_0:ActionStatus Key="4CfGbgWc1BKAnapc6KAAAA==" Type="ACTIVE" ProviderReservationInfoRef="4CfGbgWc1BKAYH+c6KAAAA==" ProviderCode="1G" ElStat="A"/>
        <universal:ProviderReservationInfo Key="4CfGbgWc1BKAYH+c6KAAAA==" ProviderCode="1G" LocatorCode="ZBL3NG" CreateDate="2019-01-08T02:43:57.721+00:00" ModifiedDate="2019-01-08T02:43:57.721+00:00" HostCreateDate="2019-01-08" OwningPCC="302I"/>
        <air:AirReservation LocatorCode="RHVYK7" CreateDate="2019-01-08T02:43:57.241+00:00" ModifiedDate="2019-01-08T02:43:57.721+00:00">
          <common_v29_0:SupplierLocator SupplierCode="BG" SupplierLocatorCode="APK5D" ProviderReservationInfoRef="4CfGbgWc1BKAYH+c6KAAAA==" CreateDateTime="2019-01-08T02:43:00.000+00:00"/>
          <common_v29_0:BookingTravelerRef Key="LPJxggBAAA/BtcL8KFAAAA=="/>
          <common_v29_0:ProviderReservationInfoRef Key="4CfGbgWc1BKAYH+c6KAAAA=="/>
          <air:AirSegment Key="LPJxggBAAA/BtcL8KFAAAA==" Group="0" Carrier="BG" CabinClass="Economy" FlightNumber="465" ProviderCode="1G" Origin="DAC" Destination="JSR" DepartureTime="2019-02-10T08:00:00.000+06:00" ArrivalTime="2019-02-10T08:45:00.000+06:00" TravelTime="45" Distance="87" ClassOfService="G" ETicketability="Yes" Equipment="DH8" Status="HK" ChangeOfPlane="false" GuaranteedPaymentCarrier="No" ProviderReservationInfoRef="4CfGbgWc1BKAYH+c6KAAAA==" TravelOrder="1" OptionalServicesIndicator="false" ParticipantLevel="Secure Sell" ElStat="A">
            <air:FlightDetails Key="4CfGbgWc1BKAaH+c6KAAAA==" Origin="DAC" Destination="JSR" DepartureTime="2019-02-10T08:00:00.000+06:00" ArrivalTime="2019-02-10T08:45:00.000+06:00" FlightTime="45" TravelTime="45" Equipment="DH8" OriginTerminal="1" DestinationTerminal="1" ElStat="A"/>
            <common_v29_0:SellMessage>DEPARTS DAC TERMINAL 1  - ARRIVES JSR TERMINAL 1</common_v29_0:SellMessage>
            <common_v29_0:SellMessage>*DEPARTURE DAC TERMINAL 1 / ARRIVAL JSR TERMINAL 1*</common_v29_0:SellMessage>
          </air:AirSegment>
          <air:AirPricingInfo Key="LPJxggBAAA/BwcL8KFAAAA==" TotalPrice="BDT2900" BasePrice="BDT2371" ApproximateTotalPrice="BDT2900" ApproximateBasePrice="BDT2371" Taxes="BDT529" LatestTicketingTime="2019-02-10T23:59:00.000+06:00" TrueLastDateToTicket="2019-02-10T23:59:00.000+06:00" PricingMethod="GuaranteedUsingAirlinePrivateFare" Refundable="true" Exchangeable="true" IncludesVAT="false" ETicketability="Yes" PlatingCarrier="BG" ProviderCode="1G" ProviderReservationInfoRef="4CfGbgWc1BKAYH+c6KAAAA==" AirPricingInfoGroup="1" PricingType="StoredFare" ElStat="A">
            <air:FareInfo Key="LPJxggBAAA/B0cL8KFAAAA==" FareBasis="GDACFO" PassengerTypeCode="ADT" Origin="DAC" Destination="JSR" EffectiveDate="2019-01-08T00:00:00.000+06:00" Amount="BDT2371" PrivateFare="AirlinePrivateFare" PseudoCityCode="302I" ElStat="A">
              <air:ContractCode Code="WDOM" ProviderCode="1G"/>
              <common_v29_0:Endorsement Value="VALID ON BG ONLY"/>
              <common_v29_0:Endorsement Value="TKT VALIDITY 6 MONTHS ONLY"/>
              <air:BaggageAllowance>
                <air:MaxWeight Value="20" Unit="Kilograms"/>
              </air:BaggageAllowance>
            </air:FareInfo>
            <air:BookingInfo BookingCode="G" CabinClass="Economy" FareInfoRef="LPJxggBAAA/B0cL8KFAAAA==" SegmentRef="LPJxggBAAA/BtcL8KFAAAA=="/>
            <air:TaxInfo Category="BD" Amount="BDT25" Key="4CfGbgWc1BKAgH+c6KAAAA=="/>
            <air:TaxInfo Category="E5" Amount="BDT4" Key="4CfGbgWc1BKAhH+c6KAAAA=="/>
            <air:TaxInfo Category="OW" Amount="BDT500" Key="4CfGbgWc1BKAiH+c6KAAAA=="/>
            <air:FareCalc>DAC BG JSR 2371GDACFO BDT2371END</air:FareCalc>
            <air:PassengerType Code="ADT" BookingTravelerRef="LPJxggBAAA/BtcL8KFAAAA==">
              <air:FareGuaranteeInfo GuaranteeDate="2019-01-08" GuaranteeType="GuaranteedUsingAirlinePrivateFare"/>
            </air:PassengerType>
            <common_v29_0:BookingTravelerRef Key="LPJxggBAAA/BtcL8KFAAAA=="/>
            <air:ChangePenalty>
              <air:Percentage>0.00</air:Percentage>
            </air:ChangePenalty>
            <air:CancelPenalty>
              <air:Percentage>0.00</air:Percentage>
            </air:CancelPenalty>
            <air:TicketingModifiersRef Key="4CfGbgWc1BKAfH+c6KAAAA=="/>
          </air:AirPricingInfo>
          <air:TicketingModifiers PlatingCarrier="BG" Key="4CfGbgWc1BKAfH+c6KAAAA==" ElStat="A">
            <air:DocumentSelect IssueElectronicTicket="true"/>
          </air:TicketingModifiers>
        </air:AirReservation>
        <common_v29_0:AgencyInfo>
          <common_v29_0:AgentAction ActionType="Created" AgentCode="uAPI3479047859-dfa41a9b" BranchCode="P3018376" AgencyCode="S3018367" EventTime="2019-01-08T02:43:55.473+00:00"/>
        </common_v29_0:AgencyInfo>
      </universal:UniversalRecord>
    </universal:AirCreateReservationRsp>
  </SOAP:Body>
</SOAP:Envelope>
