### ISSUE TITLE
Error For Booking 

### ISSUE THREAD

**Issue by imon91** [Travelport/travelport-uapi-tutorial-php#190]
Hello 
I have got this error when I tried to book would you check it please response
<img width="921" alt="tttt1" src="https://user-images.githubusercontent.com/34941713/51464684-54feed80-1d90-11e9-9663-fdbea1c8c6a6.PNG">

`
<?php

$TARGETBRANCH = 'P3018376';
$CREDENTIALS = 'Universal API/uAPI3479047859-dfa41a9b:tL+9P4o_cE';
$PROVIDER = '1G'; // Any provider you want to use like 1G/1P/1V/ACH
//$PreferredDepDate = date('2019-03-30', strtotime("75 day"));

$message = <<<EOM
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header />
  <soapenv:Body>
    <univ:AirCreateReservationReq xmlns:univ="http://www.travelport.com/schema/universal_v29_0" AuthorizedBy="user" RetainReservation="None" TargetBranch="P3018376" TraceId="trace">
      <com:BillingPointOfSaleInfo xmlns:com="http://www.travelport.com/schema/common_v29_0" OriginApplication="UAPI" />
      <com:BookingTraveler xmlns:com="http://www.travelport.com/schema/common_v29_0" DOB="1985-01-05" Gender="M" Key="KUzkmhBAAA/Bu0nmMDAAAA==" TravelerType="ADT">
        <com:BookingTravelerName First="Tasnim" Last="Imon" Prefix="mr" />
        <com:DeliveryInfo>
          <com:ShippingAddress>
            <com:AddressName>Bangladesh</com:AddressName>
            <com:Street>new palasia</com:Street>
            <com:City>indore</com:City>
            <com:State>mp</com:State>
            <com:PostalCode>452001</com:PostalCode>
            <com:Country>BD</com:Country>
          </com:ShippingAddress>
        </com:DeliveryInfo>
        <com:PhoneNumber CountryCode="880" Location="DAC" Number="1676-224087" />
        <com:Email EmailID="tasnim.hosen@gmail.com" Type="Home" />
        <com:SSR Carrier="BG" FreeText="P/BD/F1234567/BD/05Jan85/M/13Dec14/Imon/Tasnim" SegmentRef="dnzkmhBAAA/B/BuIIDAAAA==" Status="HK" Type="DOCS" />
        <com:Address>
          <com:AddressName>indore</com:AddressName>
          <com:Street>new palasia</com:Street>
          <com:City>indore</com:City>
          <com:State>Dhaka</com:State>
          <com:PostalCode>121</com:PostalCode>
          <com:Country>BD</com:Country>
        </com:Address>
      </com:BookingTraveler>
  <air:AirPricingSolution xmlns:air="http://www.travelport.com/schema/air_v29_0" Key="KUzkmhBAAA/Bt0nmMDAAAA==" TotalPrice="BDT30485" BasePrice="USD330.00" ApproximateTotalPrice="BDT30485" ApproximateBasePrice="BDT27456" EquivalentBasePrice="BDT27456" Taxes="BDT3029" ApproximateTaxes="BDT3029" >
	  
	  
        <air:AirSegment Key="KUzkmhBAAA/Bu0nmMDAAAA==" Group="0" Carrier="BG" FlightNumber="91" Origin="DAC" Destination="CCU" DepartureTime="2019-03-28T07:00:00.000+06:00" ArrivalTime="2019-03-28T07:15:00.000+05:30"  ETicketability="Yes" Equipment="DH8" ChangeOfPlane="false" ParticipantLevel="Secure Sell" OptionalServicesIndicator="false" AvailabilitySource="A" ProviderCode="1G" />
          
        <air:AirSegment Key="KUzkmhBAAA/Bw0nmMDAAAA==" Group="0" Carrier="AI" FlightNumber="773" Origin="CCU" Destination="BOM" DepartureTime="2019-03-28T16:50:00.000+05:30" ArrivalTime="2019-03-28T19:45:00.000+05:30"  ETicketability="Yes" Equipment="319" ChangeOfPlane="false" ParticipantLevel="Secure Sell" LinkAvailability="true"  OptionalServicesIndicator="false"  ProviderCode="1G" />
         
        <air:AirSegment Key="KUzkmhBAAA/By0nmMDAAAA==" Group="0" Carrier="AI" FlightNumber="9627" Origin="BOM" Destination="IDR" DepartureTime="2019-03-29T12:45:00.000+05:30" ArrivalTime="2019-03-29T14:55:00.000+05:30"  ETicketability="Yes" Equipment="ATR" ChangeOfPlane="false" ParticipantLevel="Secure Sell" LinkAvailability="true"  OptionalServicesIndicator="false"  ProviderCode="1G" />
         
        <air:AirSegment Key="KUzkmhBAAA/B00nmMDAAAA==" Group="1" Carrier="AI" FlightNumber="635" Origin="IDR" Destination="DEL" DepartureTime="2019-04-30T09:15:00.000+05:30" ArrivalTime="2019-04-30T11:10:00.000+05:30"  ETicketability="Yes" Equipment="319" ChangeOfPlane="false" ParticipantLevel="Secure Sell" LinkAvailability="true"  OptionalServicesIndicator="false"  ProviderCode="1G" />
         
        <air:AirSegment Key="KUzkmhBAAA/B20nmMDAAAA==" Group="1" Carrier="AI" FlightNumber="20" Origin="DEL" Destination="CCU" DepartureTime="2019-04-30T14:25:00.000+05:30" ArrivalTime="2019-04-30T16:40:00.000+05:30"  ETicketability="Yes" Equipment="788" ChangeOfPlane="false" ParticipantLevel="Secure Sell" LinkAvailability="true"  OptionalServicesIndicator="false"  ProviderCode="1G" />
         
        <air:AirSegment Key="KUzkmhBAAA/B40nmMDAAAA==" Group="1" Carrier="BG" FlightNumber="96" Origin="CCU" Destination="DAC" DepartureTime="2019-04-30T20:35:00.000+05:30" ArrivalTime="2019-04-30T22:05:00.000+06:00"  ETicketability="Yes" Equipment="738" ChangeOfPlane="false" ParticipantLevel="Secure Sell" OptionalServicesIndicator="false"  ProviderCode="1G" />
   
		
		<air:AirPricingInfo Key="KUzkmhBAAA/B80nmMDAAAA==" TotalPrice="BDT30485" BasePrice="USD330.00" ApproximateTotalPrice="BDT30485" ApproximateBasePrice="BDT27456" EquivalentBasePrice="BDT27456" Taxes="BDT3029" ApproximateTaxes="BDT3029" LatestTicketingTime="2019-01-25" PricingMethod="Guaranteed" Refundable="true" ETicketability="Yes" PlatingCarrier="AI" ProviderCode="1G" >
		
		
        <air:FareInfo Key="KUzkmhBAAA/BD1nmMDAAAA==" FareBasis="KBD3M" PassengerTypeCode="ADT" Origin="DAC" Destination="CCU" EffectiveDate="2019-01-20T22:04:00.000+06:00" DepartureDate="2019-03-28" Amount="BDT3744" NegotiatedFare="false" NotValidAfter="2019-06-28">
          <air:BaggageAllowance>
            <air:MaxWeight Value="20" Unit="Kilograms"/>
          </air:BaggageAllowance>
          <air:FareRuleKey FareInfoRef="KUzkmhBAAA/BD1nmMDAAAA==" ProviderCode="1G">gws-eJxNTkEOg0AIfIyZ+4BttLddWbVJ0720Hrz0/88orDUpCczAkIGUklJuFGX6jw6fblpRNwMq1NNsw+VKQrzZQXLEYyr9E82g19HntWkHStsymdUBiyw8pAjsrZZsYdRsHQVxFkF9gJPMd6c1l3d+SZz1Rf4kDvAvv6XVKgk=</air:FareRuleKey>
          <air:Brand Key="KUzkmhBAAA/BcEomMDAAAA==" BrandFound="false"/>
        </air:FareInfo>
        <air:FareInfo Key="KUzkmhBAAA/B11nmMDAAAA==" FareBasis="UEPP" PassengerTypeCode="ADT" Origin="CCU" Destination="IDR" EffectiveDate="2019-01-20T22:04:00.000+06:00" DepartureDate="2019-03-28" Amount="BDT10355" NegotiatedFare="false" NotValidBefore="2019-03-29" NotValidAfter="2019-03-29">
          <air:FareSurcharge Key="KUzkmhBAAA/Bn2nmMDAAAA==" Type="Other" Amount="NUC4.24"/>
          <air:FareSurcharge Key="KUzkmhBAAA/Bo2nmMDAAAA==" Type="Other" Amount="NUC4.24"/>
          <air:BaggageAllowance>
            <air:MaxWeight Value="20" Unit="Kilograms"/>
          </air:BaggageAllowance>
          <air:FareRuleKey FareInfoRef="KUzkmhBAAA/B11nmMDAAAA==" ProviderCode="1G">gws-eJxNTssKwzAM+5iiu+w1pL2lpAnrJZTSDHrZ/3/GnHSDGWzJll8hBKXMFGX4twHvYdlQagQK1HxbD4i42ffsgo0k1LTv6AseOlm5dOlGaU3MzGqArJm31AxXjzFW00TH0RlS0M6iUZvAj6Sn0bKsJ1Utn6hO/Osr0sP+/AAibyrI</air:FareRuleKey>
          <air:Brand Key="KUzkmhBAAA/BeEomMDAAAA==" BrandID="192563"/>
        </air:FareInfo>
        <air:FareInfo Key="KUzkmhBAAA/Bp2nmMDAAAA==" FareBasis="UEPP" PassengerTypeCode="ADT" Origin="IDR" Destination="CCU" EffectiveDate="2019-01-20T22:04:00.000+06:00" DepartureDate="2019-04-30" Amount="BDT9589" NegotiatedFare="false" NotValidBefore="2019-04-30" NotValidAfter="2019-04-30">
          <air:FareSurcharge Key="KUzkmhBAAA/B82nmMDAAAA==" Type="Other" Amount="NUC4.24"/>
          <air:FareSurcharge Key="KUzkmhBAAA/B92nmMDAAAA==" Type="Other" Amount="NUC4.24"/>
          <air:BaggageAllowance>
            <air:MaxWeight Value="20" Unit="Kilograms"/>
          </air:BaggageAllowance>
          <air:FareRuleKey FareInfoRef="KUzkmhBAAA/Bp2nmMDAAAA==" ProviderCode="1G">gws-eJxNTssKwzAM+5iiu+wsy3ZLSRPWSyhjGfSy//+MOWkHM9iSLb9ijEq5U5Tx3yZ8pnlFbQmoUPOUGoTXEOAs22EjGS1vG8aCi6OV65AOlN7EwqIGKFo4pL2anXFdnqaJePWGFPSz6NQm8CP5YbTOy4uqlt+o3oX3KTLA/vwCIOYqzA==</air:FareRuleKey>
          <air:Brand Key="KUzkmhBAAA/BgEomMDAAAA==" BrandID="192563"/>
        </air:FareInfo>
        <air:FareInfo Key="KUzkmhBAAA/Bx2nmMDAAAA==" FareBasis="KBD3M" PassengerTypeCode="ADT" Origin="CCU" Destination="DAC" EffectiveDate="2019-01-20T22:04:00.000+06:00" DepartureDate="2019-04-30" Amount="BDT3768" NegotiatedFare="false" NotValidAfter="2019-06-28">
          <air:BaggageAllowance>
            <air:MaxWeight Value="20" Unit="Kilograms"/>
          </air:BaggageAllowance>
          <air:FareRuleKey FareInfoRef="KUzkmhBAAA/Bx2nmMDAAAA==" ProviderCode="1G">gws-eJxNTkEOwkAIfEwz92G7Rr3tlm01MXLRHnrx/8+QpTWRBGZgyEApJVGulMTyHwM+w3SDrQoYkmerinwikb3ZQPKCx9TGJ8Igj/S5hbajxJbKnBywyMKQNvM4qurajcLWUdDPolMf4Efmu1Or7V1f0s/6Ig+JZ/iXX6IHKhE=</air:FareRuleKey>
          <air:Brand Key="KUzkmhBAAA/BiEomMDAAAA==" BrandFound="false"/>
        </air:FareInfo>
        <air:FareInfo Key="KUzkmhBAAA/Bj4nmMDAAAA==" FareBasis="UEPP" PassengerTypeCode="ADT" Origin="IDR" Destination="CCU" EffectiveDate="2019-01-20T22:04:00.000+06:00" DepartureDate="2019-04-30" Amount="BDT10355" NegotiatedFare="false" NotValidBefore="2019-04-30" NotValidAfter="2019-04-30">
          <air:FareSurcharge Key="KUzkmhBAAA/By4nmMDAAAA==" Type="Other" Amount="NUC4.24"/>
          <air:FareSurcharge Key="KUzkmhBAAA/Bz4nmMDAAAA==" Type="Other" Amount="NUC4.24"/>
          <air:BaggageAllowance>
            <air:MaxWeight Value="20" Unit="Kilograms"/>
          </air:BaggageAllowance>
          <air:FareRuleKey FareInfoRef="KUzkmhBAAA/Bj4nmMDAAAA==" ProviderCode="1G">gws-eJxNTssKwzAM+5iiu+0mZL2lpAnrJZSxDHrZ/3/GlKyDGWzJll8xRhNdRE3iv014T+uO2hJQYfSUGlT9EjAzO8GRjJaPA2OBm4XlOqQvam+SIsUIKFZkSGelXXHfHtTUnPNEUfSz6JQT+JF8J63r9hQz5jcxr+F1iRLAPz8idCrO</air:FareRuleKey>
          <air:Brand Key="KUzkmhBAAA/BkEomMDAAAA==" BrandID="192563"/>
        </air:FareInfo>
        <air:FareInfo Key="KUzkmhBAAA/Br4nmMDAAAA==" FareBasis="KBD3M" PassengerTypeCode="ADT" Origin="CCU" Destination="DAC" EffectiveDate="2019-01-20T22:04:00.000+06:00" DepartureDate="2019-05-01" Amount="BDT3751" NegotiatedFare="false" NotValidAfter="2019-06-28">
          <air:BaggageAllowance>
            <air:MaxWeight Value="20" Unit="Kilograms"/>
          </air:BaggageAllowance>
          <air:FareRuleKey FareInfoRef="KUzkmhBAAA/Br4nmMDAAAA==" ProviderCode="1G">gws-eJxNTkEOg0AIfIyZ+7DV2N52ZdUmTbm0Hrz0/88oizYpCczAkIGcc6LcKIn5Pzp8ummFbQoYkmctin4g0Xuzg+QVj6lengiDgeJzC+1AiS2VOTlgkYUh7eZxVtWtGYWto6CdRaM+wI/Md6dW6ru8pJ31RZ4SR/iXX6GMKhA=</air:FareRuleKey>
          <air:Brand Key="KUzkmhBAAA/BmEomMDAAAA==" BrandFound="false"/>
        </air:FareInfo>

          
		 
		   
			
		  <air:BookingInfo BookingCode="K" BookingCount="4" CabinClass="Economy" FareInfoRef="KUzkmhBAAA/BD1nmMDAAAA==" SegmentRef="KUzkmhBAAA/Bu0nmMDAAAA=="/>
          <air:BookingInfo BookingCode="U" BookingCount="9" CabinClass="Economy" FareInfoRef="KUzkmhBAAA/B11nmMDAAAA==" SegmentRef="KUzkmhBAAA/Bw0nmMDAAAA=="/>
          <air:BookingInfo BookingCode="U" BookingCount="9" CabinClass="Economy" FareInfoRef="KUzkmhBAAA/B11nmMDAAAA==" SegmentRef="KUzkmhBAAA/By0nmMDAAAA=="/>
          <air:BookingInfo BookingCode="U" BookingCount="9" CabinClass="Economy" FareInfoRef="KUzkmhBAAA/Bp2nmMDAAAA==" SegmentRef="KUzkmhBAAA/B00nmMDAAAA=="/>
          <air:BookingInfo BookingCode="U" BookingCount="9" CabinClass="Economy" FareInfoRef="KUzkmhBAAA/Bp2nmMDAAAA==" SegmentRef="KUzkmhBAAA/B20nmMDAAAA=="/>
          <air:BookingInfo BookingCode="K" BookingCount="4" CabinClass="Economy" FareInfoRef="KUzkmhBAAA/Bx2nmMDAAAA==" SegmentRef="KUzkmhBAAA/B40nmMDAAAA=="/>
			
         <air:FareCalc>DAC BG CCU 45.00KBD3M AI X/BOM Q4.24 AI IDR Q4.24 115.97UEPP AI X/DEL Q4.24 AI CCU Q4.24 106.77UEPP BG DAC 45.00KBD3M NUC329.70END ROE1.0</air:FareCalc>
          <air:PassengerType Code="ADT"/>
        
         
          <air:BaggageAllowances>
            <air:BaggageAllowanceInfo Carrier="BG" Destination="JSR" Origin="DAC" TravelerType="ADT">
              <air:URLInfo>
                <air:URL>MYTRIPANDMORE.COM/BAGGAGEDETAILSQF.BAGG</air:URL>
              </air:URLInfo>
              <air:TextInfo>
                <air:Text>2P</air:Text>
                <air:Text>BAGGAGE DISCOUNTS MAY APPLY BASED ON FREQUENT FLYER STATUS/ ONLINE CHECKIN/FORM OF PAYMENT/MILITARY/ETC.</air:Text>
              </air:TextInfo>
              <air:BagDetails ApplicableBags="1stChecked">
                <air:BaggageRestriction>
                  <air:TextInfo>
                    <air:Text>BAGGAGE CHARGES DATA NOT AVAILABLE</air:Text>
                  </air:TextInfo>
                </air:BaggageRestriction>
              </air:BagDetails>
              <air:BagDetails ApplicableBags="2ndChecked">
                <air:BaggageRestriction>
                  <air:TextInfo>
                    <air:Text>BAGGAGE CHARGES DATA NOT AVAILABLE</air:Text>
                  </air:TextInfo>
                </air:BaggageRestriction>
              </air:BagDetails>
            </air:BaggageAllowanceInfo>
            <air:CarryOnAllowanceInfo Carrier="BG" Destination="IDR" Origin="DAC">
              <air:URLInfo />
              <air:TextInfo>
                <air:Text>CARRY ON ALLOWANCE DATA NOT AVAILABLE</air:Text>
              </air:TextInfo>
            </air:CarryOnAllowanceInfo>
            <air:EmbargoInfo Carrier="BG" Destination="JSR" Origin="DAC">
              <air:URLInfo>
                <air:URL>MYTRIPANDMORE.COM/BAGGAGEDETAILSQF.BAGG</air:URL>
              </air:URLInfo>
            </air:EmbargoInfo>
          </air:BaggageAllowances>
        </air:AirPricingInfo>
      </air:AirPricingSolution>
      <com:ActionStatus xmlns:com="http://www.travelport.com/schema/common_v29_0" ProviderCode="1G" TicketDate="T" Type="ACTIVE" />
    </univ:AirCreateReservationReq>
  </soapenv:Body>
</soapenv:Envelope>
EOM;

$file = "003-".$PROVIDER."_FlightBookReq.xml"; // file name to save the request xml for test only(if you want to save the request/response)
prettyPrint($message,$file); //Calling the Pretty Print function

//
// Run the request
//

$auth = base64_encode("$CREDENTIALS");
$soap_do = curl_init("https://americas.universal-api.travelport.com/B2BGateway/connect/uAPI/AirService");
/*("https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");*/
$header = array(
"Content-Type: text/xml;charset=UTF-8",
"Accept-Encoding: gzip,deflate",
"Cache-Control: no-cache",
"Pragma: no-cache",
"SOAPAction: \"\"",
"Authorization: Basic $auth",
"Content-length: ".strlen($message),
);
//curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 30);
//curl_setopt($soap_do, CURLOPT_TIMEOUT, 30);
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($soap_do, CURLOPT_POST, true );
curl_setopt($soap_do, CURLOPT_POSTFIELDS, $message);
curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true);
curl_setopt($soap_do, CURLOPT_ENCODING, '');
$return = curl_exec($soap_do);
curl_close($soap_do);

$file = "001-".$PROVIDER."_FlightBookRsp.xml"; // file name to save the response xml for test only(if you want to save the request/response)
$content = prettyPrint($return,$file);
parseDetailOutput($content);

function prettyPrint($result,$file){
	$dom = new DOMDocument;
	$dom->preserveWhiteSpace = false;
	$dom->loadXML($result);
	$dom->formatOutput = true;
	//call function to write request/response in file
	outputWriter($file,$dom->saveXML());
	return $dom->saveXML();
}
function outputWriter($file,$content){
	file_put_contents($file, $content); // Write request/response and save them in the File
}

//Parse the previous response to get the values to populate Request xml
function parseDetailOutput($content){
	//$hotelDetailRsp = file_get_contents('002_HotelDetailRsp.xml'); // Parsing the Hotel Detail Response xml 
	$hotelDetailRsp = $content; //use this if response is not saved anywhere else use above variable
	$xml = simplexml_load_String("$hotelDetailRsp", null, null, 'SOAP', true);
	if(!$xml)
	{
		header("Location: http://LocationOfErrorPage/projects/Hotel/error.php"); // Use the location of the error page
	}

	$Results = $xml->children('SOAP',true);
	
	foreach($Results->children('SOAP',true) as $fault){
		if(strcmp($fault->getName(),'Fault') == 0){
			//trigger_error("Error occurred request processing!", E_USER_ERROR);
			header("Location: http://LocationOfErrorPage/projects/Hotel/error.php"); // Use the location of the error page
		}
	}

	foreach($Results->children('flight',true) as $nodes){
		foreach($nodes->children('flight',true) as $hsr){
			if(strcmp($hsr->getName(),'RequestedHotelDetails') == 0){
				foreach($hsr->children('flight',true) as $hp){					
					if(strcmp($hp->getName(),'FlightProperty') == 0){
						foreach($hp->attributes() as $a => $b	){
								$GLOBALS[$a] = "$b";
						}
						$COUNT = 0;
						$Address = 'Address';
						foreach($hp->children('flight',true) as $pa){							
							if(strcmp($pa->getName(),'PropertyAddress') == 0){								
								foreach($pa->children('flight',true) as $ha){														
									if(strcmp($ha->getName(),'Address') == 0){
										$GLOBALS[$Address.$COUNT++] = $ha[0];								
									}
								}
							}							
						}
					}
				}
				foreach($hsr->children('flight',true) as $hp){
					if(strcmp($hp->getName(),'FlightRateDetail') == 0){
						foreach($hp->attributes() as $a => $b	){
								$GLOBALS[$a] = "$b";
						}
						break;
					}
									
				}
			}
			break;
		}
	}
}

//call function to write output in a file

//	
// Official PHP CURL manual; http://php.net/manual/en/book.curl.php
//
?>
`

**Comment by vivekjyotipramanik** [comment]
Hi  @imon91,

Please share the full error message. The screenshot is not showing the full error message. Thanks.

**Comment by imon91** [comment]
Hello vivekjyotipramanik
Solved it
Thanks

**Comment by akv0204** [comment]
Hello Vivek,
Could you please enable robotic sign-on for following credentials -
ID:  Universal API/uAPI8383229630-d0cbb10b
Target Branch: P7039096
Provider: 1G

--
Thanks & Regards,
Ajay

**Comment by NirandaG** [comment]
Hi,
This has been created. Could you please try now?
Rgds,
Niranda
