### ISSUE TITLE
Error unmarshalling message body: xml:deserialize: improper date format: 

### ISSUE THREAD

**Issue by imon91** [Travelport/travelport-uapi-tutorial-php#194]
Hello 
I have faced this problem when I am trying to book for one way path
My request Soap Is `<?xml version="1.0"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header />
  <soapenv:Body>
    <univ:AirCreateReservationReq xmlns:univ="http://www.travelport.com/schema/universal_v29_0" AuthorizedBy="user" RetainReservation="Both" TargetBranch="P3018376" TraceId="trace">
      <com:BillingPointOfSaleInfo xmlns:com="http://www.travelport.com/schema/common_v29_0" OriginApplication="UAPI" />
      <com:BookingTraveler xmlns:com="http://www.travelport.com/schema/common_v29_0" DOB="1985-01-05" Gender="M" Key="GZVzaidB0BKADRH8dKAAAA==" TravelerType="ADT">
        <com:BookingTravelerName First="Tasnim" Last="test" Prefix="mr" />
        <com:DeliveryInfo>
          <com:ShippingAddress>
            <com:AddressName>Bangladesh</com:AddressName>
            <com:Street>new palasia</com:Street>
            <com:City>indore</com:City>
            <com:State>mp</com:State>
            <com:PostalCode>452001</com:PostalCode>
            <com:Country>BD</com:Country>
          </com:ShippingAddress>
        </com:DeliveryInfo>
        <com:PhoneNumber CountryCode="880" Location="DAC" Number="1676-224087" />
        <com:Email EmailID="tasnim@gmail.com" Type="Home" />
        <com:SSR Carrier="BG" FreeText="P/BD/F1234567/BD/05Jan85/M/13Dec14/Imon/Tasnim" SegmentRef="GZVzaidB0BKADRH8dKAAAA==" Status="HK" Type="DOCS" />
        <com:Address>
          <com:AddressName>indore</com:AddressName>
          <com:Street>new palasia</com:Street>
          <com:City>indore</com:City>
          <com:State>Dhaka</com:State>
          <com:PostalCode>121</com:PostalCode>
          <com:Country>BD</com:Country>
        </com:Address>
      </com:BookingTraveler>
       <air:AirPricingSolution xmlns:air="http://www.travelport.com/schema/air_v29_0" Key="GZVzaidB0BKAFRH8dKAAAA====" TotalPrice="BDT2700" BasePrice="BDT2171" ApproximateTotalPrice="BDT2700" ApproximateBasePrice="BDT2171" Taxes="BDT529" ApproximateTaxes="BDT529">
 <air:AirSegment Key="GZVzaidB0BKADRH8dKAAAA==" Group="0" Carrier="BG" FlightNumber="493" Origin="DAC" Destination="SPD" DepartureTime="2019-02-28T10:45:00.000+06:00" ArrivalTime="2019-02-28T11:40:00.000+06:00"  ETicketability="Yes" Equipment="DH8" ChangeOfPlane="false" ParticipantLevel="Secure Sell"  OptionalServicesIndicator="false" ProviderCode="1G" />
<air:AirPricingInfo Key="GZVzaidB0BKAHRH8dKAAAA====" TotalPrice="BDT2700" BasePrice="BDT2171" ApproximateTotalPrice="BDT2700" ApproximateBasePrice="BDT2171"  Taxes="BDT529"  LatestTicketingTime="2019-02-28T23:59:00.000+06:00" PricingMethod="GuaranteedUsingAirlinePrivateFare" Refundable="true" ETicketability="Yes" PlatingCarrier="BG" ProviderCode="1G" >
<air:FareInfo Key="GZVzaidB0BKALRH8dKAAAA==" FareBasis="GPROMO" PassengerTypeCode="ADT" Origin="DAC" Destination="SPD" EffectiveDate="2019-02-02T12:06:00.000+06:00" DepartureDate="2019-02-28" Amount="BDT2171" NegotiatedFare="false" NotValidAfter=""> 
<air:FareRuleKey FareInfoRef="GZVzaidB0BKALRH8dKAAAA==" ProviderCode="1G">6UUVoSldxwhtHLsGCpQtPsbKj3F8T9EyxsqPcXxP0TLGyo9xfE/RMjJs02vwFm2edu+Ktngmb9Ldl7wUHIq2YLzC9kE4VhUjcR6jos7miHsHDNWnNYExQ2AUdVY1xwqBppDnGM8t6Q+WyjsrTg8Vdk0MVFefcbC8//LCXtf8z7lSJnRX+7ZwMLtyzMuCE9icGjIzwdRXx7HPOvXkrT+ckNQ932Kot7TUY9r9qfPXCw6Q3plrAHfM7GMiLjRjc+XKJHXyDAS6XXKP8q+uBG/JRmRiEvRbxR4GofoIku5HF2Pq/20RpEmAXlby9IE1rxlSqufOCYxTojcOvp9697VCNs+/gL+/ZSyUGJI8QFeMrU+AdcY0m0a4yk4nKb2G5mOFq+l7n45sTSHXV4Zu5uZY74q+cJFUBzrily5qxZ3qLwOXLmrFneovA5cuasWd6i8Dly5qxZ3qLwOXLmrFneovA3N5jV9Rrzq8txHW6jzw2UbAQJCzzE4cyQZiBMwpA/ZdPj78e6noBQpLAQw84BUM6Hwa4JsFkyGM</air:FareRuleKey>
<air:Brand Key="GZVzaidB0BKALRH8dKAAAA==" BrandID=""/>
</air:FareInfo>
<air:BookingInfo BookingCode="G" FareInfoRef="GZVzaidB0BKALRH8dKAAAA==" SegmentRef="GZVzaidB0BKADRH8dKAAAA=="/>
<air:FareCalc>DAC BG SPD 2171GPROMO BDT2171END</air:FareCalc>
<air:PassengerType Code="ADT"/>
<air:BaggageAllowances>
<air:BaggageAllowanceInfo Carrier="BG" Destination="SPD" Origin="DAC" TravelerType="ADT">
<air:URLInfo>
<air:URL>VIEWTRIP.TRAVELPORT.COM/BAGGAGEPOLICY/BG</air:URL>
</air:URLInfo>
<air:TextInfo>
<air:Text>20K</air:Text>
<air:Text>BAGGAGE DISCOUNTS MAY APPLY BASED ON FREQUENT FLYER STATUS/ ONLINE CHECKIN/FORM OF PAYMENT/MILITARY/ETC.</air:Text>
</air:TextInfo>
<air:BagDetails ApplicableBags="1stChecked">
<air:BaggageRestriction>
<air:TextInfo><
air:Text>CHGS MAY APPLY IF BAGS EXCEED TTL WT ALLOWANCE</air:Text>
</air:TextInfo>
</air:BaggageRestriction>
</air:BagDetails>
<air:BagDetails ApplicableBags="2ndChecked">
<air:BaggageRestriction>
<air:TextInfo>
<air:Text>CHGS MAY APPLY IF BAGS EXCEED TTL WT ALLOWANCE</air:Text>
</air:TextInfo>
</air:BaggageRestriction>
</air:BagDetails>
</air:BaggageAllowanceInfo> 
<air:CarryOnAllowanceInfo Carrier="BG" Destination="SPD" Origin="DAC">
 <air:URLInfo />
<air:TextInfo>
<air:Text>7K</air:Text>
</air:TextInfo>
</air:CarryOnAllowanceInfo>
</air:BaggageAllowances>
</air:AirPricingInfo>
</air:AirPricingSolution>
     <com:ActionStatus xmlns:com="http://www.travelport.com/schema/common_v29_0" ProviderCode="1G" TicketDate="T" Type="ACTIVE" />
    </univ:AirCreateReservationReq>
  </soapenv:Body>
</soapenv:Envelope>`

**Comment by basheerOct** [comment]
The error is self explanatory. Please use the following format for date: `yyyy-mm-dd`.
