### ISSUE TITLE
NO VALID FARE - EXCEEDS 25M SURCHARGE BAND

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#198]
Hello,

When we search for pricing request then we get thie error

NO VALID FARE - EXCEEDS 25M SURCHARGE BAND

i am attaching the request and response xml

Please provide us the reason

Thanks

[MTkwMzE1MDMxNTUwcG0=AirPricingInfoRequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2971746/MTkwMzE1MDMxNTUwcG0.AirPricingInfoRequest.txt)
[MTkwMzE1MDMxNTUwcG0=AirPricingInfoResponse.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/2971748/MTkwMzE1MDMxNTUwcG0.AirPricingInfoResponse.txt)

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

Looks like this a issue with fare. Please raise a ticket in https://my.travelport.com for this issue. Thanks.

**Comment by Alex0084** [comment]
Hello Vivek,

We have issue with fare in some flight, so you can tell how we can omit these result from search result

Thanks
[MTkwNDA1MDgwMzE2YW0=AirPricingInfoRequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3046908/MTkwNDA1MDgwMzE2YW0.AirPricingInfoRequest.txt)
[MTkwNDA1MDgwMzE2YW0=AirPricingInfoResponse.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3046909/MTkwNDA1MDgwMzE2YW0.AirPricingInfoResponse.txt)

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

You are using a very old version of UAPI. Please use the latest version which is version 47, to get the best results. Please note that, we retire UAPI schema of older version after 3 years of the version release date. The error in the response is a valid response when there is no fare available for the itinerary. It is quite common on preproduction system as test data is limited. If you are facing the same issue in Production, Please raise a MyTravelport ticket. Thanks.
