### ISSUE TITLE
SYSTEM ERROR | Phone application failed: CHECK FORMAT|FINISH OR IGNORE TRANSACTION/MODIFY BOOKING

### ISSUE THREAD

**Issue by engrashid** [Travelport/travelport-uapi-tutorial-php#201]
Hi  please check Whats wrong with my request below ,

[universalAirCreateReservationRsp_20190423_162738.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3107076/universalAirCreateReservationRsp_20190423_162738.txt)
[universalAirCreateReservationReq_20190423_162736.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3107077/universalAirCreateReservationReq_20190423_162736.txt)
[airpriceRes_20190423_162736.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3107078/airpriceRes_20190423_162736.txt)
[airpriceReq_20190423_162733.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3107079/airpriceReq_20190423_162733.txt)
[airLowFareSearchRsp_20190423_162515.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3107080/airLowFareSearchRsp_20190423_162515.txt)
[airLowFareSearchReq_20190423_162504.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3107081/airLowFareSearchReq_20190423_162504.txt)

**Comment by vivekjyotipramanik** [comment]
Hi engrashid,

The number provide is too long and is failing validation. If the number is say, "3033333333", Please provide the first 3 numbers in AreaCode field and the rest of the numbers in the Number field. Thanks.

**Comment by engrashid** [comment]
Hi @vivekjyotipramanik , 

Thanks that explanation helped . CountryCode accepts international dial code and location accepts city or airport code . I used wrong value for those fields .
