### ISSUE TITLE
i can't find any way to book a paid baggage

### ISSUE THREAD

**Issue by by-tech** [Travelport/travelport-uapi-tutorial-php#203]
Hi,

i can't find any way to book a paid baggage, the airPricing response 
those not containe any information about baggage.

my questions :

1-how display all information about baggages weight , size  , price...

2-how to book baggage if not found in airPricing response.

please see attached log file.
[log (1).zip](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3167618/log.1.zip)

**Comment by vivekjyotipramanik** [comment]
Hi sgatrip,

We can use merchandising to book optional services like Paid Baggage, Paid Seats etc. Please find below the link with all the details. 

https://support.travelport.com/webhelp/uapi/uapi.htm#Standalone_Merchandising/Air_Merchandising.htm%3FTocPath%3DAir%7CAir%2520Merchandising%7C_____0

Regarding baggage information, it depends on the carrier/airline. Please find below the link with the details.Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Air/Air_Pricing/Air_Pricing.htm?Highlight=Dimension
