### ISSUE TITLE
The current session has expired. Please restart your session

### ISSUE THREAD

**Issue by belaassal** [Travelport/travelport-uapi-tutorial-php#206]
Hi,
when i try to make AirCreateReservation Request i get this erreur

RS : 
<SOAP:Envelope><SOAP:Body><SOAP:Fault><faultcode>Server.Business</faultcode><faultstring>The current session has expired. Please restart your session</faultstring><detail><common_v42_0:ErrorInfo><common_v42_0:Code>14022</common_v42_0:Code><common_v42_0:Service>ACH</common_v42_0:Service><common_v42_0:Type>Business</common_v42_0:Type><common_v42_0:Description>The current session has expired. Please restart your session</common_v42_0:Description><common_v42_0:TransactionId>6BCB8C470A07643B8E7E27E845B56F41</common_v42_0:TransactionId></common_v42_0:ErrorInfo></detail></SOAP:Fault></SOAP:Body></SOAP:Envelope>

Question : How Can i bypass this erreur.

UserID : Universal API/uAPI2505205233-36193653
TargetBranch : P7099851

Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi belaassal,

Could you please share the request xml. I believe you are using some kind of TraceId which is expired. Thanks.

**Comment by belaassal** [comment]
Hi vivekjyotipramanik,

`<SOAP:Envelope>
    <SOAP:Body>
        <AirCreateReservationReq TargetBranch="P7099851" LanguageCode="FR-FR" ProviderCode="ACH" RetainReservation="Both">
            <BillingPointOfSaleInfo OriginApplication="UAPI" />
            <BookingTraveler Key="5d0929bb78f69" TravelerType="ADT" Age="28" DOB="1990-09-29" Gender="M" Nationality="FR">
                <BookingTravelerName Prefix="Mr" First="PrenomA" Last="NomA" />
                <PhoneNumber Location="FRA" CountryCode="33" Number="0187650093" />
                <Email EmailID="info@bladia.com" /><Address>
                    <AddressName>53 avenue de l'europe</AddressName>
                    <Street>53 avenue de l'europe</Street>
                    <City>Amiens</City>
                    <PostalCode>80000</PostalCode>
                    <Country>FR</Country>
                </Address></BookingTraveler>
            <FormOfPayment Type="Credit" Key="1">
                <CreditCard Type="VI" Number="XXXXXXXXXXXXXXXXXX" ExpDate="XXXX-04" CVV="XXX" />
            </FormOfPayment>
            <AirPricingSolution Key="/iKdrt4R2BKAqnECAAAAAA==" TotalPrice="MAD3139.00" BasePrice="MAD3139.00" ApproximateTotalPrice="MAD3139.00" ApproximateBasePrice="MAD3139.00">
                <AirSegment Key="/iKdrt4R2BKAonECAAAAAA==" OptionalServicesIndicator="true" AvailabilityDisplayType="" Group="0" Carrier="FR" FlightNumber="7755" Origin="TNG" Destination="MAD" DepartureTime="2019-09-29T15:50:00.000+01:00" ArrivalTime="2019-09-29T18:20:00.000+02:00" FlightTime="90" TravelTime="90" SupplierCode="FR" ProviderCode="ACH" HostTokenRef="/iKdrt4R2BKApnECAAAAAA==" ClassOfService="Y"></AirSegment>
                <AirPricingInfo PricingMethod="Auto" Key="/iKdrt4R2BKArnECAAAAAA==" TotalPrice="MAD3139.00" BasePrice="MAD3139.00" ApproximateTotalPrice="MAD3139.00" ApproximateBasePrice="MAD3139.00" ProviderCode="ACH">
                    <FareInfo Amount="MAD3139.00" DepartureDate="2019-09-29" EffectiveDate="2019-06-18T19:12:45.664+01:00" Destination="MAD" Origin="TNG" PassengerTypeCode="ADT" FareBasis="S4HIGH" Key="/iKdrt4R2BKAsnECAAAAAA==">
                        <FareRuleKey FareInfoRef="/iKdrt4R2BKAsnECAAAAAA==" ProviderCode="ACH">H4sIAAAAAAAAAO1YT28TRxTfQCD/IAkkqOqh0twKUrARokCFSmsnOFgyEMVupXIb7z6vh6x3lpnZxO6haj8Gh36D3nvvpfd+gB56bj9Ab31vZr27TlzRjdRWSOVAyOzMe7/5vd/7M3z/u3dJK++JL0c1o/gxRIlUpqYlr4WBrnGhIhFDbSi1qY1kAFGN+8NaQ6i2wXXF1eRACV/EYTseSM/9WbjgLXe8KwOugFY7Qhvj3ei84se8nhoR1RtK8QktP+p4VwUa6knDoxbuN94nHYRSL6DUEUododQzKHWCUrdQ6gil3i4fR3tbMjFCxjzqgjoWPjjvmyXvmeP3T23UJRDtiiBe/JUp9HMt6e3SP5sK+FEgT2L92vvaW0CCEmQODuE1kWS8/Yo+D7LTKWhDFtSIEwiiNHEh6cpU+Xib6+7yEY/Detco/IKbNhRM/adCQUCgLo8T1MIW7a4RVbU8UONvf/7gzU/8u4veQttb1OIrGCcU6ZNF+hsP3a8moFamjUIxax1vnSsljnmE6iIbxntYkZKO9KccbAaQcGVSBZk1uh/6uJqv73ED9tLIRSC0L9PYZFo23qcVPe/NGqAgkPwPYQAKYv8cum6Vj1t7AreFDbfbeA8q2ssOEjUjro7AlI19VtHYs1MW0Op6DKE0AkkNCHrG7PXZ1V20kH1ZVmkETvlVw3yYnSRWTMKfjA3EGsOuq7PcO2gUxx9Z+VdU8lRzhZIvdLw1H7/vytjA2GT3vRJlG3MOxonxFtuNXsN4F5819mxZ2CqWes/3E8LzqHpm5bopQCGCNe5bjZaCcG1GpL0C7aYC3ZTyaA+0CEsHto3wMfJ2OeZGqtK39TQJFQ+gEUXyJCsoHe+9bPVwnsFxghwsHUKYRpiU3sKXxrvcvfe0vf/UXv2jyl2JlmcisegXAM9EhSJwoXWYcY4OH1dzeDoNCs+X3uIZGUZXCY8n3SE6es5HeS3SaC+CLyAOpGrHUxqvOFRd8JH0OeAT+6e6XGYSoMC/iUAyuXyugRJOVy+KjVkDVCR4EAjXKltAJh9XNTlzngoAJ7VxVK+rJU/PUWabPAx56HQ7tYSmb/ARwdft2I/SAIJ23OQai+WTqpjnmaHBoH/Kr65uex58omWjr3gcuKLriKkavOasAbS5MrBTDC4b7+Pz4KSjJAJXdKgL0WiRTUNrxSry0DpXt7SHMc20jESAPWcKOtPveUDnyhWnVFBVuWfCvz2dP3eHXIWg95VMMaX3zjl6lq24GRAO+CRLweqN8aB8nASlIRxBbIiTUtS2dZqQOQgcDl3+ZmgK3kW7pSdC9Qv25ljBTp0XvAfV+6NVotoYj3+5/9sfWKxfeqs2X1p42eClt5kmGqKoWVracEtYj4VPba/jLdkT7b38bWHH6450w1/JQnuP+Hhg5+XzQ7Y6LOoz0ruu0z61A2Q9Jx0HGPq5PDOaP6zmrZubLdwtkqC44tjJk2EpxEuIoTQBbBaQnqejPqjprIfrPWGiadOfA7IiJQdTMAXGi9hy46KPrtB8WZbjUqqiElHzQNyt2Duxm88MGyvuFYbZYLytkipw8ImA07NksTR7JGZ5nI0+jEK8+uMPK1jEmQPAhGZyQJNZwETMqBmrgMo7OxFmyA4nPEZYH2q2D/QOj1gP1EgzFBzDCui6JFlgu/Sqwv5Qm9pPuNYQh6A0G6XaMH8I/tFt9CFjuqU1AegDFMMXYmwIBsNfWV9yFWAGWgtMKkav2UjygB0LbneMZF9EaCFJmCQDJ0JDbr+uQGidAhtg66Y90cRiakUiHBpGBVvvMCNG9APLmAF3nRwvo/DimiKbyCvwPjpDbb1CzTEjrU3MT1r1XTlkt1mC1CMKRVMubSqYc+RbonJyqF2ge+4ejczwMei6A4xQplYJQizj22gUywM5rLEXMUvjVGO43IxMvokTZHXCio0MIqBCSvGlz/vyGFRsV3p8vMNOhsIf0sfyvTD+wUjEqF5l8RKFtdXVDhKKL1l2EKXaSeh/Df3HGpoJCYmJZYMD+mR37xyF7ioYEJz+dljXIDpkhHWBG3azjOOYi4gjFcJMbtk7YP+TCn9jzYzDd1K0zRQfOICxL0T7b2g2oybXKXrJGMbb3RwoADrjqLrF0oRucO8OQ/xWQ33A0g727hptBNhbAjbIRDf9HyWSM59NDh9Z+Edyw96qh0uDQvlO+HTQKt867091Hpy9JYaEjAZ8QqsZ/Tbyf1PxZGEmnjmq2SifzQN2OhFw3hyJdPSWPNg5mwSWzhbXpqe4f8Ru4nEcvfAwWs4SQt+yuOiRnZHhkuGcWf/rN2/e+d4xzqcfz04/3tj+V8z2vGSiWfvM9jMLydxtuPYnV1gKLmIYAAA=</FareRuleKey>
                    </FareInfo>
                    <BookingInfo BookingCode="Y" CabinClass="Economy" FareInfoRef="/iKdrt4R2BKAsnECAAAAAA==" SegmentRef="/iKdrt4R2BKAonECAAAAAA==" HostTokenRef="/iKdrt4R2BKApnECAAAAAA==" />
                    <PassengerType Code="ADT" Age="28" BookingTravelerRef="5d0929bb78f69" />
                </AirPricingInfo>
                <HostToken Key="/iKdrt4R2BKApnECAAAAAA==">NNSFR{IS###}MAD{CC###ET}ACHSDv01LPD1:56daedb1-644c-4b77-bb57-a5fd423e8d32 </HostToken>
            </AirPricingSolution>
            <ActionStatus Type="ACTIVE" ProviderCode="ACH" />
            <Payment Key="2" Type="Itinerary" FormOfPaymentRef="1" Amount="MAD3139.00" />
        </AirCreateReservationReq>
    </SOAP:Body>
</SOAP:Envelope>
`

**Comment by vivekjyotipramanik** [comment]
Hi belaassal,

Do you have access to ACH. Are you using Production environemnt. If yes, Please raise a ticket in My.Travelport.com and we will pick it up from there. Thanks.

**Comment by belaassal** [comment]
NO ....... i am using Development environment .
for ACH a can get Availability and Price ....but i am not sure about booking(AirCreateReservation)

**Comment by vivekjyotipramanik** [comment]
Hi belaassal,

Could you please share all the shop, price request and response. Another reason of this issue could be the HostToken mismatch or the hostToken already expired. Generally the token stay alive for around 5 mins. Thanks.

**Comment by belaassal** [comment]
Hi vivekjyotipramanik,

her is the log of all Request made and response.
[log.zip](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3307324/log.zip)

**Comment by vivekjyotipramanik** [comment]
Hi belaassal,

Could you please run the process again and make sure that the create request run within 5 mins of the price response. Thanks.

**Comment by belaassal** [comment]
Hi vivekjyotipramanik,

as suggested i made the create request within 5min of price request  but i still get the same error :
[log.zip](https://github.com/Travelport/travelport-uapi-tutorial-php/files/3307415/log.zip)


Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi belaassal,

Could you please raise a ticket on My.Travelport.com. We will pick it up from there. Thanks.

**Comment by by-tech** [comment]
Dear vivekjyotipramanik

Thanks to check CS0159781 ticket on My.Travelport.com

ACH create booking is not possible...thanks to help

Regards
