### ISSUE TITLE
No fares found for the specified request

### ISSUE THREAD

**Issue by kiran-subedi34** [Travelport/travelport-uapi-tutorial-php#21]
Hello
 I get the error like UNABLE TO FARE QUOTE. I have used the code that is provided on the git and changes the credentials where need to change but I get the error as : 
<?xml version="1.0"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Business</faultcode>
      <faultstring>UNABLE TO FARE QUOTE</faultstring>
      <detail>
        <common_v33_0:ErrorInfo xmlns:common_v33_0="http://www.travelport.com/schema/common_v33_0">
          <common_v33_0:Code>4413</common_v33_0:Code>
          <common_v33_0:Service>AIRSVC</common_v33_0:Service>
          <common_v33_0:Type>Business</common_v33_0:Type>
          <common_v33_0:Description>No fares found for the specified request.</common_v33_0:Description>
          <common_v33_0:TransactionId>E313D1310A07643C2144B77E8CBFBA5C</common_v33_0:TransactionId>
          <common_v33_0:TraceId>trace</common_v33_0:TraceId>
        </common_v33_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>

**Comment by vivekjyotipramanik** [comment]
Hi Kiran,

Thank you for your interest in Travelport Universal API. Could you please try with the same date and Airlines in the http://demo.travelportuniversalapi.com/ and please let me know if you are getting the same response in demosite. if yes, then the fare quote is unavailable. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by kiran-subedi34** [comment]
I get the same result in demo site that you  provided i.e http://demo.travelportuniversalapi.com . I didn't know whats the reason behind this. Please help me to get out of this.

**Comment by vivekjyotipramanik** [comment]
Hi Kiran,

I have tried in demosite with MEL-SYD for the Date Aug 24 and it worked fine for me. Could you please try again. Also, Please provide me the request you are trying with. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by kiran-subedi34** [comment]
Hi vivek,

I also get the result. But when I try other data like KTM-DEL then I get  error as UNABLE TO FARE QUOTE but when I tried MEL-SYD I get the result. Is there  limited for search leg or else ? Hope this type of error will not occur on the production.
