### ISSUE TITLE
ReturnBrandIndicator' is not allowed :(

### ISSUE THREAD

**Issue by hasintha** [Travelport/travelport-uapi-tutorial-php#210]
Hello there

according to the [xsd](https://support.travelport.com/webhelp/uapi/uAPI.htm#../Subsystems/Schemas/Content/Schemas/AvailabilitySearchReq.html) ReturnBrandIndicator is avaiable as an attribute of AvailabilitySearchReq

But alas I'm getting the below error

`Attribute 'ReturnBrandIndicator' is not allowed to appear in element 'air:AvailabilitySearchReq'.`

My request

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq TraceId="trace" AuthorizedBy="user" TargetBranch="$TARGETBRANCH" xmlns:air="http://www.travelport.com/schema/air_v29_0" xmlns:com="http://www.travelport.com/schema/common_v29_0" ReturnBrandIndicator="true" >
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="LGW"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="EDI"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2019-12-31">
            </air:SearchDepTime>            
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="$Provider"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
`

Please help

**Comment by vivekjyotipramanik** [comment]
Hi hasintha,

ReturnBrandIndicator was not allowed in schema v29. Please use latest version of UAPI schema which is v48 and give it a try. Thanks.

**Comment by hasintha** [comment]
Hi Vivek 

Thanks much bro
