### ISSUE TITLE
HotelSearchAvail Coordinates in response missing 

### ISSUE THREAD

**Issue by rehman22** [Travelport/travelport-uapi-tutorial-php#213]
this is request

**Comment by rehman22** [comment]
` 
<HotelSearchAvailabilityReq xmlns="http://www.travelport.com/schema/hotel_v42_0" TraceId="142cac4d-ccd7-4a1b-a1a2-2ca4084c2adf" AuthorizedBy="Travelport" TargetBranch="P3224559">
  <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v42_0" OriginApplication="uAPI" />
  <HotelSearchLocation>
    <HotelLocation Location="KHI" />
  </HotelSearchLocation>
  <HotelSearchModifiers NumberOfAdults="1" NumberOfRooms="1" AvailableHotelsOnly="true">
    <PermittedProviders xmlns="http://www.travelport.com/schema/common_v42_0">
      <Provider Code="1G" />
    </PermittedProviders>
    <NumberOfChildren Count="1">
      <Age>10</Age>
    </NumberOfChildren>
  </HotelSearchModifiers>
  <HotelStay>
    <CheckinDate>2019-07-16</CheckinDate>
    <CheckoutDate>2019-07-23</CheckoutDate>
  </HotelStay>
</HotelSearchAvailabilityReq>`




and this is response






`<hotel:HotelSearchAvailabilityRsp TraceId="142cac4d-ccd7-4a1b-a1a2-2ca4084c2adf" TransactionId="D19BA0800A074262C4734BCABBC8BBA6" ResponseTime="5474" xmlns:hotel="http://www.travelport.com/schema/hotel_v42_0" xmlns:common_v42_0="http://www.travelport.com/schema/common_v42_0">
  <common_v42_0:ResponseMessage Code="5244" Type="Warning" ProviderCode="1G">NumberOfChildren modifier is not supported, and has been ignored.</common_v42_0:ResponseMessage>
  <hotel:ReferencePoint>QUAID E AZAM INTERNATIONAL</hotel:ReferencePoint>
  <hotel:HotelSearchResult>
    <common_v42_0:VendorLocation ProviderCode="1G" VendorCode="WV" VendorLocationID="78806" Key="MKQyzuBAAA/BOh+q0SAAAA==" />
    <hotel:HotelProperty HotelChain="WV" HotelCode="78806" HotelLocation="KHI" Name="PEARL CONTINENTAL KARACHI" VendorLocationKey="MKQyzuBAAA/BOh+q0SAAAA==" HotelTransportation="26" ReserveRequirement="Deposit" Availability="Available">
      <hotel:PropertyAddress>
        <hotel:Address>CLUB ROAD</hotel:Address>
      </hotel:PropertyAddress>
      <common_v42_0:Distance Units="KM" Value="10" Direction="SW" />
      <hotel:HotelRating RatingProvider="AAA">
        <hotel:Rating>0</hotel:Rating>
      </hotel:HotelRating>
    </hotel:HotelProperty>
    <hotel:RateInfo MinimumAmount="USD115.00" MinAmountRateChanged="true" MaximumAmount="USD360.00" MaxAmountRateChanged="true" />
  </hotel:HotelSearchResult>
  <hotel:HotelSearchResult>
    <common_v42_0:VendorLocation ProviderCode="1G" VendorCode="MC" VendorLocationID="09807" Key="MKQyzuBAAA/BPh+q0SAAAA==" />
    <hotel:HotelProperty HotelChain="MC" HotelCode="09807" HotelLocation="KHI" Name="KARACHI MARRIOTT HOTEL" VendorLocationKey="MKQyzuBAAA/BPh+q0SAAAA==" HotelTransportation="7" ReserveRequirement="Guarantee" ParticipationLevel="4" Availability="Available">
      <hotel:PropertyAddress>
        <hotel:Address>9 ABDULLAH HAROON RO</hotel:Address>
      </hotel:PropertyAddress>
      <common_v42_0:Distance Units="KM" Value="10" Direction="SW" />
      <hotel:HotelRating RatingProvider="AAA">
        <hotel:Rating>0</hotel:Rating>
      </hotel:HotelRating>
    </hotel:HotelProperty>
    <hotel:RateInfo MinimumAmount="USD106.25" MaximumAmount="USD900.00" />
  </hotel:HotelSearchResult>
  <hotel:HotelSearchResult>
    <common_v42_0:VendorLocation ProviderCode="1G" VendorCode="RA" VendorLocationID="E0264" Key="MKQyzuBAAA/BQh+q0SAAAA==" />
    <hotel:HotelProperty HotelChain="RA" HotelCode="E0264" HotelLocation="KHI" Name="RAMADA KARACHI CREEK" VendorLocationKey="MKQyzuBAAA/BQh+q0SAAAA==" HotelTransportation="7" ReserveRequirement="Other" ParticipationLevel="4" Availability="Available">
      <hotel:PropertyAddress>
        <hotel:Address>ZULFIQAR STREET 1</hotel:Address>
      </hotel:PropertyAddress>
      <common_v42_0:Distance Units="KM" Value="10" Direction="SW" />
      <hotel:HotelRating RatingProvider="AAA">
        <hotel:Rating>0</hotel:Rating>
      </hotel:HotelRating>
    </hotel:HotelProperty>
    <hotel:RateInfo MinimumAmount="PKR17000.00" MinAmountRateChanged="false" MaximumAmount="PKR30000.00" MaxAmountRateChanged="false" />
  </hotel:HotelSearchResult>
  <hotel:HotelSearchResult>
    <common_v42_0:VendorLocation ProviderCode="1G" VendorCode="WV" VendorLocationID="01012" Key="MKQyzuBAAA/BRh+q0SAAAA==" />
    <hotel:HotelProperty HotelChain="WV" HotelCode="01012" HotelLocation="KHI" Name="AVARI TOWERS KARACHI" VendorLocationKey="MKQyzuBAAA/BRh+q0SAAAA==" HotelTransportation="7" ReserveRequirement="Deposit" Availability="Available">
      <hotel:PropertyAddress>
        <hotel:Address>SINDH</hotel:Address>
      </hotel:PropertyAddress>
      <common_v42_0:Distance Units="KM" Value="5" Direction="SW" />
      <hotel:HotelRating RatingProvider="AAA">
        <hotel:Rating>0</hotel:Rating>
      </hotel:HotelRating>
    </hotel:HotelProperty>
    <hotel:RateInfo MinimumAmount="USD175.00" MinAmountRateChanged="true" MaximumAmount="USD1000.00" MaxAmountRateChanged="true" />
  </hotel:HotelSearchResult>
  <hotel:HotelSearchResult>
    <common_v42_0:VendorLocation ProviderCode="1G" VendorCode="MK" VendorLocationID="00752" Key="MKQyzuBAAA/BSh+q0SAAAA==" />
    <hotel:HotelProperty HotelChain="MK" HotelCode="00752" HotelLocation="KHI" Name="MOVENPICK HOTEL KARACHI" VendorLocationKey="MKQyzuBAAA/BSh+q0SAAAA==" HotelTransportation="7" ReserveRequirement="Guarantee" ParticipationLevel="2" Availability="Available">
      <hotel:PropertyAddress>
        <hotel:Address>CLUB RD</hotel:Address>
      </hotel:PropertyAddress>
      <common_v42_0:Distance Units="KM" Value="10" Direction="SW" />
      <hotel:HotelRating RatingProvider="AAA">
        <hotel:Rating>0</hotel:Rating>
      </hotel:HotelRating>
    </hotel:HotelProperty>
    <hotel:RateInfo MinimumAmount="USD90.00" MinAmountRateChanged="false" MaximumAmount="USD685.00" MaxAmountRateChanged="false" />
  </hotel:HotelSearchResult>
  <hotel:HotelSearchResult>
    <common_v42_0:VendorLocation ProviderCode="1G" VendorCode="RA" VendorLocationID="90269" Key="MKQyzuBAAA/BTh+q0SAAAA==" />
    <hotel:HotelProperty HotelChain="RA" HotelCode="90269" HotelLocation="KHI" Name="RAMADA PLAZA KARACHI HOTEL" VendorLocationKey="MKQyzuBAAA/BTh+q0SAAAA==" HotelTransportation="7" ReserveRequirement="Other" ParticipationLevel="4" Availability="Available">
      <hotel:PropertyAddress>
        <hotel:Address>STAR AVENUE</hotel:Address>
      </hotel:PropertyAddress>
      <common_v42_0:Distance Units="KM" Value="8" Direction="W" />
      <hotel:HotelRating RatingProvider="AAA">
        <hotel:Rating>0</hotel:Rating>
      </hotel:HotelRating>
    </hotel:HotelProperty>
    <hotel:RateInfo MinimumAmount="PKR17999.00" MinAmountRateChanged="false" MaximumAmount="PKR24999.00" MaxAmountRateChanged="false" />
  </hotel:HotelSearchResult>
  <hotel:HotelSearchResult>
    <common_v42_0:VendorLocation ProviderCode="1G" VendorCode="WV" VendorLocationID="01279" Key="MKQyzuBAAA/BUh+q0SAAAA==" />
    <hotel:HotelProperty HotelChain="WV" HotelCode="01279" HotelLocation="KHI" Name="BEACH LUXURY KARACHI" VendorLocationKey="MKQyzuBAAA/BUh+q0SAAAA==" HotelTransportation="26" ReserveRequirement="Guarantee" Availability="Available">
      <hotel:PropertyAddress>
        <hotel:Address>M.T.KHAN RD</hotel:Address>
      </hotel:PropertyAddress>
      <common_v42_0:Distance Units="KM" Value="11" Direction="SW" />
      <hotel:HotelRating RatingProvider="AAA">
        <hotel:Rating>0</hotel:Rating>
      </hotel:HotelRating>
    </hotel:HotelProperty>
    <hotel:RateInfo MinimumAmount="USD88.00" MinAmountRateChanged="false" MaximumAmount="USD203.00" MaxAmountRateChanged="false" />
  </hotel:HotelSearchResult>
</hotel:HotelSearchAvailabilityRsp>`

**Comment by vivekjyotipramanik** [comment]
Hi rehman22,

Coordinate location values are supported only for agencies that are provisioned for Hotel Content Plus (HCP). Please contact your Travelport Account Manager for more information. Thanks.

**Comment by rehman22** [comment]
thanks you vivek
