### ISSUE TITLE
Get Nearest Airports and find Airport by city name

### ISSUE THREAD

**Issue by waqas1987** [Travelport/travelport-uapi-tutorial-php#217]
Is it possible to find nearest airports in travelport API.
2nd is i want find a Airport by city name or City Code in travelport.

need Help

**Comment by vivekjyotipramanik** [comment]
Hi waqas1987,

Please find below the details about the reference data which will provide the details about Airport and CityName. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Getting_Started/Design_Considerations/Reference_Data.htm
