### ISSUE TITLE
UniversalRecordRetrieveRsp - Ticket Issue Date

### ISSUE THREAD

**Issue by ldjvc** [Travelport/travelport-uapi-tutorial-php#218]
Hi,

when tickets are listed in the UniversalRecordRetrieveRsp there appears to be no ticket issue date. I.E., AirReservation->DocumentInfo->TicketInfo does not contain an issue date. How to get this information? Should we just use AirReservation->SupplierLocator->CreateDateTime ?

ldjvc

**Comment by vivekjyotipramanik** [comment]
Hi ldjvc,

Please use the AirRetrieveDocumentReq xml to get the ticket issued date. Please find below the link with all the details. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Air/Air_Ticketing/Displaying_Ticket_Information.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAir%2520Ticketing%2520(Document%2520Production)%7C_____2

**Comment by ldjvc** [comment]
Thanks.
