### ISSUE TITLE
Authentication credentials are invalid

### ISSUE THREAD

**Issue by rickithadi** [Travelport/travelport-uapi-tutorial-php#221]
Authentication works in [demo](https://demo.travelportuniversalapi.com) but not node. Don't know what's going wrong. targetBranch is P108141

**Comment by vivekjyotipramanik** [comment]
Hi rickithadi,

If the credentials are working fine in demosite then the credentials are valid. Please share the exact error you are getting. Thanks.

**Comment by rickithadi** [comment]
Yup that's why i don't understand. Could it have something to do with the target branch? This is the SOAP response
`RequestSoapError.SoapRequestError: Error during request to SOAP API. Check url validity
    at axios.request.then.catch (/home/hadi/node_modules/uapi-json/src/Request/uapi-request.js:114:33)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  name: 'RequestSoapError.SoapRequestError',
  data:
   { status: 401,
data:{<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:faultcode>76</SOAP-ENV:faultcode><SOAP-ENV:faultstring>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:faultstring><SOAP-ENV:faultactor>            </SOAP-ENV:faultactor><SOAP-ENV:detail>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>}}'`

**Comment by rickithadi** [comment]
Hi i feel like an idiot.

 My credentials are for pre-production and I didn't realise the settings object defaults to prod. Switched that up and it works fine. Thanks loads
