### ISSUE TITLE
NO PLATING CARRIER FOUND

### ISSUE THREAD

**Issue by kiran-subedi34** [Travelport/travelport-uapi-tutorial-php#23]
Hello travelport , 
We're working on integration of API in our system. I got some errors:
1) I was able to fetch result from Low Fare Search(LowFareSearchReq). When I tried to send the AirPriceReq I get the error like : NO PLATING CARRIER FOUND . In the demo site , I had logged in with custom credentials and tried  I get the same error. I had attached the request and response here . 

[001-1G_PriceReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/422167/001-1G_PriceReq.txt)
[001-1G_PriceRsp.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/422166/001-1G_PriceRsp.txt)

**Comment by vivekjyotipramanik** [comment]
Hi Kiran,

Thank you for your interest in Travelport Universal API. Could you please try with the below request. Please let me know how it goes. Thanks.

```xml
<?xml version="1.0"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header/>
  <soapenv:Body>
    <air:AirPriceReq xmlns:air="http://www.travelport.com/schema/air_v34_0" xmlns:com="http://www.travelport.com/schema/common_v34_0" xmlns:common_v34_0="http://www.travelport.com/schema/common_v34_0" AuthorizedBy="user" CheckFlightDetails="true" FareRuleType="long" TargetBranch="P7051238" TraceId="trace">
      <com:BillingPointOfSaleInfo xmlns:com="http://www.travelport.com/schema/common_v34_0" OriginApplication="UAPI"/>
      <air:AirItinerary>
        <air:AirSegment Key="jGxHx0NbRmG+ID0/8quDYg==" Group="0" Carrier="QF" FlightNumber="865" Origin="OOL" Destination="SYD" DepartureTime="2016-09-24T16:00:00.000+10:00" ArrivalTime="2016-09-24T17:30:00.000+10:00" FlightTime="90" Distance="423" ETicketability="Yes" Equipment="737" ChangeOfPlane="false" ParticipantLevel="Secure Sell" LinkAvailability="true" PolledAvailabilityOption="Cached status used. Polled avail exists" OptionalServicesIndicator="false" AvailabilitySource="P" AvailabilityDisplayType="Fare Shop/Optimal Shop" ProviderCode="1G"/>
      </air:AirItinerary>
      <air:AirPricingModifiers PlatingCarrier="QF"/>
      <com:SearchPassenger BookingTravelerRef="gr8AVWGCR064r57Jt0+8bA==" Code="ADT"/>
      <air:AirPricingCommand/>
    </air:AirPriceReq>
  </soapenv:Body>
</soapenv:Envelope>

```

Thanks & Regards
Vivekjyoti Pramanik

**Comment by kiran-subedi34** [comment]
Thanks Vivekjyoti Pramanik. It solved the problem. Vivekjyoti ,I am in confused. There are various schema versions for request such as http://www.travelport.com/schema/air_v34_0 or http://www.travelport.com/schem
a/air_v33_0. Which version should we use?

**Comment by vivekjyotipramanik** [comment]
Hi Kiran,

We recommend to use the latest version always which is currently version v38. Please find below the link to download the latest schema version. Please let me know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/Content/Resources/uAPI_WSDLschema_Release-V16.3.0.33.zip

Thanks & Regards
Vivekjyoti Pramanik

**Comment by kiran-subedi34** [comment]
Hi Vivekjyoti,

I had successfully implement the **Low Fare Shop > Air Pricing  > Create Air Booking**. But I got error like **Host error during ticket issue. UNAUTHORISED/INVALID PLATING CARRIER CODE** while implementing the  **Air Ticketing**.  I had done some research but didn't get any solution for this problem. I had attached the request and response here .
[AirTicketRequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/532443/AirTicketRequest.txt)
[AirTicketRsp.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/532444/AirTicketRsp.txt)

**Comment by vivekjyotipramanik** [comment]
Hi Kiran,

We need to review the AirCreateReservationReq and Rsp to analyze this. Most likely reason is, there is a PlatingCarrier associated in the Segment which was missing in AirCreateReservationReq. Please add PlatingCarrier="carrierName" in AirPriceInfo in AirCreateReservationReq and run AirCreateReservationReq and AirTicketReq again. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by kiran-subedi34** [comment]
Hi vivek,

I had added the PlatingCarrier in AirPricingInfo but I get the same error. I had attach the AirCreateReservationReq and Rsp. Please check the files and let me know where I had done error.

[001-1G_AirCreateReservationRsp .txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/534298/001-1G_AirCreateReservationRsp.txt)
[001-1G_AirCreateReservationReq .txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/534299/001-1G_AirCreateReservationReq.txt)

**Comment by vivekjyotipramanik** [comment]
Hi Kiran,

Could you please confirm if you have added PlatingCarrier in AirPriceReq.
It should be added in the AirPriceReq as well. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by kiran-subedi34** [comment]
Hi vivek,

I had added PlatingCarrier in AirPriceReq too. I had attach the AirPriceReq and Rsp and let me known where I had done error.Thanks

[001-1G_AirPriceReq .txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/534942/001-1G_AirPriceReq.txt)
[001-1G_AirPriceRsp .txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/534944/001-1G_AirPriceRsp.txt)

Thanks 
Kiran Subedi

**Comment by vivekjyotipramanik** [comment]
Hi Kiran,

Could you please retry the AirTicketReq and provide me the request and response. Thanks.

Thanks & Regards
Vivekjyoti Pramanik
