### ISSUE TITLE
Our Test crendital not working

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#230]
Hello Vivek,
  Yesterday we receive the test detail for GDS to test, but when we ente these detail in demo site its showing wrong

Here are the details : 

Universal API User ID:  Universal API/uAPI3840912104
--
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P105153
URLs:  https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

Please check

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

We have unlocked the credential. Please use correct password and targetbranch. Looks like the password you are using is incorrect. Thanks.

**Comment by Alex0084** [comment]
Hello Vivek
  i am using the detail which is sent by your system emails, can you please send a new one to this mail id please ?

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

We can't send emails with credentials as it is system email. Please request for a new trial credential. Thanks.

**Comment by Alex0084** [comment]
Hello @vivekjyotipramanik ,

i get the new details but when i go for pricing request then i get this error

**Transaction Error: Procedure/5012**

These are new details


Universal API User ID:  Universal API/uAPI8422215514
--

Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P105400
URLs:  https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

I have reached out to provisioning team to fix the issue and I will provide an update as soon as it is fixed. Please NEVER share password in this forum. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

We have rebuilt the robotic signon. Could you please try again. Thanks.

**Comment by Alex0084** [comment]
Hello @vivekjyotipramanik 

Thank you for correcting the error, when i go for ticket in Demo Site then i get this error

  <air:TicketFailureInfo Code="12008" Message="Host error during ticket issue. INVALID ND LINKAGE" BookingTravelerRef="QzN2aTdTZ2JqNWRrdTlXUg==">


Can you please resolve it so we can test complete flow and implement

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

Ticketing is not allowed with Trial credentials. To enable ticketing, please create a ticket in My.Travelport.com and also, please reach out to your Travelport Account Manager to enable virtual ticketing printer for your pcc. Thanks.
