### ISSUE TITLE
RePrice after AirCreate PNR

### ISSUE THREAD

**Issue by huzatech** [Travelport/travelport-uapi-tutorial-php#235]
Hi, Vivek, 

Thank for your kind support I need your further help. We got the complete flow from LFS to AirTicket. Now we are in a phase and seeking your assistance:
1. We create PNR yesterday or any earlier day, as per pricing rules Filed Fare will expire on a certain time mostly 23:59 on the same day of PNR creation but the PNR remain live. 
2. I didn't find any help / sample for Re-Pricing on how to delete the Filed Fare and store the new Fares.

Dear Vivek hope you got my concern and will reply us with your fruitful comments.

Thanks.

**Comment by huzatech** [comment]
Hi Vivek, seeking your fruitful response please.

Thanks

**Comment by vivekjyotipramanik** [comment]
Hi huzatech,

Could you please raise this question in My.Travelport.com so that we can pick it up from there. Thanks.

**Comment by huzatech** [comment]
Hi Vivek I already on 15JAN but till now I didn't got any reply from them. I found you very cooperative and friendly so please let support us on:

1. Air Re-Price when the file fare was expire but the PNR is live
2. Dividing the PNR
3. Refund (Half / Full) & cancel the air segments
4. Exchange of Air ticket 

I found only a method but didn't samples on how to use which attributes. I am humbly requested to you please help us.

**Comment by vivekjyotipramanik** [comment]
Hi huzatech,

Please find below my comments. I would request you to reach out to your Travelport Account Manager to get a answer on the ticket you have already raised. Thanks.

1. Air Re-Price when the file fare was expire but the PNR is live: To do this you have to use UniveralModify. Please find below the link with the details. 

https://support.travelport.com/webhelp/uapi/uapi.htm#Booking/Modify/Modifying_Air_Bookings.htm%3FTocPath%3DUniversal%2520Records%2520and%2520Bookings%7CModifying%2520Bookings%7CModifying%2520Universal%2520Records%7C_____2

https://support.travelport.com/webhelp/uapi/uapi.htm#SampleWeb/Alternative_Sample_Pages/Samples_UR_Workflows.htm%3FTocPath%3DSamples%7CXML%2520Samples%2520%7CUniversal%2520Record%2520Samples%7CUniversal%2520Record%2520Workflows%7C_____0

2. Dividing the PNR: I am not sure if there is any way to divide a PNR.

3. Refund & Cancel air Segments: 
Refund sample is here 

https://support.travelport.com/webhelp/uapi/uapi.htm#SampleWeb/Individual_Sample_Pages/040-ACH_Air_LFS-AC_ShopToRefund.htm

https://support.travelport.com/webhelp/uapi/uapi.htm#SampleWeb/Individual_Sample_Pages/045-ACH_Air_LFS-AC_CancelHold.htm

https://support.travelport.com/webhelp/uapi/uapi.htm#SampleWeb/Individual_Sample_Pages/043-ACH_Air_LFS-U2_OptSvce-Bag_ShopToRefund.htm

Please find attached the cancellation samples: 
[PartialCancellationSamples (2).zip](https://github.com/Travelport/travelport-uapi-tutorial-php/files/4146415/PartialCancellationSamples.2.zip)


4. Exchange of Air Ticket : Sample is here https://support.travelport.com/webhelp/uapi/uapi.htm#SampleWeb/Individual_Sample_Pages/048-ACH_Air_LFS-U2_ShopToExchange.htm

https://support.travelport.com/webhelp/uapi/uapi.htm#SampleWeb/Individual_Sample_Pages/048-ACH_Air_LFS-U2_ShopToExchange.htm

https://support.travelport.com/webhelp/uapi/uapi.htm#SampleWeb/Individual_Sample_Pages/099-ACH_Air_LFS-AC_ShopToExchange.htm

**Comment by huzatech** [comment]
Hi, thanks for assistance and we browse the codes I just need to clarify on RefundQuoteReq what exactly the TCRN number 





<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:air="http://www.travelport.com/schema/air_v30_0" xmlns:com="http://www.travelport.com/schema/common_v30_0">
<soapenv:Header/>
<soapenv:Body>
<air:AirRefundQuoteReq AuthorizedBy="user" TargetBranch="TRGT_BRCH" TraceId="trace">
<com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
<air:TCRNumber>61692</air:TCRNumber>
</air:AirRefundQuoteReq>
</soapenv:Body>
</soapenv:Envelope>

**Comment by huzatech** [comment]
Also can share a sample code on AirTicketVoidReq. 

please

**Comment by vivekjyotipramanik** [comment]
Hi huzatech,

TCR means Ticketless Carrier Record. It generally returned for ACH carriers which are generally Ticketless Carriers. 

There is no transactions available called AirTicketVoidReq, there is one transaction AirVoidDocumentReq. Could you please check. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#../Subsystems/Schemas/Content/Schemas/AirVoidDocumentReq.html
