### ISSUE TITLE
need to rebuild robotic signon

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#238]
Here are my test details

Universal API User ID:  Universal API/uAPI4701060469-34e29710
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7002784
URLs:  https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

Please check and resolve

Thanks

**Comment by Alex0084** [comment]
Hello
can you resolve it please ?

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

This was rebuilt on 3rd March. Are you still facing the issue. I would recommend to request for new set of credentials if you are still facing the same issue. Thanks.

**Comment by Alex0084** [comment]
Hello @vivekjyotipramanik 

can you also enable robotic signon for this new details

Universal API User ID:  Universal API/uAPI8931078193-41fe5ac8
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7005006
URLs:  https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

Thanks

**Comment by Alex0084** [comment]
Hello @vivekjyotipramanik 
its resolved please ?

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

It was created on Monday April 6th. Could you please try again. Thanks.

**Comment by Alex0084** [comment]
@vivekjyotipramanik 
its still same please check

[MjAwNDEwMTE1OTIyYW0=AirPricingInfoResponse.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/4461425/MjAwNDEwMTE1OTIyYW0.AirPricingInfoResponse.txt)
[MjAwNDEwMTE1OTIyYW0=AirPricingInfoRequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/4461426/MjAwNDEwMTE1OTIyYW0.AirPricingInfoRequest.txt)

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

Could you please create a ticket in My.Travelport.com regarding this issue. I have rechecked with provisioning team and the robotic signOn is in place. Thanks.

**Comment by Alex0084** [comment]
when i login then its says your account is blocked, so can you check it please

username : pulkit@travellights.net

**Comment by vivekjyotipramanik** [comment]
Hi Alex0084,

Unfortunately we would not be able to check for blocked account through github. Please reach out to your Travelport Account Manager or call Travelport Helpdesk. Thanks.
