### ISSUE TITLE
Transaction Error: Procedure/5012

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#242]
Universal API User ID:  Universal API/uAPI5529259828
--
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P105180
URLs:  https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/

**Comment by vivekjyotipramanik** [comment]
Robotic SignOn has been rebuilt. Thanks.

**Comment by vecchiojoe** [comment]
Error: Procedure/5012
Hi i get this error while creating pnr
I'm in test mode.
- uAPI2363283117-0aaa9aed
Thanks
