### ISSUE TITLE
Hi Alex0084, Code not found for booking module

### ISSUE THREAD

**Issue by Arehmans** [Travelport/travelport-uapi-tutorial-php#245]
Hi Alex0084,

Yes, live booking is working fine. Thanks.

_Originally posted by @vivekjyotipramanik in https://github.com/Travelport/travelport-uapi-tutorial-php/issues/243#issuecomment-622438695_

Please guide me I am not able to find book request or reserve flight request in this code.
Moreover, I am getting this error 
[20-Jun-2020 05:24:27 America/New_York] PHP Fatal error:  Error occurred request/response processing! in /home/dailgrat/sdkinfo.com/travel/Air/phpSample_Air.php on line 112

**Comment by vivekjyotipramanik** [comment]
Hi Arehmans,

Could you please log the exact error you are getting. Also, please try your credentials using the https://demo.travelportuniversalapi.com/ and confirm if your credentials are fine. You can put custom credentials in the top right corner of the main page using 'Production'/'Custom Credentials' dropdown. Thanks.

**Comment by Arehmans** [comment]
Yes credentials problem thanks
