### ISSUE TITLE
Unsuccessful primary host transaction causing reservation failure.

### ISSUE THREAD

**Issue by zagriaum** [Travelport/travelport-uapi-tutorial-php#248]
Hello ,
today Im faced this issue for  Booking flight  but yesterday its worked .
   response 
     "faultcode" => "Server.Business"
     "faultstring" => "Unsuccessful primary host transaction causing reservation failure."

**Comment by vivekjyotipramanik** [comment]
Hi zagriaum,

Please check if you are using the correct HostToken returned in the AirPriceRsp. Please share the req and rsp xml to analyze the issue further. Thanks.

**Comment by zagriaum** [comment]
Hello  vivekjyotipramanik , 
I used Test credential its working fine but used to live credential to faced  this issue .
and anothe **question** 

- can i issue ticket using test credential for test purposes ?

**### //Reservation Request**

<?xml version="1.0"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header/>
  <soapenv:Body>
    <univ:AirCreateReservationReq xmlns:air="http://www.travelport.com/schema/air_v41_0" xmlns:common_v41_0="http://www.travelport.com/schema/common_v41_0" xmlns:univ="http://www.travelport.com/schema/universal_v41_0" AuthorizedBy="user" RetainReservation="Both" TargetBranch="P3055729" TraceId="tracebidhee">
      <com:BillingPointOfSaleInfo xmlns:com="http://www.travelport.com/schema/common_v41_0" OriginApplication="uAPI"/>
      <com:BookingTraveler xmlns:com="http://www.travelport.com/schema/common_v41_0" DOB="1993-07-13" Gender="M" Key="qiWg7anbqAPGdZTomZzkSZeY" TravelerType="ADT">
        <com:BookingTravelerName First="Ram" Last="Bohara" Prefix="Mr"/>
        <com:DeliveryInfo>
          <com:ShippingAddress>
            <com:AddressName>Kathamandu Nepal</com:AddressName>
            <com:Street>ktm</com:Street>
            <com:City>ktm</com:City>
            <com:State>ktm</com:State>
            <com:Country>NP</com:Country>
          </com:ShippingAddress>
        </com:DeliveryInfo>
        <com:PhoneNumber AreaCode="1" CountryCode="977" Location="KTM" Number="9813147608"/>
        <com:Email EmailID="bestflynepal@gmail.com" Type="Home"/>
        <com:SSR FreeText="P/NP/24324/NP/13Jul93/M/24Jun25/Bohara/Ram" Type="DOCS"/>
        <com:Address>
          <com:AddressName>Kathamandu Nepal</com:AddressName>
          <com:Street>ktm</com:Street>
          <com:City>ktm</com:City>
          <com:State>ktm</com:State>
          <com:Country>NP</com:Country>
        </com:Address>
      </com:BookingTraveler>
      <com:AgencyContactInfo xmlns:com="http://www.travelport.com/schema/common_v41_0">
        <com:PhoneNumber CountryCode="977" Location="KTM" Number="9841215061" Text="Best Fly"/>
      </com:AgencyContactInfo>
      <com:FormOfPayment xmlns:com="http://www.travelport.com/schema/common_v41_0" Type="Cash"/>
      <air:AirPricingSolution Key="QRveFKRc1BKA+jAMLKAAAA==" TotalPrice="NPR9496" BasePrice="NPR3000" ApproximateTotalPrice="NPR9496" ApproximateBasePrice="NPR3000" Taxes="NPR6496" ApproximateTaxes="NPR6496" QuoteDate="2020-06-24">
        <air:AirSegment Key="QRveFKRc1BKA8jAMLKAAAA==" Group="0" Carrier="RA" FlightNumber="205" ProviderCode="1G" Origin="KTM" Destination="DEL" DepartureTime="2020-08-30T08:00:00.000+05:45" ArrivalTime="2020-08-30T09:40:00.000+05:30" FlightTime="115" TravelTime="115" Distance="506" ClassOfService="X" ChangeOfPlane="false" OptionalServicesIndicator="false" AvailabilityDisplayType="Fare Specific Fare Quote Unbooked">
          <air:CodeshareInfo OperatingCarrier="RA">NEPAL AIRLINES CORPORATION</air:CodeshareInfo>
          <air:FlightDetails Key="QRveFKRc1BKA9jAMLKAAAA==" Origin="KTM" Destination="DEL" DepartureTime="2020-08-30T08:00:00.000+05:45" ArrivalTime="2020-08-30T09:40:00.000+05:30" FlightTime="115" TravelTime="115" Distance="506"/>
        </air:AirSegment>
        <air:AirPricingInfo Key="QRveFKRc1BKAAkAMLKAAAA==" TotalPrice="NPR9496" BasePrice="NPR3000" ApproximateTotalPrice="NPR9496" ApproximateBasePrice="NPR3000" ApproximateTaxes="NPR6496" Taxes="NPR6496" LatestTicketingTime="2020-08-30T23:59:00.000+05:45" PricingMethod="Manual" IncludesVAT="false" ETicketability="Yes" ProviderCode="1G">
          <air:FareInfo Key="QRveFKRc1BKAGkAMLKAAAA==" FareBasis="XOWDELA" PassengerTypeCode="ADT" Origin="KTM" Destination="DEL" EffectiveDate="2020-06-24T19:07:00.000+05:45" DepartureDate="2020-08-30" Amount="NPR3000">
            <air:FareRuleKey FareInfoRef="QRveFKRc1BKAGkAMLKAAAA==" ProviderCode="1G">6UUVoSldxwgykIuTvtyluMbKj3F8T9EyxsqPcXxP0TLGyo9xfE/RMjJs02vwFm2eN+GgJTM7aBgHdoJgT6NTuqmH01+uu6H/FenkGXotILHqj1HL04MgiGAUdVY1xwqBppDnGM8t6Q8H3QVP9uVLlOFHo+GV2bmB3y15wvXv7vU+3dDDBESahCU6h1rWHJVPCplunHywyErPOvXkrT+ckCsrvdeFp4UJ83fZ3yCAPaqF5/cPFa6JQ1mfiDo+P8hvJHXyDAS6XXISUo5B2hXvKWOagxex7drIJY27I3ATiVSF/oTXxxF6MeJYtF79PC3YsxYLUKGiXKXVW5TpURjX8Z25NU6mMqfajm0p+6jlWiLg2BMJ0qOmdc4YTCgtCVCcDW1HK9YNPXKTSmkPozzko+aeJIc23zoev4Xvb2u1Qx+/he9va7VDH7+F729rtUMfv4Xvb2u1Qx+/he9va7VDH8ONhV50oNexly5qxZ3qLwMUu+QC5Q/Q9nDDng+cSKo712q8/th4C8701vHqwlaqzR4fSC3KPF3j5GwF8kqQiiA=</air:FareRuleKey>
          </air:FareInfo>
          <air:BookingInfo BookingCode="X" CabinClass="Economy" FareInfoRef="QRveFKRc1BKAGkAMLKAAAA==" SegmentRef="QRveFKRc1BKA8jAMLKAAAA=="/>
          <air:TaxInfo Category="B6" Amount="NPR1000" Key="QRveFKRc1BKABkAMLKAAAA=="/>
          <air:TaxInfo Category="NP" Amount="NPR791" Key="QRveFKRc1BKACkAMLKAAAA=="/>
          <air:TaxInfo Category="NQ" Amount="NPR1130" Key="QRveFKRc1BKADkAMLKAAAA=="/>
          <air:TaxInfo Category="YQ" Amount="NPR493" Key="QRveFKRc1BKAEkAMLKAAAA=="/>
          <air:TaxInfo Category="YR" Amount="NPR3082" Key="QRveFKRc1BKAFkAMLKAAAA=="/>
          <air:PassengerType Code="ADT" Age="40" BookingTravelerRef="qiWg7anbqAPGdZTomZzkSZeY"/>
          <air:BaggageAllowances>
            <air:BaggageAllowanceInfo TravelerType="ADT" Origin="KTM" Destination="DEL" Carrier="RA">
              <air:URLInfo>
                <air:URL>VIEWTRIP.TRAVELPORT.COM/BAGGAGEPOLICY/RA</air:URL>
              </air:URLInfo>
              <air:TextInfo>
                <air:Text>20K</air:Text>
                <air:Text>BAGGAGE DISCOUNTS MAY APPLY BASED ON FREQUENT FLYER STATUS/ ONLINE CHECKIN/FORM OF PAYMENT/MILITARY/ETC.</air:Text>
              </air:TextInfo>
              <air:BagDetails ApplicableBags="1stChecked" BasePrice="0" ApproximateBasePrice="0" TotalPrice="0" ApproximateTotalPrice="0">
                <air:BaggageRestriction>
                  <air:TextInfo>
                    <air:Text>CHGS MAY APPLY IF BAGS EXCEED TTL WT ALLOWANCE</air:Text>
                  </air:TextInfo>
                </air:BaggageRestriction>
              </air:BagDetails>
              <air:BagDetails ApplicableBags="2ndChecked" BasePrice="0" ApproximateBasePrice="0" TotalPrice="0" ApproximateTotalPrice="0">
                <air:BaggageRestriction>
                  <air:TextInfo>
                    <air:Text>CHGS MAY APPLY IF BAGS EXCEED TTL WT ALLOWANCE</air:Text>
                  </air:TextInfo>
                </air:BaggageRestriction>
              </air:BagDetails>
            </air:BaggageAllowanceInfo>
            <air:CarryOnAllowanceInfo Origin="KTM" Destination="DEL" Carrier="RA">
              <air:TextInfo>
                <air:Text>BAGGAGE ALLOWANCE DATA NOT AVAILABLE</air:Text>
              </air:TextInfo>
            </air:CarryOnAllowanceInfo>
          </air:BaggageAllowances>
        </air:AirPricingInfo>
      </air:AirPricingSolution>
      <com:ActionStatus xmlns:com="http://www.travelport.com/schema/common_v41_0" ProviderCode="1G" TicketDate="2020-08-30T23:59:00.000+05:45" Type="ACTIVE"/>
    </univ:AirCreateReservationReq>
  </soapenv:Body>
</soapenv:Envelope>



**Response**
<?xml version="1.0"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Business</faultcode>
      <faultstring>Unsuccessful primary host transaction causing reservation failure.</faultstring>
      <detail>
        <common_v41_0:ErrorInfo xmlns:common_v41_0="http://www.travelport.com/schema/common_v41_0">
          <common_v41_0:Code>3515</common_v41_0:Code>
          <common_v41_0:Service>AIRSVC</common_v41_0:Service>
          <common_v41_0:Type>Business</common_v41_0:Type>
          <common_v41_0:Description>Unsuccessful primary host transaction causing reservation failure.</common_v41_0:Description>
          <common_v41_0:TransactionId>E67F98BA0A0740628CC4F73B2EF2F3D9</common_v41_0:TransactionId>
          <common_v41_0:TraceId>tracebidhee</common_v41_0:TraceId>
        </common_v41_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>

**Comment by zagriaum** [comment]
Hello vivekjyotipramanik ,
I used Test credential its working fine but used to live credential to faced this issue .
and anothe question

can i issue ticket using test credential for test purposes ?
### //Reservation Request

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
soapenv:Header/
soapenv:Body
<univ:AirCreateReservationReq xmlns:air="http://www.travelport.com/schema/air_v41_0" xmlns:common_v41_0="http://www.travelport.com/schema/common_v41_0" xmlns:univ="http://www.travelport.com/schema/universal_v41_0" AuthorizedBy="user" RetainReservation="Both" TargetBranch="P3055729" TraceId="tracebidhee">
<com:BillingPointOfSaleInfo xmlns:com="http://www.travelport.com/schema/common_v41_0" OriginApplication="uAPI"/>
<com:BookingTraveler xmlns:com="http://www.travelport.com/schema/common_v41_0" DOB="1993-07-13" Gender="M" Key="qiWg7anbqAPGdZTomZzkSZeY" TravelerType="ADT">
<com:BookingTravelerName First="Ram" Last="Bohara" Prefix="Mr"/>
com:DeliveryInfo
com:ShippingAddress
com:AddressNameKathamandu Nepal</com:AddressName>
com:Streetktm</com:Street>
com:Cityktm</com:City>
com:Statektm</com:State>
com:CountryNP</com:Country>
</com:ShippingAddress>
</com:DeliveryInfo>
<com:PhoneNumber AreaCode="1" CountryCode="977" Location="KTM" Number="9813147608"/>
<com:Email EmailID="bestflynepal@gmail.com" Type="Home"/>
<com:SSR FreeText="P/NP/24324/NP/13Jul93/M/24Jun25/Bohara/Ram" Type="DOCS"/>
com:Address
com:AddressNameKathamandu Nepal</com:AddressName>
com:Streetktm</com:Street>
com:Cityktm</com:City>
com:Statektm</com:State>
com:CountryNP</com:Country>
</com:Address>
</com:BookingTraveler>
<com:AgencyContactInfo xmlns:com="http://www.travelport.com/schema/common_v41_0">
<com:PhoneNumber CountryCode="977" Location="KTM" Number="9841215061" Text="Best Fly"/>
</com:AgencyContactInfo>
<com:FormOfPayment xmlns:com="http://www.travelport.com/schema/common_v41_0" Type="Cash"/>
<air:AirPricingSolution Key="QRveFKRc1BKA+jAMLKAAAA==" TotalPrice="NPR9496" BasePrice="NPR3000" ApproximateTotalPrice="NPR9496" ApproximateBasePrice="NPR3000" Taxes="NPR6496" ApproximateTaxes="NPR6496" QuoteDate="2020-06-24">
<air:AirSegment Key="QRveFKRc1BKA8jAMLKAAAA==" Group="0" Carrier="RA" FlightNumber="205" ProviderCode="1G" Origin="KTM" Destination="DEL" DepartureTime="2020-08-30T08:00:00.000+05:45" ArrivalTime="2020-08-30T09:40:00.000+05:30" FlightTime="115" TravelTime="115" Distance="506" ClassOfService="X" ChangeOfPlane="false" OptionalServicesIndicator="false" AvailabilityDisplayType="Fare Specific Fare Quote Unbooked">
<air:CodeshareInfo OperatingCarrier="RA">NEPAL AIRLINES CORPORATION</air:CodeshareInfo>
<air:FlightDetails Key="QRveFKRc1BKA9jAMLKAAAA==" Origin="KTM" Destination="DEL" DepartureTime="2020-08-30T08:00:00.000+05:45" ArrivalTime="2020-08-30T09:40:00.000+05:30" FlightTime="115" TravelTime="115" Distance="506"/>
</air:AirSegment>
<air:AirPricingInfo Key="QRveFKRc1BKAAkAMLKAAAA==" TotalPrice="NPR9496" BasePrice="NPR3000" ApproximateTotalPrice="NPR9496" ApproximateBasePrice="NPR3000" ApproximateTaxes="NPR6496" Taxes="NPR6496" LatestTicketingTime="2020-08-30T23:59:00.000+05:45" PricingMethod="Manual" IncludesVAT="false" ETicketability="Yes" ProviderCode="1G">
<air:FareInfo Key="QRveFKRc1BKAGkAMLKAAAA==" FareBasis="XOWDELA" PassengerTypeCode="ADT" Origin="KTM" Destination="DEL" EffectiveDate="2020-06-24T19:07:00.000+05:45" DepartureDate="2020-08-30" Amount="NPR3000">
<air:FareRuleKey FareInfoRef="QRveFKRc1BKAGkAMLKAAAA==" ProviderCode="1G">6UUVoSldxwgykIuTvtyluMbKj3F8T9EyxsqPcXxP0TLGyo9xfE/RMjJs02vwFm2eN+GgJTM7aBgHdoJgT6NTuqmH01+uu6H/FenkGXotILHqj1HL04MgiGAUdVY1xwqBppDnGM8t6Q8H3QVP9uVLlOFHo+GV2bmB3y15wvXv7vU+3dDDBESahCU6h1rWHJVPCplunHywyErPOvXkrT+ckCsrvdeFp4UJ83fZ3yCAPaqF5/cPFa6JQ1mfiDo+P8hvJHXyDAS6XXISUo5B2hXvKWOagxex7drIJY27I3ATiVSF/oTXxxF6MeJYtF79PC3YsxYLUKGiXKXVW5TpURjX8Z25NU6mMqfajm0p+6jlWiLg2BMJ0qOmdc4YTCgtCVCcDW1HK9YNPXKTSmkPozzko+aeJIc23zoev4Xvb2u1Qx+/he9va7VDH7+F729rtUMfv4Xvb2u1Qx+/he9va7VDH8ONhV50oNexly5qxZ3qLwMUu+QC5Q/Q9nDDng+cSKo712q8/th4C8701vHqwlaqzR4fSC3KPF3j5GwF8kqQiiA=</air:FareRuleKey>
</air:FareInfo>
<air:BookingInfo BookingCode="X" CabinClass="Economy" FareInfoRef="QRveFKRc1BKAGkAMLKAAAA==" SegmentRef="QRveFKRc1BKA8jAMLKAAAA=="/>
<air:TaxInfo Category="B6" Amount="NPR1000" Key="QRveFKRc1BKABkAMLKAAAA=="/>
<air:TaxInfo Category="NP" Amount="NPR791" Key="QRveFKRc1BKACkAMLKAAAA=="/>
<air:TaxInfo Category="NQ" Amount="NPR1130" Key="QRveFKRc1BKADkAMLKAAAA=="/>
<air:TaxInfo Category="YQ" Amount="NPR493" Key="QRveFKRc1BKAEkAMLKAAAA=="/>
<air:TaxInfo Category="YR" Amount="NPR3082" Key="QRveFKRc1BKAFkAMLKAAAA=="/>
<air:PassengerType Code="ADT" Age="40" BookingTravelerRef="qiWg7anbqAPGdZTomZzkSZeY"/>
air:BaggageAllowances
<air:BaggageAllowanceInfo TravelerType="ADT" Origin="KTM" Destination="DEL" Carrier="RA">
air:URLInfo
air:URLVIEWTRIP.TRAVELPORT.COM/BAGGAGEPOLICY/RA</air:URL>
</air:URLInfo>
air:TextInfo
air:Text20K</air:Text>
air:TextBAGGAGE DISCOUNTS MAY APPLY BASED ON FREQUENT FLYER STATUS/ ONLINE CHECKIN/FORM OF PAYMENT/MILITARY/ETC.</air:Text>
</air:TextInfo>
<air:BagDetails ApplicableBags="1stChecked" BasePrice="0" ApproximateBasePrice="0" TotalPrice="0" ApproximateTotalPrice="0">
air:BaggageRestriction
air:TextInfo
air:TextCHGS MAY APPLY IF BAGS EXCEED TTL WT ALLOWANCE</air:Text>
</air:TextInfo>
</air:BaggageRestriction>
</air:BagDetails>
<air:BagDetails ApplicableBags="2ndChecked" BasePrice="0" ApproximateBasePrice="0" TotalPrice="0" ApproximateTotalPrice="0">
air:BaggageRestriction
air:TextInfo
air:TextCHGS MAY APPLY IF BAGS EXCEED TTL WT ALLOWANCE</air:Text>
</air:TextInfo>
</air:BaggageRestriction>
</air:BagDetails>
</air:BaggageAllowanceInfo>
<air:CarryOnAllowanceInfo Origin="KTM" Destination="DEL" Carrier="RA">
air:TextInfo
air:TextBAGGAGE ALLOWANCE DATA NOT AVAILABLE</air:Text>
</air:TextInfo>
</air:CarryOnAllowanceInfo>
</air:BaggageAllowances>
</air:AirPricingInfo>
</air:AirPricingSolution>
<com:ActionStatus xmlns:com="http://www.travelport.com/schema/common_v41_0" ProviderCode="1G" TicketDate="2020-08-30T23:59:00.000+05:45" Type="ACTIVE"/>
</univ:AirCreateReservationReq>
</soapenv:Body>
</soapenv:Envelope>

Response

<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
SOAP:Body
SOAP:Fault
Server.Business
Unsuccessful primary host transaction causing reservation failure.

<common_v41_0:ErrorInfo xmlns:common_v41_0="http://www.travelport.com/schema/common_v41_0">
<common_v41_0:Code>3515</common_v41_0:Code>
<common_v41_0:Service>AIRSVC</common_v41_0:Service>
<common_v41_0:Type>Business</common_v41_0:Type>
<common_v41_0:Description>Unsuccessful primary host transaction causing reservation failure.</common_v41_0:Description>
<common_v41_0:TransactionId>E67F98BA0A0740628CC4F73B2EF2F3D9</common_v41_0:TransactionId>
<common_v41_0:TraceId>tracebidhee</common_v41_0:TraceId>
</common_v41_0:ErrorInfo>

</SOAP:Fault>
</SOAP:Body>
</SOAP:Envelope>

**Comment by vivekjyotipramanik** [comment]
Hi zagriaum,

For live credential issues, could you please raise a ticket in My.Ttravelport.com and we will pick it up from there. Thanks.

**Comment by zagriaum** [comment]
HI vivekjyotipramanik,
Okay Thankyou .
but can't solution  Unsuccessful primary host transaction causing reservation failure. this issue for using live credential ?

**Comment by vivekjyotipramanik** [comment]
Hi zagriaum,

Any issue related to live credentials should be raised through My.Travelport.com. Unfortunately through github we would not be able to resolve issues with live credentials. Thanks.

**Comment by zagriaum** [comment]
HI vivekjyotipramanik,
Okay thanks .
