### ISSUE TITLE
 all class flight 

### ISSUE THREAD

**Issue by zagriaum** [Travelport/travelport-uapi-tutorial-php#249]
how to serch all class flight ?

**Comment by vivekjyotipramanik** [comment]
Hi zagriaum,

Could you please elaborate your question. Thanks.

**Comment by zagriaum** [comment]
Hi vivekjyotipramanik ,
eg we want search  Economy & Business class pass to form value Economy & Business  like wise  want to all   classes what  value pass form data .

**Comment by vivekjyotipramanik** [comment]
Hi zagriaum,

Just to clarify, are you looking to search flights which will return flight from both Economy and Business class. If that is the case, could you please try with this. Thanks.

```xml
<LowFareSearchReq xmlns="http://www.travelport.com/schema/air_v42_0" TraceId="2c60e574-1623-40bd-9d6e-d13afb3d1663" TargetBranch="P3088249" ReturnUpsellFare="true">
  <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v42_0" OriginApplication="uAPI" />
  <SearchAirLeg>
    <SearchOrigin>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v42_0" Code="DEN" PreferCity="true" />
    </SearchOrigin>
    <SearchDestination>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v42_0" Code="LHR" PreferCity="true" />
    </SearchDestination>
    <SearchDepTime PreferredTime="2020-12-16" />
  </SearchAirLeg>
  <AirSearchModifiers>
    <PreferredProviders>
      <Provider xmlns="http://www.travelport.com/schema/common_v42_0" Code="1G" />
    </PreferredProviders>
  </AirSearchModifiers>
  <SearchPassenger xmlns="http://www.travelport.com/schema/common_v42_0" Code="ADT" />
  <AirPricingModifiers>
    <AccountCodes>
      <AccountCode xmlns="http://www.travelport.com/schema/common_v42_0" Code="-" />
    </AccountCodes>
  </AirPricingModifiers>
</LowFareSearchReq>
```

**Comment by zagriaum** [comment]
Hi vivekjyotipramanik , 
we want listout all cabin class flight .

**This request list out  only economic class cabin flight**  
<?xml version="1.0"?>

    <LowFareSearchReq xmlns="http://www.travelport.com/schema/air_v41_0" TraceId="tracebidhee" TargetBranch="P7085688" ReturnUpsellFare="true">
      <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v41_0" OriginApplication="uAPI"/>
      <SearchAirLeg>
        <SearchOrigin>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v41_0" Code="KTM" PreferCity="true"/>
        </SearchOrigin>
        <SearchDestination>
          <CityOrAirport xmlns="http://www.travelport.com/schema/common_v41_0" Code="DEL" PreferCity="true"/>
        </SearchDestination>
        <SearchDepTime PreferredTime="2021-01-30">
        </SearchDepTime>
        <AirLegModifiers>
          <PreferredCabins>
            <CabinClass xmlns="http://www.travelport.com/schema/common_v41_0" Type="Economy"/>
          </PreferredCabins>
        </AirLegModifiers>
      </SearchAirLeg>
      <AirSearchModifiers>
        <PreferredProviders>
          <Provider xmlns="http://www.travelport.com/schema/common_v41_0" Code="1G"/>
        </PreferredProviders>
      </AirSearchModifiers>
      <SearchPassenger xmlns="http://www.travelport.com/schema/common_v41_0" Code="ADT" Age="40" DOB="1980-07-08"/>
    </LowFareSearchReq>

but we want listout all cabin class flight . which value pass this cabin class for listout all cabin class flight  ?

**Comment by vivekjyotipramanik** [comment]
Hi zagriaum,

This request will list out every cabin class flight based on availability. Thanks.

```xml
<LowFareSearchReq xmlns="http://www.travelport.com/schema/air_v41_0" TraceId="tracebidhee" TargetBranch="P7085688" ReturnUpsellFare="true">
  <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v41_0" OriginApplication="uAPI"/>
  <SearchAirLeg>
    <SearchOrigin>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v41_0" Code="KTM" PreferCity="true"/>
    </SearchOrigin>
    <SearchDestination>
      <CityOrAirport xmlns="http://www.travelport.com/schema/common_v41_0" Code="DEL" PreferCity="true"/>
    </SearchDestination>
    <SearchDepTime PreferredTime="2021-01-30">
    </SearchDepTime>
  </SearchAirLeg>
  <AirSearchModifiers>
    <PreferredProviders>
      <Provider xmlns="http://www.travelport.com/schema/common_v41_0" Code="1G"/>
    </PreferredProviders>
  </AirSearchModifiers>
  <SearchPassenger xmlns="http://www.travelport.com/schema/common_v41_0" Code="ADT" Age="40" DOB="1980-07-08"/>
</LowFareSearchReq>```

**Comment by zagriaum** [comment]
Thank you @vivekjyotipramanik  its working .
