### ISSUE TITLE
How Can I View The XML Response Before I Start Parse IT 

### ISSUE THREAD

**Issue by Kyrillos25** [Travelport/travelport-uapi-tutorial-php#25]
I have a soap request and i need to preview the XML Response so i can parse it 

Note: The Request in the attachments 
![low far search](https://cloud.githubusercontent.com/assets/17097663/19021431/38a43b7e-88c1-11e6-9abc-c996f6acae24.png)

**Comment by NirandaG** [comment]
Hi Kyrillos25,
You can use Fiddler to monitor the request and responses via the SOAP.

Thank you,
B.Rgds,
Niranda

**Comment by Kyrillos25** [comment]
I will try it 
, Thanks

**Comment by Kyrillos25** [comment]
what data should be inserted in composer header in Fiddler ?

i tried this

Content-Type: text/xml;charset=UTF-8
Accept: gzip,deflate
Cache-Control: no-cache
Pragma: no-cache
SOAPAction: \"\"
Authorization: Basic $CREDENTIALS 
Content-length:1171


And i got this Error 

HTTP/1.1 504 Fiddler - Receive Failure
Cache-Control: no-cache, must-revalidate

**Comment by Kyrillos25** [comment]
Thanks Niranda
I used POSTMAN and i work!
