### ISSUE TITLE
Date Change and Reissue Ticket

### ISSUE THREAD

**Issue by huzatech** [Travelport/travelport-uapi-tutorial-php#252]
Hi, 
I need your support in Travelport 1G API for:
1. Need to book a new segments by LFS
2. Cancel the previous segments
3. Get fare difference (quote) of new flights
4. Save price and Issue the new Ticket (Exchange of AirTicket).

Note: UR created and ticket issued. 

Seeking your assistance with some sample xml. Thanks

Mannan

**Comment by vivekjyotipramanik** [comment]
Hi huzatech,

You have to reprice it using AirPriceReq, during this you have to use the AirReservation locator in the AirPriceReq and then use UR modify to add the fare to the UR again. Please find below the details. Thanks.

https://support.travelport.com/webhelp/uapi/uapi.htm#Air/Air_Pricing/Air_Pricing.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7CAir%2520Pricing%7C_____0

https://support.travelport.com/webhelp/uapi/uapi.htm#Air/Shared_Air_Topics/Manual_Fares.htm

**Comment by huzatech** [comment]
Thanks Vivek, 

one another question, we need to exclude PK in the LFS req and res. 
Is there any method? please.

**Comment by vivekjyotipramanik** [comment]
Hi huzatech,

You can add ProhibitedCarriers in the AirSearchModifiers or AirLegModifiers like below. Just to add, PermittedCarrier, ProhibitedCarrier, and PreferredCarrier are mutually exclusive, and cannot be included in the same request. A warning is returned. Thanks.

```xml
<AirSearchModifiers>
    <ProhibitedCarriers>
      <Carrier Code="PK" />
    </ProhibitedCarriers>
</AirSearchModifiers>
```

**Comment by huzatech** [comment]
many thanks
