### ISSUE TITLE
Where i can find "ClassOfService" attribute to make "AirPrice" Request

### ISSUE THREAD

**Issue by Kyrillos25** [Travelport/travelport-uapi-tutorial-php#26]
Based on "LowFarSearchRS" in "024-1G_Air_LFS_MinimumData" 
i get all the data i need to make "AirPriceRQ" except this attribute "ClassOfService" i didn't find it.
could someone help me!
,thanks

@vivekjyotipramanik

**Comment by vivekjyotipramanik** [comment]
Hi Kyrillos25,

The ClassOfService is same as BookingInfo. Please check the BookingInfo/@BookingCode in the AirPricingSolution in LowFareSearch. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Kyrillos25** [comment]
So i will use BookingInfo/@BookingCode instead of Airsegment/@ClassOfService
That it?!

**Comment by vivekjyotipramanik** [comment]
Hi Kyrillos25,

You have to use the value of BookingInfo/@BookingCode from LowFareSearchRsp in AirSegment/@ClassOfService in AirPriceRsp. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Kyrillos25** [comment]
OK 
the Request has been sent and no error encountered

Thanks Vivekjyoti Pramanik
