### ISSUE TITLE
General air service Error

### ISSUE THREAD

**Issue by Kyrillos25** [Travelport/travelport-uapi-tutorial-php#28]
Hi,
I'm Trying to create "AirBookReq" but i'm getting this Error

![capture](https://cloud.githubusercontent.com/assets/17097663/19196682/c19b9fe6-8cb6-11e6-8d00-02496bef0ae4.JPG)

**Comment by vivekjyotipramanik** [comment]
Hi Kyrillos25,

This is a valid issue and occurs when the AirSegment is not available anymore.
As lots of developers and testers are using the PreProduction environment, this is a quite common in PreProduction envirnment. Please try with different Airlines, markets and dates. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik
