### ISSUE TITLE
Some of the requested AirPricingInfos could not be saved for the requested provider

### ISSUE THREAD

**Issue by sivaneshc** [Travelport/travelport-uapi-tutorial-php#49]
Hi,

I am getting warning like "Some of the requested AirPricingInfos could not be saved for the requested provider" and "NO VALID FARE FOR INPUT CRITERIA" in the AirCreateReservationRsp. 

I get this error most of the time. Please find the attached request and response xmls.

[xmls.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/656602/xmls.txt)

Thank you.

**Comment by vivekjyotipramanik** [comment]
Hi  sivaneshc,

There was a Fare outage in PreProduction environment today. Could you please try again.
If it is still not working please try adding PlatingCarrier in the AirPricingInfo in AirCreateReservationReq. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik
