### ISSUE TITLE
Can't issue EMD-A

### ISSUE THREAD

**Issue by ewingsmarco** [Travelport/travelport-uapi-tutorial-php#50]
After ticketing a Booking, when i try to issue an EMD (EMDIssuanceReq) the system replies "User is not authorized". 

The same credentials are working for all the other requests (searching, pricing, ticketing). What could be causing this? 

the XML i´m sending:

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:air="http://www.travelport.com/schema/air_v30_0" xmlns:com="http://www.travelport.com/schema/common_v30_0">
<soapenv:Header/>
<soapenv:Body>
<air:EMDIssuanceReq AuthorizedBy="user" ShowDetails="true" TargetBranch="******" TraceId="trace" UniversalRecordLocatorCode="****">
<com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
<com:ProviderReservationDetail ProviderCode="1G" ProviderLocatorCode="******"/>
<com:TicketNumber>*************</com:TicketNumber>
<air:SelectionModifiers RFIC="*" SupplierCode="**">
<air:AirSegmentRef Key="*****"/>
</air:SelectionModifiers>
</air:EMDIssuanceReq>
</soapenv:Body>
</soapenv:Envelope>

**Comment by vivekjyotipramanik** [comment]
Hi  ewingsmarco,

Thank you for your interest in Travelport Universal API. The same credentials should work for EMD if you are provisioned for Air Merchandising. If you are using PreProduction or Production credentials please contact you Travelport Account Manager and you Travelport Account Manager will be help you getting provisioned for Air Merchandising. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by ewingsmarco** [comment]
Like you wrote,  that was Air Merchandising provisioning was missing. Thank you.
