### ISSUE TITLE
How does transaction work

### ISSUE THREAD

**Issue by jackychang94** [Travelport/travelport-uapi-tutorial-php#53]
Hello, I've been working on the API sample and while I understand how most of it works, I'm unsure about payment.
Does travelport get paid while the website user is checking out with a hotel/flight OR the one getting paid is the travel agent/website owner? Is there need to set up a payment gateway (eg. Paypal) on our website that is utilizing the uAPI, or we simply send credit card details over to travelport for processing?
Also, are there any difference in the payment process between air, hotel and vehicle?

Thank you so much!

**Comment by NirandaG** [comment]
Hi jackychang94,

Yes, you need to integrate a payment gateway to your system and it's totally up to you to decide which payment gateway you could use depending on the business logic.
Since this is business related question I would ask you to speak to your Travelport Account Manager.

Thank you,
B.Rgds,
Niranda

**Comment by marcadde23** [comment]
@NirandaG @vivekjyotipramanik 
May I ask, I did the LowFareSearchReq, and now I want to select one flight.
In my page, I added "Select" button, which I want to generate AirPrice_Rq.xml, which method do I use?
Is there any guide/standard to follow, or just is open to create that AirPrice_Rq.xml on my own way.

Secondly, in AirPrice_Rq.xml we should write BookingTravelerRef and Key attributes for SearchPassenger node??, okay then In LowFareSearchRsp.xml, where I find BookingTravelerRef for each passenger?

Thank you.

**Comment by vivekjyotipramanik** [comment]
Hi marcadde23,

Please find below the link with the guide. 

In LowFareSearchRsp, there is no BookingTravelerRef to Key, you can use any alpha numeric number as Key. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Air/Air_Shopping_and_Booking.htm%3FTocPath%3DAir%7CAir%2520Shopping%2520and%2520Booking%7C_____0

**Comment by marcadde23** [comment]
@vivekjyotipramanik  Thank you for replying me, 
Now, i sent AirPrice request as below

```
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Header/>
  <soapenv:Body>
    <AirPriceReq xmlns="http://www.travelport.com/schema/air_v42_0" xmlns:air="http://www.travelport.com/schema/air_v42_0" TraceId="trace" AuthorizedBy="user" TargetBranch="P105370">
      <BillingPointOfSaleInfo xmlns="http://www.travelport.com/schema/common_v42_0" OriginApplication="uAPI"/>
      <AirItinerary>
        <AirSegment Key="7M+sSJ3R2BKA7TNyBAAAAA==" Group="0" Origin="NBO" Carrier="KQ" Distance="2200" Equipment="788" FlightTime="305" Destination="DXB" ArrivalTime="2018-03-31T01:00:00.000+04:00" FlightNumber="310" DepartureTime="2018-03-30T18:55:00.000+03:00" ETicketability="Yes" ParticipantLevel="Secure Sell" LinkAvailability="true" AvailabilitySource="P" AvailabilityDisplayType="Fare Shop/Optimal Shop" PolledAvailabilityOption="Cached status used. Polled avail exists" OptionalServicesIndicator="false"/>
      </AirItinerary>
      <AirPricingModifiers InventoryRequestType="DirectAccess">
        <BrandModifiers ModifierType="FareFamilyDisplay"/>
      </AirPricingModifiers>
      <SearchPassenger xmlns="http://www.travelport.com/schema/common_v42_0" Code="ADT"/>
      <AirPricingCommand>
        <AirSegmentPricingModifiers AirSegmentRef="7M+sSJ3R2BKA7TNyBAAAAA=="/>
      </AirPricingCommand>
      <FormOfPayment xmlns="http://www.travelport.com/schema/common_v42_0" Type="Credit"/>
    </AirPriceReq>
  </soapenv:Body>
</soapenv:Envelope>
```

And I got response like this

```
<?xml version="1.0"?>
<SOAP:Envelope xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP:Body>
    <SOAP:Fault>
      <faultcode>Server.Business</faultcode>
      <faultstring>SearchPassenger Key or BookingTravelerRef is required.</faultstring>
      <detail>
        <common_v42_0:ErrorInfo xmlns:common_v42_0="http://www.travelport.com/schema/common_v42_0">
          <common_v42_0:Code>4398</common_v42_0:Code>
          <common_v42_0:Service>AIRSVC</common_v42_0:Service>
          <common_v42_0:Type>Business</common_v42_0:Type>
          <common_v42_0:Description>SearchPassenger Key or BookingTravelerRef is required.</common_v42_0:Description>
          <common_v42_0:TransactionId>668ABF6C0A07643B5A94851F1FBEF6E5</common_v42_0:TransactionId>
          <common_v42_0:TraceId>trace</common_v42_0:TraceId>
        </common_v42_0:ErrorInfo>
      </detail>
    </SOAP:Fault>
  </SOAP:Body>
</SOAP:Envelope>
```
I see **SOAP Fault: SearchPassenger Key or BookingTravelerRef is required** in response
Okay then, where I can find BookingTravelerRef in Low Fare Shopping Response?
