### ISSUE TITLE
Price difference for more than one passenger.

### ISSUE THREAD

**Issue by sivaneshc** [Travelport/travelport-uapi-tutorial-php#55]
Hi,

In AirPriceResponse we get 1772 as total price for two adults but in the demo portal we see 886 which is exactly half the price. Here is the PNR **ZMQW51**

Here is the request and response xml
[uapi.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/671768/uapi.txt)

What is going wrong?

Thank you

**Comment by sivaneshc** [comment]
Any update?

**Comment by NirandaG** [comment]
Hi sivaneshc,

I have checked with the demo site for the exact dates I get the same  price SGD1772.
Please find the attached screen capture from the demo site flight options.
Could you please let me know which option you are reffering as half price on demo site?

Thank you,
B.Rgds,
Niranda
![demo](https://cloud.githubusercontent.com/assets/17075104/21510102/cb40469c-cce3-11e6-81d6-7e137b3d8e76.jpg)

**Comment by sivaneshc** [comment]
Hi Niranda,

Thanks for your support.
AirPriceResponse shows SGD1772. No problem in that. The exact issue is, after completing the booking we retrieved the same in demo portal. There in itinerary we get the price as SGD886.

![capture](https://cloud.githubusercontent.com/assets/5404973/21515885/6244cdaa-ccf9-11e6-9502-eea2b3f2afc5.JPG)

Thank you.

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

We used the same Flights for testing and after reservation and retrieving as well the price is coming up same as the AirPriceResponse. Could you please share the screenshot just before reservation/booking showing the price of the cart or the AirPriceReq/rsp and the AirCreateReservationReq/Rsp from the demosite logs. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by sivaneshc** [comment]
Hi vivekjyotipramanik,

Please find the attached logs and screenshots from demosite.

![availability](https://cloud.githubusercontent.com/assets/5404973/21536751/d8853da2-cdac-11e6-800e-2a5cf06fb146.JPG)

![airpricereqres](https://cloud.githubusercontent.com/assets/5404973/21536750/d85b3dd6-cdac-11e6-9a15-8dfa501186dc.JPG)

![ticket](https://cloud.githubusercontent.com/assets/5404973/21536752/d89b7dce-cdac-11e6-9395-e37bfff36f54.JPG)


[demositelogs.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/676590/demositelogs.txt)

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

Thanks for the details. We are checking and will provide an update soon. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

There is some problem with the demosite AirPriceReq which is the reason it is returning only one AirPriceInfo in the response and that is the reason, the booking req/rsp is only getting only once AirPriceInfo. 

Please find below the corrected AirPriceRsp. It will return the missing AirPriceInfo in the response and we have to use both of the AirPriceInfo in the bookingReq to get the correct price in booking. In the meantime, we are working to fix the issue. Please let me know how it goes. Thanks.

```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <air:AirPriceReq AuthorizedBy="JAN" TargetBranch="TRGT_BRCH" FareRuleType="none" CheckFlightDetails="true" xmlns:air="http://www.travelport.com/schema/air_v39_0">
      <com:BillingPointOfSaleInfo OriginApplication="UAPI" xmlns:com="http://www.travelport.com/schema/common_v39_0"/>
      <air:AirItinerary>
        <air:AirSegment Key="d+U6Ll4R2BKAYqHAAAAAAA==" Group="0" Carrier="QF" FlightNumber="400" Origin="MEL" Destination="SYD" DepartureTime="2017-01-18T06:00:00.000+11:00" ArrivalTime="2017-01-18T07:25:00.000+11:00" FlightTime="85" Distance="456" ETicketability="Yes" Equipment="332" ChangeOfPlane="false" ParticipantLevel="Secure Sell" LinkAvailability="true" PolledAvailabilityOption="Cached status used. Polled avail exists" OptionalServicesIndicator="false" AvailabilitySource="P" AvailabilityDisplayType="Fare Shop/Optimal Shop" ProviderCode="1G" ClassOfService="K">
        </air:AirSegment>
        <air:AirSegment Key="d+U6Ll4R2BKAaqHAAAAAAA==" Group="1" Carrier="QF" FlightNumber="497" Origin="SYD" Destination="MEL" DepartureTime="2017-01-23T22:00:00.000+11:00" ArrivalTime="2017-01-23T23:35:00.000+11:00" FlightTime="95" Distance="456" ETicketability="Yes" Equipment="332" ChangeOfPlane="false" ParticipantLevel="Secure Sell" LinkAvailability="true" PolledAvailabilityOption="Cached status used. Polled avail exists" OptionalServicesIndicator="false" AvailabilitySource="P" AvailabilityDisplayType="Fare Shop/Optimal Shop" ProviderCode="1G" ClassOfService="K">
        </air:AirSegment>
      </air:AirItinerary>
      <com:SearchPassenger Code="ADT" Age="21" BookingTravelerRef="1" Key="A" xmlns:com="http://www.travelport.com/schema/common_v39_0"/>
      <com:SearchPassenger Code="ADT" Age="20" BookingTravelerRef="2" Key="B" xmlns:com="http://www.travelport.com/schema/common_v39_0"/>
      <air:AirPricingCommand/>
      <FormOfPayment Type="Credit" xmlns="http://www.travelport.com/schema/common_v39_0"/>
    </air:AirPriceReq>
  </soap:Body>
</soap:Envelope>
```

Thanks & Regards
Vivekjyoti Pramanik
