### ISSUE TITLE
How will i maintain the session in the Low fare shopping of Universal API flow?Is there any login request? 

### ISSUE THREAD

**Issue by vishababu** [Travelport/travelport-uapi-tutorial-php#56]
I know the flow of flight.Before Booking ,session creation request will started.that means while searching the availability and checking the price, how will i maintain the session to track the booking flow from the starting stage?

**Comment by vivekjyotipramanik** [comment]
Hi vishababu,

Thank you for your interest in Travelport Universal API. We can use SessionContext from Search as well. 
Please find below the link which might be helpful. Please let me know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Sessions/Introduction_to_Sessioning.htm%3FTocPath%3DSessions%7C_____0

Thanks & Regards
Vivekjyoti Pramanik

**Comment by vishababu** [comment]
Hi vivek,
Thank you for giving the link.In Session context, What string value will be kept for nm,val,id to the request?Thanks for kind reply.

Regards,
VishaBabu

**Comment by vivekjyotipramanik** [comment]
Hi vishababu,

Once we start the session using BookingStartReq we will receive the sessionKey in the response. Please find below the samples. Please let me know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/Content/Sessions/Samples/1.Start%20Session-Req.xml

https://support.travelport.com/webhelp/uapi/Content/Sessions/Samples/1.Start%20Session-Rsp.xml

Thanks & Regards
Vivekjyoti Pramanik

**Comment by vishababu** [comment]
Hi Vivekjyoti Pramanik,

Thanks for your reply.As you already mentioned before two days,session context is used to track the booking flow from the search itself.But in that session context class request,we have given two sessioncontextsessionpro and sessioncontextsessiontok class objects.In that respective objects,string value nm,val,id are given.So now What string value will be kept for nm,val,id to the search request?
 
Thanks,
Visha Babu

**Comment by vivekjyotipramanik** [comment]
Hi vishababu,

We are checking and will provide an update soon. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by vivekjyotipramanik** [comment]
Hi vishababu,

As of current UAPI release using Sessions in LowFareSearch and AirPrice is not recommened, cause it might hold up a GTID which might cause issue internally. Using object serialization or using caching of LowFareSearch through programming is a better recommended approach for LowFareSearch and AirPrice as of now. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by vishababu** [comment]
Hi vivek, 

Thanks for Kind Reply.

Regards,
VishaBabu
