### ISSUE TITLE
Domain/Service: uAPI/Service not authorized for user

### ISSUE THREAD

**Issue by yatinmistry** [Travelport/travelport-uapi-tutorial-php#58]
Hello,
We are getting error after getting  production api credentials.
**"Domain/Service: uAPI/Service not authorized for user"**

And new credentials are working on Travelport Test Tool and demo.travelportuniversalapi.com.
But from our system it is not working.

I have also changed production endpoint : https://apac.universal-api.travelport.com/B2BGateway/connect/uAPI/Service.

[LowFareSearchRes.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/693377/LowFareSearchRes.txt)
[LowFareSearchReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/693378/LowFareSearchReq.txt)

Thanks,
Yatin Mistry

**Comment by vivekjyotipramanik** [comment]
Hi yatinmistry,

The URL you are using is missing the actual service name. 
Please try with the URL,  https://apac.universal-api.travelport.com/B2BGateway/connect/uAPI/AirService. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by yatinmistry** [comment]
Hi Vivekjyoti Pramanik,

Thanks a lot.

Now its working.
