### ISSUE TITLE
Voiding Tickets

### ISSUE THREAD

**Issue by ewingsmarco** [Travelport/travelport-uapi-tutorial-php#60]
Hi,

we are voiding tickets using AirVoidDocumentReq, and it´s been working for a while. But when we ticket extra baggage (optional services) for that same flight, then when voiding the ticket, extra baggage does not get voided. How to void extra baggage? In Travelport's documentation it says AirVoidDocumentReq cannot be used to void EMDs. 

here is the generic xml we use to void a ticket:

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:air="http://www.travelport.com/schema/air_v36_0" xmlns:com="http://www.travelport.com/schema/common_v36_0">
<soapenv:Header/>
<soapenv:Body>
<air:AirVoidDocumentReq AuthorizedBy="xxxx" BulkTicket="false" ReturnInfoOnFail="true" TargetBranch="xxxxxx" TraceId="trace">
<com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
<air:AirReservationLocatorCode> xxxx </air:AirReservationLocatorCode>
</air:AirVoidDocumentReq>
</soapenv:Body>
</soapenv:Envelope>`

Thank you very much.

**Comment by vivekjyotipramanik** [comment]
Hi  ewingsmarco,

The void ticketing is only for voiding tickets and it does not support voiding EMDs which I believe you are trying to do while voiding baggage. To cancel any optional service we can use UniveralRecordModify. Please find below the link which might be helpful. Please let me know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Booking/Modify/Modifying_Universal_Records.htm%3FTocPath%3DUniversal%2520Records%2520and%2520Bookings%7CModifying%2520Bookings%7CModifying%2520Universal%2520Records%7C_____0

Thanks & Regards
Vivekjyoti Pramanik

**Comment by ewingsmarco** [comment]
Thank you very much for your help.

I´m trying to send a UniveralRecordModify request to cancel extra baggage optional service, but the response gives me "TPGateway - Request data not found - Request ignored". 

This is an example of the xml i´m sending:
```

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:univ="http://www.travelport.com/schema/universal_v34_0"
                  xmlns:com="http://www.travelport.com/schema/common_v34_0">
  <soapenv:Body>
		<univ:UniversalRecordModifyReq AuthorizedBy="xxxx" ReturnRecord="true" TargetBranch="xxxx" Version="0">
			<com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
			<univ:RecordIdentifier ProviderCode="1G" ProviderLocatorCode="xxxxx" UniversalLocatorCode="xxxxx"/>
			<univ:UniversalModifyCmd>
					<univ:UniversalDelete>
						<common_v34_0:SSR Key="8zaefmBAAA/B3LJgfMAAAA==" SegmentRef="t59gUmBAAA/BErr4dMAAAA==" Status="KD" Type="ASVC" FreeText="**C/0H8/ABAG/PREPAID FIRST ADDITIONAL PC 23/A" Carrier="XX" ProviderReservationInfoRef="8zaeUmBAAA/BfAUgfMAAAA=="/>
					</univ:UniversalDelete>
				</univ:AirAdd>
			</univ:UniversalModifyCmd>
		</univ:UniversalRecordModifyReq>
	</soapenv:Body>
</soapenv:Envelope>
```

Do you have an example of a univ:UniversalRecordModifyReq deleting an optional service?

**Comment by vivekjyotipramanik** [comment]
Hi ewingsmarco,

Could you please confirm the Endpoint URL you are using. The URL should be 
https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/UniversalRecordService.
Please confirm if you are using the same. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by ewingsmarco** [comment]
Hi,

we are not using that URL, but now i was able to sucessful cancel extra baggage optional services with the following XML:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
									xmlns:univ="http://www.travelport.com/schema/universal_v34_0"
									xmlns:com="http://www.travelport.com/schema/common_v34_0"
									xmlns:air="http://www.travelport.com/schema/air_v34_0">
  <soapenv:Body>
		<univ:UniversalRecordModifyReq AuthorizedBy="user" ReturnRecord="true" TargetBranch="xxxxx" Version="3">
			<com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
			<univ:RecordIdentifier ProviderCode="1G" ProviderLocatorCode="xxxxx" UniversalLocatorCode="xxxxx"/>
			<univ:UniversalModifyCmd Key="teste">
				<univ:AirDelete BookingTravelerRef="xxxxx" ReservationLocatorCode="xxxx" Element="SSR" Key="xxxxxxxx"></univ:AirDelete>
			</univ:UniversalModifyCmd>
		</univ:UniversalRecordModifyReq>
	</soapenv:Body>
</soapenv:Envelope>
```

After some feedback from Travelport, there isn´t currently any service to void EMD´s. It has to be done manually.


Thank you very much for your help.
Marco

**Comment by huzatech** [comment]
Hi Vivekjyoti,
I am searching the xml for AirVoid ticket but I can't found anything. 
Can please share a req & res for void air ticket.

Thanks

**Comment by AnsariRNT** [comment]
@huzatech 

same here. I coudnt find any link to the void sample. Have you got it? if youve got it.. pls share here.. will be a great help
