### ISSUE TITLE
Search thumbnails

### ISSUE THREAD

**Issue by HipeL** [Travelport/travelport-uapi-tutorial-php#61]
Hello, sorry for being bugging you guys again.
Is there any way of getting 1 -> 10 images to show as preview when searching for hotel without having to send +1 request per hotel found via HotelSearchAvailabilityReq or is it actually mandatory to send a HotelMediaLinksReq foreach hotel:HotelProperty 
Thank you in advance and sorry for my poor english

**Comment by vivekjyotipramanik** [comment]
Hi HipeL,

Using HotelSearchAvailability it is not possible to get Hotel Images. We can use HotelMediaLinks to get the Hotel Images. Although, there is another Travelport Product called Hotel Content Plus(HCP) using which you can download the static contents like images etc. Please contact your Travelport Account Manager or visit https://developer.travelport.com/ to know more about HCP. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by RajshreeTathe** [comment]
Hi Vivek,

We have travelport hotel content plus credentials , how we can use these api's. 

I am trying to fetch result using below request but getting authentication error. Can you please suggest how can I use these api or what methodology should I use to implement this api with travleport.

Request : <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://www.opentravel.org/OTA/2003/05">
   <soap:Header/>
   <soap:Body>
      <OTA_HotelDescriptiveInfoRQ TimeStamp="2017-09-07T09:30:47.0Z" Version="1.0" Target="Test" EchoToken="ternal">
         <POS>
            <Source>
               <BookingChannel Type="2">
                  <CompanyName Code="HCP_CHEAPTRAVEL18" CompanyShortName="Cheap Travel Calendar"/>
               </BookingChannel>
            </Source>
         </POS>
         <HotelDescriptiveInfos>
            <HotelDescriptiveInfo BrandCode="BW" HotelCode="BW45029" HotelCodeContext="1P"/>
         </HotelDescriptiveInfos>
      </OTA_HotelDescriptiveInfoRQ>
   </soap:Body>
</soap:Envelope>

Endpoint URL : https://americas.copy-webservices.travelport.com/B2BGateway/connect/HotelContent/HotelDescriptiveInfo

Thanks,
Rajshree

**Comment by vivekjyotipramanik** [comment]
Hi RajshreeTathe,

We do not provide support for HotelContentPlus through github. Please create a MyTravelport ticket for HotelContentPlus and we will pick up the ticket from there. Thanks.
