### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by HipeL** [Travelport/travelport-uapi-tutorial-php#62]
Hello, it's me again... I'm attempting to try the HotelBook Req, and as I did with the other requests still assemblying some logic behind but starting from a really basic one(Picking up XML from examples and almost manually changing the data inside them, before changing alot of properties and such).
But on this request I keep getting this error and it's a little vague so I'm unnable to trace it... 
I would gladly accept any little help, thank you in advance :)

[bookRequest.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/761645/bookRequest.txt)
[bookResponse.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/761646/bookResponse.txt)

Sérgio Reis

**Comment by vivekjyotipramanik** [comment]
Hi HipeL,

Could you please try the booking traveler name as <com:bookingtravelername first="S**e**rgio" last="Reis" prefix="Mr">. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by HipeL** [comment]
My bad... sorry for this awfull quetion. Before I close this question and let me take a little chance of asking some questions not directly code related.

1. - According to the payments, does the HotelCreateReservationReq handles the payments or it is required to use a 3rd party payment system (like paypal stripe and etc)?
2. - At least for me, I can't get the demo to show me more information on a hotel ( https://i.gyazo.com/2a3869fd1e6f1ed49cff4de86cb16fb1.gif )
3. - Is it in any plan a REST API / SoapClient php implementation comming soon?
4. - Would travelport be intrested in a Laravel wrapper?

Thank you once again, you've been more than a great help

**Comment by NirandaG** [comment]
Hi HipeL,

Please find the below explanations.

1 - HotelCreateReservationReq does not handle the payments. You need to integrate your own payment method with validations.

2 - The hotel description can be retrieved from HotelDetailsReq XML.
https://support.travelport.com/webhelp/uapi/uAPI.htm#SampleWeb/Individual_Sample_Pages/007-1G_Hotel_MinimumData.htm%3FTocPath%3DSamples%7CXML%2520Samples%2520%7CHotel%2520Samples%7CHotel%2520Workflows%7CGalileo%2520(1G)%2520Workflows%7C_____1
Please let me know if this does not work for you.

3 - We do not have sample codes for most of the transactions based on PHP.

4 - I am not sure what you meant by this question.

Thank you,
B.Rgds,
Niranda

**Comment by vivekjyotipramanik** [comment]
Hi HipeL,

We do have a RestAPi sample for Hotel, using Universal API in a mobile environmentwith JSON messages over XML.The App and the JSON API are intended for testing purposes. Although this is for testing purposes only. Please find below the link. Thanks.

https://github.com/Travelport/HotelBooker

Thanks & Regards
Vivekjyoti Pramanik

**Comment by HipeL** [comment]
Thanks for both answers and sorry it took me a while to answer back
@NirandaG 
2 - I was already doing such request and working with it, I only wanted to see in what manner the demo itself tackled it
4 - If travelport would be intrested in a php framework (laravel) implementation of the API

@vivekjyotipramanik 
If the JSON API would to go live I would most certainly use it, for now i'll stick with what's provided

Thank you both once again

**Comment by ahmedaisar** [comment]
Hoping for a day TravelPort would migrate from XML to REST - it would then be as easy as pie for us developers.
