### ISSUE TITLE
3100 : INVALID INPUT

### ISSUE THREAD

**Issue by praise549** [Travelport/travelport-uapi-tutorial-php#70]
[BookingRes.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/1006693/BookingRes.txt)
[BookingReq.txt](https://github.com/Travelport/travelport-uapi-tutorial-php/files/1006692/BookingReq.txt)

Hi, 
I am getting a warning like 3100 : INVALID INPUT and Some of the requested AirPricingInfos could not be saved for the requested provider.
I get this error only going for booking with ADULT + CHILD + I

NFANT and there is no issue in booking the combination like
1. Adult
2.Adult+Child
3.Adult+Infant

**Comment by vivekjyotipramanik** [comment]
Hi praise549,

Could you please remove the PlatingCarrier attribute from the AirPricingInfo and give it a try. Please let us know how it goes. Thanks.

**Comment by praise549** [comment]
Hi @vivekjyotipramanik ,
 I had made the changes in xml, that you recommended and now i can able to do booking and ticketing. Thank you for the help
