### ISSUE TITLE
(76): Authentication credentials are invalid

### ISSUE THREAD

**Issue by lemonkazi** [Travelport/travelport-uapi-tutorial-php#75]
I can see an issue when tried my credential 
Please check Below code.
$TARGETBRANCH = 'P105390';
$CREDENTIALS = 'Universal API/uAPI-834741898:DPPPdXHy65r6ZwHADhGRwAqD2';
$Provider = '1G';
$soap_do = curl_init ("https://apac.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");

Testing source
http://apitest.learnindoorgrowing.com/phpSample_Air.php

When unlocked that it was displaying error code 76 "Result Error Message Response (76): Authentication credentials are invalid."

But I checked again and again my credential was ok. Travelport provided me this preproduction credential  for 30 days.
I also tried for another trial credential but in that reply email they told me it will take 10 days to give me another credential.

**Comment by vivekjyotipramanik** [comment]
Hi lemonkazi,

Could you please change your password to the below. Please let us know how it goes. Thanks.

r4AGq557

**Comment by lemonkazi** [comment]
@vivekjyotipramanik 
Thanks . Your new password worked for me.
