### ISSUE TITLE
Fatal error: Encoding Error! in D:\MAMP\htdocs\travelport\Air\phpSample_Air.php on line 105

### ISSUE THREAD

**Issue by abrar7866** [Travelport/travelport-uapi-tutorial-php#78]
Hi,

I'm getting an error while running this file "fatal error: encoding error" as mentioned in the title.

Here is my code:

`<?php 
/* 
* uAPI sample communication in php language 
* 
* This example requires the cURL library to be installed and working. 
* 
* Please note, in the sample code below, the variable $CREDENTIALS is created by binding your username and password together with a colon e.g. 
* 
* $auth = base64_encode("Universal API/API1234567:mypassword"); 
* 
* The variable $TARGETBRANCH should be set to the TargetBranch provided by Travelport. 
* 
* (C) 2014 Travelport, Inc. 
* This code is for illustration purposes only. 
*/

error_reporting(E_ALL); ini_set('display_errors', 1); 

$TARGETBRANCH = 'P105201';
$CREDENTIALS = "Universal API/uAPI4816366251:E9KzymQek7ztGC2QcXG2R8m5E";
$Provider = '1G'; // Any provider you want to use like 1G/1P/1V/ACH

$message = <<<EOM
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq TraceId="trace" AuthorizedBy="user" TargetBranch="$TARGETBRANCH" xmlns:air="http://www.travelport.com/schema/air_v29_0" xmlns:com="http://www.travelport.com/schema/common_v29_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="LGW"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="EDI"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2014-12-31">
            </air:SearchDepTime>            
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="$Provider"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
EOM;

$file = "001-".$Provider."_AirAvailabilityReq.xml"; // file name to save the request xml for test only(if you want to save the request/response)
prettyPrint($message,$file);//call function to pretty print xml

$auth = base64_encode("Universal API/uAPI4816366251:E9KzymQek7ztGC2QcXG2R8m5E"); 
$soap_do = curl_init ("https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/UtilService");
$header = array(
"Content-Type: text/xml;charset=UTF-8", 
"Accept: gzip,deflate", 
"Cache-Control: no-cache", 
"Pragma: no-cache", 
"SOAPAction: \"\"",
"Authorization: Basic $auth", 
"Content-length: ".strlen($message),
); 
//curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 30); 
//curl_setopt($soap_do, CURLOPT_TIMEOUT, 30); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($soap_do, CURLOPT_POST, true ); 
curl_setopt($soap_do, CURLOPT_POSTFIELDS, $message); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true); // this will prevent the curl_exec to return result and will let us to capture output
$return = curl_exec($soap_do);

$file = "001-".$Provider."_AirAvailabilityRsp.xml"; // file name to save the response xml for test only(if you want to save the request/response)
$content = prettyPrint($return,$file);
parseOutput($content);
//print '<br>';
//echo $return;
//print '<br>';
//print_r(curl_getinfo($soap_do));

//Pretty print XML
function prettyPrint($result,$file){
	$dom = new DOMDocument;
	$dom->preserveWhiteSpace = false;
	$dom->loadXML($result);
	$dom->formatOutput = true;		
	//call function to write request/response in file	
	outputWriter($file,$dom->saveXML());
	return $dom->saveXML();
}

//function to write output in a file
function outputWriter($file,$content){	
	file_put_contents($file, $content); // Write request/response and save them in the File
}

function parseOutput($content){	//parse the Search response to get values to use in detail request
	$AirAvailabilitySearchRsp = $content; //use this if response is not saved anywhere else use above variable
	//echo $AirAvailabilitySearchRsp;
	$xml = simplexml_load_String("$AirAvailabilitySearchRsp", null, null, 'SOAP', true);	
	
	if($xml)
		echo "Processing! Please wait!";
	else{
		trigger_error("Encoding Error!", E_USER_ERROR);
	}

	$Results = $xml->children('SOAP',true);
	foreach($Results->children('SOAP',true) as $fault){
		if(strcmp($fault->getName(),'Fault') == 0){
			trigger_error("Error occurred request/response processing!", E_USER_ERROR);
		}
	}
	
	$count = 0;
	$fileName = "flights.txt";
	if(file_exists($fileName)){
		file_put_contents($fileName, "");
	}
	foreach($Results->children('air',true) as $nodes){
		foreach($nodes->children('air',true) as $hsr){
			if(strcmp($hsr->getName(),'AirSegmentList') == 0){
				foreach($hsr->children('air',true) as $hp){
					if(strcmp($hp->getName(),'AirSegment') == 0){
						$count = $count + 1;
						file_put_contents($fileName,"\r\n"."Air Segment ".$count."\r\n"."\r\n", FILE_APPEND);
						foreach($hp->attributes() as $a => $b	){
								$GLOBALS[$a] = "$b";
								//echo "$a"." : "."$b";
								file_put_contents($fileName,$a." : ".$b."\r\n", FILE_APPEND);
						}												
					}					
				}
			}
			//break;
		}
	}
	$Token = 'Token';
	$TokenKey = 'TokenKey';
	$fileName = "tokens.txt";
	if(file_exists($fileName)){
		file_put_contents($fileName, "");
	}
	foreach($Results->children('air',true) as $nodes){
		foreach($nodes->children('air',true) as $hsr){
			if(strcmp($hsr->getName(),'HostTokenList') == 0){			
				foreach($hsr->children('common_v29_0', true) as $ht){
					if(strcmp($ht->getName(), 'HostToken') == 0){
						$GLOBALS[$Token] = $ht[0];
						foreach($ht->attributes() as $a => $b){
							if(strcmp($a, 'Key') == 0){
								file_put_contents($fileName,$TokenKey.":".$b."\r\n", FILE_APPEND);
							}
						}						
						file_put_contents($fileName,$Token.":".$ht[0]."\r\n", FILE_APPEND);
					}
				}
			}
		}
	}
	
	echo "\r\n"."Processing Done. Please check results in files.";

}

var_dump();
?>
`

**Comment by abrar7866** [comment]
@tedbeatie @alellington @mofreeman Please can you help me out?

**Comment by vivekjyotipramanik** [comment]
Hi abrar7866,

The account you are using is locked. We are working on to unlock it. We will notify you as soon as it is resolved. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi abrar7866,

The account is unlocked now. Could you please try again. Please let us know how it goes. Thanks.

**Comment by abrar7866** [comment]
Thank you for unlocking the account. I've one more query.

We've enabled the 30 day trial of Travelport API and studied the searching the flights module closely and found that the booking is not available in the demo mode.

I would also appreciate if you could help us out in the booking module so that the end customers could buy the flights via credit card etc.

**Comment by vivekjyotipramanik** [comment]
Hi abrar7866,

Booking is available in demomode with preProduction selection. In production it is not available. But if you select the preProduction, you will be able to do booking as well. With Trial credentials as well booking is available in Preproduction. Please let us know how it goes. Thanks.

**Comment by abrar7866** [comment]
Hi Vivek,

Thank you for your reply.

I want to apply for pre-production system to access the booking module. Can you please guide me how can I apply for booking api?

Can you please post some links or guides or requirements of applying for pre-production and if its free or paid.

Thanks,
Abrar

**Comment by vivekjyotipramanik** [comment]
Hi abrar7866,

Using trial credentials as well you can use booking and actuallly complete booking. The ticketing is not available with trial credentials. Trial credentials is actually PreProduction credential with limited access.

The full access preproduction credentials can be received after signing a contract with Travelport and there is a cost associated with it. Please use the contact us link in developer network and Sales team will contact you regarding this. Thanks.

**Comment by abrar7866** [comment]
Hi Vivek,

We're in the process of purchasing the API. In the mean time, we're working on the interface.

While developing interface, I've some questions to ask, my first question is that how could we fetch the source and destination from the list when users try to input the airport code in the box. Should we use Google API for this or is there any xml file or anything that could help us fetch all the airport codes.

Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi abrar7866,

There is UtilService in UAPI with ReferenceDataRetrieveReq which can provide all the Airport names and their codes. Please find below the link with all the details. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Getting_Started/Design_Considerations/Reference_Data.htm%3FTocPath%3DGetting%2520Started%7CUniversal%2520API%2520Overview%7CDesign%2520Considerations%7C_____5

**Comment by vivekjyotipramanik** [comment]
Hi jakircomilla1,

Please share the XML response you are receiving. Thanks.

**Comment by jakircomilla1** [comment]
Hello Vivekjyotipramanik,
Thank you very much for your quick response.
Here is my XML response-
<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <SOAP-ENV:faultcode>76</SOAP-ENV:faultcode>
      <SOAP-ENV:faultstring>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:faultstring>
      <SOAP-ENV:faultactor>            </SOAP-ENV:faultactor>
      <SOAP-ENV:detail>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:detail>
    </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by vivekjyotipramanik** [comment]
Hi jakircomilla1,

The account is locked. Could you please provide your username and TargetBranch you are using and we will unlock it. Thanks.

**Comment by jakircomilla1** [comment]
Hi vivekjyotipramanik,
TargetBranc: P7039096
username: Universal API/uAPI8383229630-d0cbb10

**Comment by jakircomilla1** [comment]
Hello vivekjyotipramanik,

I ma still stuck there. Can you please help me...

**Comment by vivekjyotipramanik** [comment]
Hi jakircomilla1,

We will notify you as soon as the issue is fixed. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi jakircomilla1,

The account is not locked. Looks like you are using incorrect username. There is a b at the end of the username which you are not using. Please use the correct username and it should work fine. Thanks.

username: Universal API/uAPI8383229630-d0cbb10b

**Comment by jakircomilla1** [comment]
Dear Vivekjyotipramanik,
Thank you very much for you kind help.
Problem solve :).

**Comment by rajeshmuduli** [comment]
Hello Sir,
I am getting the error : Fatal error: Encoding Error! in /var/www/html/php_SampleAir.php on line 103
which is my code - trigger_error("Encoding Error!", E_USER_ERROR);
Please help me.

**Comment by vivekjyotipramanik** [comment]
Hi  rajeshmuduli,

Please share the exact request xml you are sending. Could you please also try your credentials in demosite to check if it is working fine there . Thanks.

http://demo.travelportuniversalapi.com/

**Comment by rajeshmuduli** [comment]
<?php 
/* 
* uAPI sample communication in php language 
* 
* This example requires the cURL library to be installed and working. 
* 
* Please note, in the sample code below, the variable $CREDENTIALS is created by binding your username and password together with a colon e.g. 
* 
* $auth = base64_encode("Universal API/API1234567:mypassword"); 
* 
* The variable $TARGETBRANCH should be set to the TargetBranch provided by Travelport. 
* 
* (C) 2014 Travelport, Inc. 
* This code is for illustration purposes only. 
*/
$TARGETBRANCH = 'P7038859';
$CREDENTIALS = 'Universal API/uAPI2061352272-1951691b:kTh4NdtecXPWZxsjhSjNkxTgS';
$Provider = '1G'; // Any provider you want to use like 1G/1P/1V/ACH

$message = <<<EOM
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq TraceId="trace" AuthorizedBy="user" TargetBranch="$TARGETBRANCH" xmlns:air="http://www.travelport.com/schema/air_v29_0" xmlns:com="http://www.travelport.com/schema/common_v29_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="LGW"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="EDI"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2014-12-31">
            </air:SearchDepTime>            
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="$Provider"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
EOM;

$file = "001-".$Provider."_AirAvailabilityReq.xml"; // file name to save the request xml for test only(if you want to save the request/response)
prettyPrint($message,$file);//call function to pretty print xml

$auth = base64_encode("Universal API/uAPI2061352272-1951691b:kTh4NdtecXPWZxsjhSjNkxTgS"); 
$soap_do = curl_init ("https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");
$header = array(
"Content-Type: text/xml;charset=UTF-8", 
"Accept: gzip,deflate", 
"Cache-Control: no-cache", 
"Pragma: no-cache", 
"SOAPAction: \"\"",
"Authorization: Basic $auth", 
"Content-length: ".strlen($message),
); 
//curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 30); 
//curl_setopt($soap_do, CURLOPT_TIMEOUT, 30); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($soap_do, CURLOPT_POST, true ); 
curl_setopt($soap_do, CURLOPT_POSTFIELDS, $message); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true); // this will prevent the curl_exec to return result and will let us to capture output
$return = curl_exec($soap_do);

$file = "001-".$Provider."_AirAvailabilityRsp.xml"; // file name to save the response xml for test only(if you want to save the request/response)
$content = prettyPrint($return,$file);
parseOutput($content);
//print '<br>';
//echo $return;
//print '<br>';
//print_r(curl_getinfo($soap_do));

//Pretty print XML
function prettyPrint($result,$file){
    $dom = new DOMDocument;
    $dom->preserveWhiteSpace = false;
    $dom->loadXML($result);
    $dom->formatOutput = true;      
    //call function to write request/response in file   
    outputWriter($file,$dom->saveXML());
    return $dom->saveXML();
}

//function to write output in a file
function outputWriter($file,$content){  
    file_put_contents($file, $content); // Write request/response and save them in the File
}

function parseOutput($content){ //parse the Search response to get values to use in detail request
    $AirAvailabilitySearchRsp = $content; //use this if response is not saved anywhere else use above variable
    //echo $AirAvailabilitySearchRsp;
    $xml = simplexml_load_String("$AirAvailabilitySearchRsp", null, null, 'SOAP', true);    
    
    if($xml)
        echo "Processing! Please wait!";
    else{
        trigger_error("Encoding Error!", E_USER_ERROR);
    }

    $Results = $xml->children('SOAP',true);
    foreach($Results->children('SOAP',true) as $fault){
        if(strcmp($fault->getName(),'Fault') == 0){
            trigger_error("Error occurred request/response processing!", E_USER_ERROR);
        }
    }
    
    $count = 0;
    $fileName = "flights.txt";
    if(file_exists($fileName)){
        file_put_contents($fileName, "");
    }
    foreach($Results->children('air',true) as $nodes){
        foreach($nodes->children('air',true) as $hsr){
            if(strcmp($hsr->getName(),'AirSegmentList') == 0){
                foreach($hsr->children('air',true) as $hp){
                    if(strcmp($hp->getName(),'AirSegment') == 0){
                        $count = $count + 1;
                        file_put_contents($fileName,"\r\n"."Air Segment ".$count."\r\n"."\r\n", FILE_APPEND);
                        foreach($hp->attributes() as $a => $b   ){
                                $GLOBALS[$a] = "$b";
                                //echo "$a"." : "."$b";
                                file_put_contents($fileName,$a." : ".$b."\r\n", FILE_APPEND);
                        }                                               
                    }                   
                }
            }
            //break;
        }
    }
    $Token = 'Token';
    $TokenKey = 'TokenKey';
    $fileName = "tokens.txt";
    if(file_exists($fileName)){
        file_put_contents($fileName, "");
    }
    foreach($Results->children('air',true) as $nodes){
        foreach($nodes->children('air',true) as $hsr){
            if(strcmp($hsr->getName(),'HostTokenList') == 0){           
                foreach($hsr->children('common_v29_0', true) as $ht){
                    if(strcmp($ht->getName(), 'HostToken') == 0){
                        $GLOBALS[$Token] = $ht[0];
                        foreach($ht->attributes() as $a => $b){
                            if(strcmp($a, 'Key') == 0){
                                file_put_contents($fileName,$TokenKey.":".$b."\r\n", FILE_APPEND);
                            }
                        }                       
                        file_put_contents($fileName,$Token.":".$ht[0]."\r\n", FILE_APPEND);
                    }
                }
            }
        }
    }
    
    echo "\r\n"."Processing Done. Please check results in files.";

}
//var_dump();
?>

**Comment by rajeshmuduli** [comment]
<?php 
/* 
* uAPI sample communication in php language 
* 
* This example requires the cURL library to be installed and working. 
* 
* Please note, in the sample code below, the variable $CREDENTIALS is created by binding your username and password together with a colon e.g. 
* 
* $auth = base64_encode("Universal API/API1234567:mypassword"); 
* 
* The variable $TARGETBRANCH should be set to the TargetBranch provided by Travelport. 
* 
* (C) 2014 Travelport, Inc. 
* This code is for illustration purposes only. 
*/
$TARGETBRANCH = 'P7038859';
$CREDENTIALS = 'Universal API/uAPI2061352272-1951691b:kTh4NdtecXPWZxsjhSjNkxTgS';
$Provider = '1G'; // Any provider you want to use like 1G/1P/1V/ACH

$message = <<<EOM
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq TraceId="trace" AuthorizedBy="user" TargetBranch="$TARGETBRANCH" xmlns:air="http://www.travelport.com/schema/air_v29_0" xmlns:com="http://www.travelport.com/schema/common_v29_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="LGW"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="EDI"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2014-12-31">
            </air:SearchDepTime>            
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="$Provider"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
EOM;

$file = "001-".$Provider."_AirAvailabilityReq.xml"; // file name to save the request xml for test only(if you want to save the request/response)
prettyPrint($message,$file);//call function to pretty print xml

$auth = base64_encode("Universal API/uAPI2061352272-1951691b:kTh4NdtecXPWZxsjhSjNkxTgS"); 
$soap_do = curl_init ("https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");
$header = array(
"Content-Type: text/xml;charset=UTF-8", 
"Accept: gzip,deflate", 
"Cache-Control: no-cache", 
"Pragma: no-cache", 
"SOAPAction: \"\"",
"Authorization: Basic $auth", 
"Content-length: ".strlen($message),
); 
//curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 30); 
//curl_setopt($soap_do, CURLOPT_TIMEOUT, 30); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($soap_do, CURLOPT_POST, true ); 
curl_setopt($soap_do, CURLOPT_POSTFIELDS, $message); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true); // this will prevent the curl_exec to return result and will let us to capture output
$return = curl_exec($soap_do);

$file = "001-".$Provider."_AirAvailabilityRsp.xml"; // file name to save the response xml for test only(if you want to save the request/response)
$content = prettyPrint($return,$file);
parseOutput($content);
//print '<br>';
//echo $return;
//print '<br>';
//print_r(curl_getinfo($soap_do));

//Pretty print XML
function prettyPrint($result,$file){
    $dom = new DOMDocument;
    $dom->preserveWhiteSpace = false;
    $dom->loadXML($result);
    $dom->formatOutput = true;      
    //call function to write request/response in file   
    outputWriter($file,$dom->saveXML());
    return $dom->saveXML();
}

//function to write output in a file
function outputWriter($file,$content){  
    file_put_contents($file, $content); // Write request/response and save them in the File
}

function parseOutput($content){ //parse the Search response to get values to use in detail request
    $AirAvailabilitySearchRsp = $content; //use this if response is not saved anywhere else use above variable
    //echo $AirAvailabilitySearchRsp;
    $xml = simplexml_load_String("$AirAvailabilitySearchRsp", null, null, 'SOAP', true);    
    
    if($xml)
        echo "Processing! Please wait!";
    else{
        trigger_error("Encoding Error!", E_USER_ERROR);
    }

    $Results = $xml->children('SOAP',true);
    foreach($Results->children('SOAP',true) as $fault){
        if(strcmp($fault->getName(),'Fault') == 0){
            trigger_error("Error occurred request/response processing!", E_USER_ERROR);
        }
    }
    
    $count = 0;
    $fileName = "flights.txt";
    if(file_exists($fileName)){
        file_put_contents($fileName, "");
    }
    foreach($Results->children('air',true) as $nodes){
        foreach($nodes->children('air',true) as $hsr){
            if(strcmp($hsr->getName(),'AirSegmentList') == 0){
                foreach($hsr->children('air',true) as $hp){
                    if(strcmp($hp->getName(),'AirSegment') == 0){
                        $count = $count + 1;
                        file_put_contents($fileName,"\r\n"."Air Segment ".$count."\r\n"."\r\n", FILE_APPEND);
                        foreach($hp->attributes() as $a => $b   ){
                                $GLOBALS[$a] = "$b";
                                //echo "$a"." : "."$b";
                                file_put_contents($fileName,$a." : ".$b."\r\n", FILE_APPEND);
                        }                                               
                    }                   
                }
            }
            //break;
        }
    }
    $Token = 'Token';
    $TokenKey = 'TokenKey';
    $fileName = "tokens.txt";
    if(file_exists($fileName)){
        file_put_contents($fileName, "");
    }
    foreach($Results->children('air',true) as $nodes){
        foreach($nodes->children('air',true) as $hsr){
            if(strcmp($hsr->getName(),'HostTokenList') == 0){           
                foreach($hsr->children('common_v29_0', true) as $ht){
                    if(strcmp($ht->getName(), 'HostToken') == 0){
                        $GLOBALS[$Token] = $ht[0];
                        foreach($ht->attributes() as $a => $b){
                            if(strcmp($a, 'Key') == 0){
                                file_put_contents($fileName,$TokenKey.":".$b."\r\n", FILE_APPEND);
                            }
                        }                       
                        file_put_contents($fileName,$Token.":".$ht[0]."\r\n", FILE_APPEND);
                    }
                }
            }
        }
    }
    
    echo "\r\n"."Processing Done. Please check results in files.";

}
//var_dump();
?>

**Comment by rajeshmuduli** [comment]
Dear Sir,
Demosite is working fine (http://demo.travelportuniversalapi.com/)  But in the above code i got an error of : Fatal error: Encoding Error! in /var/www/html/php_SampleAir.php on line 103.

**Comment by vivekjyotipramanik** [comment]
Hi rajeshmuduli,

In the above request you are sending AirAvailability request with date 4 years back (2014-12-31). Please change the date to a future date. Thanks.

**Comment by sujithgnair** [comment]
My UserID is : Universal API/uAPI9703103917-79d95180 
Branch Code: P7033281,

Iam getting a an error as follows:
Fatal error: Encoding Error! in D:\xampp\htdocs\test\travelport\Air\phpSample_Air.php on line 108. Do you think the problem is with account being locked. Can you pls reconfirm me on the same. Thx in advance.

**Comment by Technovier** [comment]
I am getting the error : Fatal error: Encoding Error! in /opt/lampp/htdocs/travelport-uapi-tutorial-php-master/Air/phpSample_Air.php on line 102

My code is below:
```
<?php 
/* 
* uAPI sample communication in php language 
* 
* This example requires the cURL library to be installed and working. 
* 
* Please note, in the sample code below, the variable $CREDENTIALS is created by binding your username and password together with a colon e.g. 
* 
* $auth = base64_encode("Universal API/API1234567:mypassword"); 
* 
* The variable $TARGETBRANCH should be set to the TargetBranch provided by Travelport. 
* 
* (C) 2014 Travelport, Inc. 
* This code is for illustration purposes only. 
*/
$TARGETBRANCH = 'P7002731';
$CREDENTIALS = 'Universal API/uAPI7662861526-8cd988d4:PUniversal API/uAPI7662861526-8cd988d4';
$Provider = '1G'; // Any provider you want to use like 1G/1P/1V/ACH

$message = <<<EOM
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">   <soapenv:Header/>
   <soapenv:Body>
      <air:AvailabilitySearchReq AuthorizedBy="user" TargetBranch="$TARGETBRANCH" TraceId="trace" xmlns:air="http://www.travelport.com/schema/air_v26_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI" xmlns:com="http://www.travelport.com/schema/common_v26_0"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="CDG" xmlns:com="http://www.travelport.com/schema/common_v26_0"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="CHA" xmlns:com="http://www.travelport.com/schema/common_v26_0"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2014-06-19"/>
			<air:AirLegModifiers>
               <air:PreferredCabins>
                  <com:CabinClass Type="Economy" xmlns:com="http://www.travelport.com/schema/common_v26_0"/>
               </air:PreferredCabins>
            </air:AirLegModifiers>
         </air:SearchAirLeg>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="CHA" xmlns:com="http://www.travelport.com/schema/common_v26_0"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="CDG" xmlns:com="http://www.travelport.com/schema/common_v26_0"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2014-06-28"/>
			<air:AirLegModifiers>
               <air:PreferredCabins>
                  <com:CabinClass Type="Economy" xmlns:com="http://www.travelport.com/schema/common_v26_0"/>
               </air:PreferredCabins>
            </air:AirLegModifiers>
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="$Provider" xmlns:com="http://www.travelport.com/schema/common_v26_0"/>
            </air:PreferredProviders>
         </air:AirSearchModifiers>
      </air:AvailabilitySearchReq>
   </soapenv:Body>
</soapenv:Envelope>
EOM;

//$file = "001-".$Provider."_AirAvailabilityReq.xml"; // file name to save the request xml for test only(if you want to save the request/response)
//prettyPrint($message,$file);//call function to pretty print xml

$auth = base64_encode("$CREDENTIALS"); 
$soap_do = curl_init ("https://emea.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/AirService");
$header = array(
"Content-Type: text/xml;charset=UTF-8", 
"Accept: gzip,deflate", 
"Cache-Control: no-cache", 
"Pragma: no-cache", 
"SOAPAction: \"\"",
"Authorization: Basic $auth", 
"Content-length: ".strlen($message),
); 
//curl_setopt($soap_do, CURLOPT_CONNECTTIMEOUT, 30); 
//curl_setopt($soap_do, CURLOPT_TIMEOUT, 30); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($soap_do, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($soap_do, CURLOPT_POST, true ); 
curl_setopt($soap_do, CURLOPT_POSTFIELDS, $message); 
curl_setopt($soap_do, CURLOPT_HTTPHEADER, $header);
curl_setopt($soap_do, CURLOPT_RETURNTRANSFER, true); // this will prevent the curl_exec to return result and will let us to capture output
$return = curl_exec($soap_do);

//$file = "001-".$Provider."_AirAvailabilityRsp.xml"; // file name to save the response xml for test only(if you want to save the request/response)
//$content = prettyPrint($return,$file);
parseOutput($return);
//print '<br>';
//echo $return;
//print '<br>';
//print_r(curl_getinfo($soap_do));

//Pretty print XML
function prettyPrint($result,$file){
	$dom = new DOMDocument;
	$dom->preserveWhiteSpace = false;
	$dom->loadXML($result);
	$dom->formatOutput = true;		
	//call function to write request/response in file	
	outputWriter($file,$dom->saveXML());
	return $dom->saveXML();
}

//function to write output in a file
function outputWriter($file,$content){	
	file_put_contents($file, $content); // Write request/response and save them in the File
}

function parseOutput($content){	//parse the Search response to get values to use in detail request
	$AirAvailabilitySearchRsp = $content; //use this if response is not saved anywhere else use above variable
	//echo $AirAvailabilitySearchRsp;
	$xml = simplexml_load_String("$AirAvailabilitySearchRsp", null, null, 'SOAP', true);
	
	if($xml)
		echo "Processing! Please wait!";
	else{
		trigger_error("Encoding Error!", E_USER_ERROR);
	}

	$Results = $xml->children('SOAP',true);
	foreach($Results->children('SOAP',true) as $fault){
		if(strcmp($fault->getName(),'Fault') == 0){
			trigger_error("Error occurred request/response processing!", E_USER_ERROR);
		}
	}
	
	$count = 0;
	$fileName = "flights.txt";
	if(file_exists($fileName)){
		file_put_contents($fileName, "");
	}
	foreach($Results->children('air',true) as $nodes){
		foreach($nodes->children('air',true) as $hsr){
			if(strcmp($hsr->getName(),'AirSegmentList') == 0){
				foreach($hsr->children('air',true) as $hp){
					if(strcmp($hp->getName(),'AirSegment') == 0){
						$count = $count + 1;
						file_put_contents($fileName,"\r\n"."Air Segment ".$count."\r\n"."\r\n", FILE_APPEND);
						foreach($hp->attributes() as $a => $b	){
								$GLOBALS[$a] = "$b";
								//echo "$a"." : "."$b";
								file_put_contents($fileName,$a." : ".$b."\r\n", FILE_APPEND);
						}												
					}					
				}
			}
			//break;
		}
	}
	$Token = 'Token';
	$TokenKey = 'TokenKey';
	$fileName = "tokens.txt";
	if(file_exists($fileName)){
		file_put_contents($fileName, "");
	}
	foreach($Results->children('air',true) as $nodes){
		foreach($nodes->children('air',true) as $hsr){
			if(strcmp($hsr->getName(),'HostTokenList') == 0){			
				foreach($hsr->children('common_v29_0', true) as $ht){
					if(strcmp($ht->getName(), 'HostToken') == 0){
						$GLOBALS[$Token] = $ht[0];
						foreach($ht->attributes() as $a => $b){
							if(strcmp($a, 'Key') == 0){
								file_put_contents($fileName,$TokenKey.":".$b."\r\n", FILE_APPEND);
							}
						}						
						file_put_contents($fileName,$Token.":".$ht[0]."\r\n", FILE_APPEND);
					}
				}
			}
		}
	}
	
	echo "\r\n"."Processing Done. Please check results in files.";

}
'done'
?>
```

**Comment by vivekjyotipramanik** [comment]
Hi Technovier,

The sample is using very old version of schema. Please use latest version of schema which is version 48. Thanks.

**Comment by mariyamh** [comment]
Fatal error: Encoding Error! in C:\xampp\htdocs\travelport-uapi-tutorial-php-master\Air\phpSample_Air.php on line 103

**Comment by LycanDev-1** [comment]
hi @vivekjyotipramanik 

$TARGETBRANCH = 'P7009927';
$CREDENTIALS = 'Universal API/UAPI3568924042-3768c943

I am also not able to access the api getting following response

<SOAP-ENV:Fault xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:faultcode>76</SOAP-ENV:faultcode>
  <SOAP-ENV:faultstring>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:faultstring>
  <SOAP-ENV:faultactor></SOAP-ENV:faultactor>
  <SOAP-ENV:detail>Authentication Result Error Message Response  (76): Authentication credentials are invalid.</SOAP-ENV:detail>
</SOAP-ENV:Fault>
