### ISSUE TITLE
Search Modifiers

### ISSUE THREAD

**Issue by nitincdac** [Travelport/travelport-uapi-tutorial-php#81]
Hello

I want to add "PermittedCabins" modifiers to the request. But I am getting error. Please check the request. 

Request : 

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header/>
    <soapenv:Body>
        <air:LowFareSearchReq TraceId="trace" AuthorizedBy="user" SolutionResult="true" TargetBranch="P108164" xmlns:air="http://www.travelport.com/schema/air_v33_0" xmlns:com="http://www.travelport.com/schema/common_v33_0">
            <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
            <air:SearchAirLeg>
                <air:SearchOrigin>
                    <com:Airport Code="YUL"/>
                </air:SearchOrigin>
                <air:SearchDestination>
                    <com:Airport Code="YYZ"/>
                </air:SearchDestination>
                <air:SearchDepTime PreferredTime="2017-10-07"/>
            </air:SearchAirLeg>
            <air:AirSearchModifiers>
                <air:PreferredProviders>
                    <com:Provider Code="1P"/>
                </air:PreferredProviders>
                <air:PermittedCabins>
                    <com:Cabin Class="Economy"/>
                </air:PermittedCabins>
            </air:AirSearchModifiers>                        
            <com:SearchPassenger BookingTravelerRef="1" Code="ADT"/>
        </air:LowFareSearchReq>
    </soapenv:Body>
</soapenv:Envelope>

Also please tell me how do I add multiple modifiers to one request, like if I want to add 
1. PermittedCabins
2. Travellers Type(adult-2,child-1,infant-1) 
3. Airline Code
etc.  in one request only

Please help. 
Thanks

**Comment by vivekjyotipramanik** [comment]
Hi nitincdac,

Please find below the corrected request and also I have added the requested modifiers. Please let us know how it goes. Thanks.

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <air:LowFareSearchReq TraceId="trace" AuthorizedBy="user" SolutionResult="true" TargetBranch="${Properties Air#EB}" xmlns:air="http://www.travelport.com/schema/air_v42_0" xmlns:com="http://www.travelport.com/schema/common_v42_0">
         <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
         <air:SearchAirLeg>
            <air:SearchOrigin>
               <com:Airport Code="YUL"/>
            </air:SearchOrigin>
            <air:SearchDestination>
               <com:Airport Code="YYZ"/>
            </air:SearchDestination>
            <air:SearchDepTime PreferredTime="2017-10-07"/>
         </air:SearchAirLeg>
         <air:AirSearchModifiers>
            <air:PreferredProviders>
               <com:Provider Code="1V"/>
            </air:PreferredProviders>
            <air:PermittedCarriers>
               <com:Carrier Code="AC"/>
            </air:PermittedCarriers>
            <air:PermittedCabins>
               <com:CabinClass Type="Economy"/>
            </air:PermittedCabins>
         </air:AirSearchModifiers>
         <com:SearchPassenger BookingTravelerRef="1" Code="ADT"/>
      </air:LowFareSearchReq>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by nitincdac** [comment]
perfect !!! working.... Thanks
