### ISSUE TITLE
Segments & transit's ??

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#86]
Dear Sir, 
Please let us know how to connect transit's segments together as we are getting this result below as showing traveling from DEL to CGK via KUL but there is no common between both segments to connect them how we do this please also for example from DEL to SIN via KUL.. 

Air Segment 1

Key : asfh927Q2BKAEGVsIAAAAA==
Group : 0
Carrier : MH
FlightNumber : 173
Origin : DEL
Destination : KUL
DepartureTime : 2017-09-01T13:10:00.000+05:30
ArrivalTime : 2017-09-01T21:05:00.000+08:00
FlightTime : 325
TravelTime : 505
ETicketability : Yes
Equipment : 738
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : No polled avail exists
OptionalServicesIndicator : false
AvailabilitySource : A
AvailabilityDisplayType : General

Air Segment 2

Key : asfh927Q2BKAGGVsIAAAAA==
Group : 0
Carrier : WY
FlightNumber : 5727
Origin : KUL
Destination : CGK
DepartureTime : 2017-09-01T22:05:00.000+08:00
ArrivalTime : 2017-09-01T23:05:00.000+07:00
FlightTime : 120
TravelTime : 505
ETicketability : Yes
Equipment : 738
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 3

Key : asfh927Q2BKAIGVsIAAAAA==
Group : 0
Carrier : VA
FlightNumber : 5523
Origin : DEL
Destination : SIN
DepartureTime : 2017-09-01T09:00:00.000+05:30
ArrivalTime : 2017-09-01T17:25:00.000+08:00
FlightTime : 355
TravelTime : 530
ETicketability : Yes
Equipment : 772
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 4

Key : asfh927Q2BKAKGVsIAAAAA==
Group : 0
Carrier : VA
FlightNumber : 5632
Origin : SIN
Destination : CGK
DepartureTime : 2017-09-01T18:30:00.000+08:00
ArrivalTime : 2017-09-01T19:20:00.000+07:00
FlightTime : 110
TravelTime : 530
ETicketability : Yes
Equipment : 773
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 5

Key : asfh927Q2BKAMGVsIAAAAA==
Group : 0
Carrier : SQ
FlightNumber : 401
Origin : DEL
Destination : SIN
DepartureTime : 2017-09-01T09:00:00.000+05:30
ArrivalTime : 2017-09-01T17:25:00.000+08:00
FlightTime : 355
TravelTime : 530
ETicketability : Yes
Equipment : 772
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 6

Key : asfh927Q2BKAOGVsIAAAAA==
Group : 0
Carrier : SQ
FlightNumber : 966
Origin : SIN
Destination : CGK
DepartureTime : 2017-09-01T18:30:00.000+08:00
ArrivalTime : 2017-09-01T19:20:00.000+07:00
FlightTime : 110
TravelTime : 530
ETicketability : Yes
Equipment : 773
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 7

Key : asfh927Q2BKAQGVsIAAAAA==
Group : 0
Carrier : SQ
FlightNumber : 403
Origin : DEL
Destination : SIN
DepartureTime : 2017-09-01T21:55:00.000+05:30
ArrivalTime : 2017-09-02T06:10:00.000+08:00
FlightTime : 345
TravelTime : 530
ETicketability : Yes
Equipment : 388
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 8

Key : asfh927Q2BKASGVsIAAAAA==
Group : 0
Carrier : PG
FlightNumber : 4361
Origin : SIN
Destination : CGK
DepartureTime : 2017-09-02T07:25:00.000+08:00
ArrivalTime : 2017-09-02T08:15:00.000+07:00
FlightTime : 110
TravelTime : 530
ETicketability : Yes
Equipment : 738
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : No polled avail exists
OptionalServicesIndicator : false
AvailabilitySource : O
AvailabilityDisplayType : General

Air Segment 9

Key : asfh927Q2BKAUGVsIAAAAA==
Group : 0
Carrier : VA
FlightNumber : 5695
Origin : DEL
Destination : SIN
DepartureTime : 2017-09-01T21:55:00.000+05:30
ArrivalTime : 2017-09-02T06:10:00.000+08:00
FlightTime : 345
TravelTime : 540
ETicketability : Yes
Equipment : 388
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 10

Key : asfh927Q2BKAWGVsIAAAAA==
Group : 0
Carrier : VA
FlightNumber : 5621
Origin : SIN
Destination : CGK
DepartureTime : 2017-09-02T07:40:00.000+08:00
ArrivalTime : 2017-09-02T08:25:00.000+07:00
FlightTime : 105
TravelTime : 540
ETicketability : Yes
Equipment : 773
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 11

Key : asfh927Q2BKAYGVsIAAAAA==
Group : 0
Carrier : SQ
FlightNumber : 403
Origin : DEL
Destination : SIN
DepartureTime : 2017-09-01T21:55:00.000+05:30
ArrivalTime : 2017-09-02T06:10:00.000+08:00
FlightTime : 345
TravelTime : 540
ETicketability : Yes
Equipment : 388
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 12

Key : asfh927Q2BKAaGVsIAAAAA==
Group : 0
Carrier : SQ
FlightNumber : 952
Origin : SIN
Destination : CGK
DepartureTime : 2017-09-02T07:40:00.000+08:00
ArrivalTime : 2017-09-02T08:25:00.000+07:00
FlightTime : 105
TravelTime : 540
ETicketability : Yes
Equipment : 773
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 13

Key : asfh927Q2BKAcGVsIAAAAA==
Group : 0
Carrier : OD
FlightNumber : 206
Origin : DEL
Destination : KUL
DepartureTime : 2017-09-01T22:05:00.000+05:30
ArrivalTime : 2017-09-02T06:00:00.000+08:00
FlightTime : 325
TravelTime : 540
ETicketability : Yes
Equipment : 739
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : No polled avail exists
OptionalServicesIndicator : false
AvailabilitySource : O
AvailabilityDisplayType : General

Air Segment 14

Key : asfh927Q2BKAeGVsIAAAAA==
Group : 0
Carrier : OD
FlightNumber : 320
Origin : KUL
Destination : CGK
DepartureTime : 2017-09-02T07:30:00.000+08:00
ArrivalTime : 2017-09-02T08:35:00.000+07:00
FlightTime : 125
TravelTime : 540
ETicketability : Yes
Equipment : 738
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : No polled avail exists
OptionalServicesIndicator : false
AvailabilitySource : O
AvailabilityDisplayType : General

Air Segment 15

Key : asfh927Q2BKAgGVsIAAAAA==
Group : 0
Carrier : SQ
FlightNumber : 401
Origin : DEL
Destination : SIN
DepartureTime : 2017-09-01T09:00:00.000+05:30
ArrivalTime : 2017-09-01T17:25:00.000+08:00
FlightTime : 355
TravelTime : 550
ETicketability : Yes
Equipment : 772
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : Polled avail used
OptionalServicesIndicator : false
AvailabilitySource : S
AvailabilityDisplayType : General

Air Segment 16

Key : asfh927Q2BKAiGVsIAAAAA==
Group : 0
Carrier : PG
FlightNumber : 4307
Origin : SIN
Destination : CGK
DepartureTime : 2017-09-01T18:45:00.000+08:00
ArrivalTime : 2017-09-01T19:40:00.000+07:00
FlightTime : 115
TravelTime : 550
ETicketability : Yes
Equipment : 738
ChangeOfPlane : false
ParticipantLevel : Secure Sell
LinkAvailability : true
PolledAvailabilityOption : No polled avail exists
OptionalServicesIndicator : false
AvailabilitySource : O
AvailabilityDisplayType : General

Thank you ...

**Comment by vivekjyotipramanik** [comment]
Hi  Alex0084,

Please find below the link with the complete details about the connection logic. The Connection element will appear in LowFareSearchRsp if there is a connection. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/Content/Air/Shared_Air_Topics/AirSegmentConnectionLogic.htm

**Comment by Alex0084** [comment]
Thank you so much for the help...
