### ISSUE TITLE
Activate test credentials

### ISSUE THREAD

**Issue by tinasherobert** [Travelport/travelport-uapi-tutorial-php#87]
Hello,

Please activate below test credentials.

Universal API User ID: Universal API/uAPI7341562091-18e3a6e9
TargetBranch : Branch Code for Galileo (1G): P7002716

**Comment by vivekjyotipramanik** [comment]
Hi tinasherobert,

We are working on this and will provide an update as soon as it is unlocked. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi tinasherobert,

We have unlocked the account. Could you please try again. Please let us know how it goes. Thanks.

**Comment by tinasherobert** [comment]
Thanx very much

**Comment by asadsaeed83** [comment]
i am unable to login with my test  credentials ,Please help me out this matter ,Error 500 generated
Universal API User ID:  Universal API/uAPI1128768630 

Please authorized this account
