### ISSUE TITLE
Booking history

### ISSUE THREAD

**Issue by sivaneshc** [Travelport/travelport-uapi-tutorial-php#88]
Hi, 

How can i retrieve all booking history. Is there any request?

Thank you.

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

We can use the UniversalRecordHistoryReq to get all the previous booking history on a particular UR. Please find below the link with the details. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/uAPI.htm#Booking/UniversalRecord/Requesting_a_Universal_Record_History.htm

**Comment by sivaneshc** [comment]
Hi vivekjyotipramanik,

Can you please share sample request and response xml?

Thank you.

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

UR history is all bout the previous booking history for a particular UR. Please find below the sample request and response. Please find below the link with the XML samples. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/Content/SampleWeb/SampleFiles/069-14_1G_UnivRecordHistory_Rq.xml

https://support.travelport.com/webhelp/uapi/Content/SampleWeb/SampleFiles/069-14_1G_UnivRecordHistory_Rs.xml

https://support.travelport.com/webhelp/uapi/uAPI.htm#SampleWeb/By_Transaction/Samples_UnivRecordHistory.htm

**Comment by sivaneshc** [comment]
Hi vivekjyotipramanik,

Thanks for your response.
my question is how can I retrieve last 10 bookings from my account?

Thank you

**Comment by vivekjyotipramanik** [comment]
Hi sivaneshc,

I believe for UniversalRecordSearch you are using incorrect endpoint. The endpoint should be UniversalRecordService URL. Please find below the complete endpoint URL. Please let us know how it goes. Thanks.

https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/UniversalRecordService

**Comment by sivaneshc** [comment]
Hi vivekjyotipramanik,

Thank you so much for your response. Its working fine.
Is there any option to search by createdDate range?

Thank you.

**Comment by vivekjyotipramanik** [comment]
Hi  sivaneshc,

I believe currently it is only available for TravelDate range. Please find below the xml request and response sample. Please let us know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/Content/SampleWeb/SampleFiles/014-01_ACH_UnivRecordSearch_Rq.xml

https://support.travelport.com/webhelp/uapi/Content/SampleWeb/SampleFiles/014-01_ACH_UnivRecordSearch_Rs.xml

**Comment by sivaneshc** [comment]
Hi vivekjyotipramanik,

Ok. Thank you

**Comment by anantksingh** [comment]
Hi vivekjyotipramanik,

Thanks for your response.
my question is how can I retrieve last bookings from my account?
I tried UniversalRecordSearchReq method but i got error message "Error 404: SRVE0295E: Error reported: 404";
I want to check https://americas.universal-api.pp.travelport.com/B2BGateway/connect/uAPI/UniversalRecordService

Booking Response
Soap Struture 1:
[universalUniversalRecord] => Array
(
	[@attributes] => Array
		(
			[LocatorCode] => EDQQ17
			[Version] => 0
			[Status] => Active
		
		)
)
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:univ="http://www.travelport.com/schema/universal_v44_0" xmlns:ses="http://www.travelport.com/soa/common/security/SessionContext_v1" xmlns:com="http://www.travelport.com/schema/common_v44_0">
<soapenv:Body>
	<univ:UniversalRecordRetrieveReq TargetBranch="xxx" RetrieveProviderReservationDetails="false">
	  <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
	  <univ:UniversalRecordLocatorCode>EDQQ17</univ:UniversalRecordLocatorCode>
	</univ:UniversalRecordRetrieveReq>
</soapenv:Body>
</soapenv:Envelope>						

Error 404: SRVE0295E: Error reported: 404

Soap Struture 2:
Booking Response
[universalProviderReservationInfo] => Array
	(
		[@attributes] => Array
			(
				[Key] => xuCplX7Q2BKA4c4kAAAAAA==
				[ProviderCode] => 1G
				[LocatorCode] => JTM3GT
				[CreateDate] => 2018-09-17T12:57:37.701+00:00
				[ModifiedDate] => 2018-09-17T12:57:37.701+00:00
				[HostCreateDate] => 2018-09-17
				[OwningPCC] => 5Y34
			)

	)
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:univ="http://www.travelport.com/schema/universal_v44_0" xmlns:ses="http://www.travelport.com/soa/common/security/SessionContext_v1" xmlns:com="http://www.travelport.com/schema/common_v44_0">
<soapenv:Body>
  <univ:UniversalRecordRetrieveReq TargetBranch="xxx" RetrieveProviderReservationDetails="false">
	<com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
	<univ:ProviderReservationInfo ProviderCode="1G" ProviderLocatorCode="JTM3GT"/>
  </univ:UniversalRecordRetrieveReq>
</soapenv:Body>
</soapenv:Envelope>	
Error 404: SRVE0295E: Error reported: 404
Thank you

**Comment by vivekjyotipramanik** [comment]
Hi  anantksingh,

Could you please confirm if you are sending correct TargetBranch. Thanks.

**Comment by anantksingh** [comment]
Hi @Vivekjyoti,
please find

Booking Response
Soap Struture 1:
[universalUniversalRecord] => Array
(
	[@attributes] => Array
		(
			[LocatorCode] => EDQQ17
			[Version] => 0
			[Status] => Active
		
		)
)
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:univ="http://www.travelport.com/schema/universal_v44_0" xmlns:ses="http://www.travelport.com/soa/common/security/SessionContext_v1" xmlns:com="http://www.travelport.com/schema/common_v44_0">
<soapenv:Body>
	<univ:UniversalRecordRetrieveReq TargetBranch="P7065745" RetrieveProviderReservationDetails="false">
	  <com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
	  <univ:UniversalRecordLocatorCode>EDQQ17</univ:UniversalRecordLocatorCode>
	</univ:UniversalRecordRetrieveReq>
</soapenv:Body>
</soapenv:Envelope>						

Error 404: SRVE0295E: Error reported: 404

Soap Struture 2:
Booking Response
[universalProviderReservationInfo] => Array
	(
		[@attributes] => Array
			(
				[Key] => xuCplX7Q2BKA4c4kAAAAAA==
				[ProviderCode] => 1G
				[LocatorCode] => JTM3GT
				[CreateDate] => 2018-09-17T12:57:37.701+00:00
				[ModifiedDate] => 2018-09-17T12:57:37.701+00:00
				[HostCreateDate] => 2018-09-17
				[OwningPCC] => 5Y34
			)

	)
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:univ="http://www.travelport.com/schema/universal_v44_0" xmlns:ses="http://www.travelport.com/soa/common/security/SessionContext_v1" xmlns:com="http://www.travelport.com/schema/common_v44_0">
<soapenv:Body>
  <univ:UniversalRecordRetrieveReq TargetBranch="P7065745" RetrieveProviderReservationDetails="false">
	<com:BillingPointOfSaleInfo OriginApplication="UAPI"/>
	<univ:ProviderReservationInfo ProviderCode="1G" ProviderLocatorCode="JTM3GT"/>
  </univ:UniversalRecordRetrieveReq>
</soapenv:Body>
</soapenv:Envelope>	
Error 404: SRVE0295E: Error reported: 404
