### ISSUE TITLE
Filter options.

### ISSUE THREAD

**Issue by Alex0084** [Travelport/travelport-uapi-tutorial-php#89]
Hello,

Please we are stuck in how to make Filter option for number of stop's?

Can you please provide us the code for it?

Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi  Alex0084,

Could you please explain your question a little bit more. Could you please provide the details which cod you are looking for and in what programming language. Could you please confirm if you are asking for stops modifiers in request and if so is it LowFareSearchReq or AirAvailabilityReq or any other request.
