### ISSUE TITLE
How to insert auth info

### ISSUE THREAD

**Issue by ps554808667** [Travelport/travelport-uapi-tutorial-php#95]
Hi,
How to insert auth info(like username and password )?  I find code sample to do "Authentication credentials" in PHP on this site: https://github.com/Travelport/travelport-uapi-tutorial-php/blob/master/Air/phpSample_Air_LFS.php  
  but our engineer develop with JAVA, and I can't find how to insert  username and password in the site your have given to me: https://github.com/Travelport/travelport-uapi-tutorial/tree/master    
I can't find how to insert  username and password.
Thank you so much!

**Comment by ps554808667** [comment]
Hi,
    Another question about Authentication credentials, I can,t pass Validation in soapui tools now. And I can successful last week.



![image](https://user-images.githubusercontent.com/30485823/30852469-71c2a318-a2de-11e7-8660-67f371f70773.png)

**Comment by vivekjyotipramanik** [comment]
Hi ps554808667,

The way you are using the authentication is correct. I believe there is some issue with the request you are using. Could you please send us the request xml. Thanks.

**Comment by vivekjyotipramanik** [comment]
Hi ps554808667,

For Java we generally use the run configurations for the testing code, that is why it is not showing in the java code base. But we are using the username/password ion the below code. Please let us know how it goes. Thanks.

https://github.com/Travelport/travelport-uapi-tutorial/blob/master/src/com/travelport/tutorial/support/PortWrapper.java

**Comment by ps554808667** [comment]
Hi vivekjyotipramanik,
    Thank you for your response, I have solved this problem.
